# Generated by Django 4.2.29 on 2026-03-21 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_auditlog_retain_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('field_value', 'Field Value'), ('calculation', 'Calculation'), ('comparison', 'Comparison'), ('reference', 'Reference'), ('cross_document', 'Cross Document'), ('statistical', 'Statistical'), ('screenshot', 'Screenshot')], max_length=32)),
                ('field_name', models.CharField(blank=True, max_length=128)),
                ('field_name_ar', models.CharField(blank=True, max_length=128)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('linked_document_type', models.CharField(blank=True, max_length=32)),
                ('linked_document_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Evidence',
                'verbose_name_plural': 'Audit Evidence Items',
                'db_table': 're_audit_evidence',
                'ordering': ['evidence_type'],
            },
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=32)),
                ('rule_version', models.PositiveSmallIntegerField()),
                ('applied_severity', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=16)),
                ('explanation', models.TextField()),
                ('explanation_ar', models.TextField(blank=True)),
                ('risk_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('blocks_approval', models.BooleanField(default=False)),
                ('raw_output', models.JSONField(blank=True, default=dict, help_text='Unstructured output dict returned by the rule class.')),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Result',
                'verbose_name_plural': 'Audit Results',
                'db_table': 're_audit_result',
            },
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=32)),
                ('document_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=16)),
                ('engine_version', models.CharField(default='2.0', max_length=16)),
                ('triggered_by', models.CharField(choices=[('upload', 'Upload'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('reprocess', 'Reprocess')], default='upload', max_length=16)),
                ('total_rules', models.PositiveSmallIntegerField(default=0)),
                ('passed_rules', models.PositiveSmallIntegerField(default=0)),
                ('failed_rules', models.PositiveSmallIntegerField(default=0)),
                ('warning_rules', models.PositiveSmallIntegerField(default=0)),
                ('skipped_rules', models.PositiveSmallIntegerField(default=0)),
                ('error_rules', models.PositiveSmallIntegerField(default=0)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16, null=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('blocks_approval', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of error dicts recorded during execution.')),
            ],
            options={
                'verbose_name': 'Audit Run',
                'verbose_name_plural': 'Audit Runs',
                'db_table': 're_audit_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('po_to_invoice', 'Purchase Order → Invoice'), ('invoice_to_payment', 'Invoice → Payment'), ('payroll_to_bank', 'Payroll → Bank Statement'), ('tax_to_invoice', 'Tax Return → Invoice'), ('asset_to_purchase', 'Fixed Asset → Purchase'), ('expense_to_receipt', 'Expense → Receipt')], max_length=32)),
                ('source_document_type', models.CharField(max_length=32)),
                ('source_document_id', models.UUIDField(db_index=True)),
                ('target_document_type', models.CharField(max_length=32)),
                ('target_document_id', models.UUIDField(db_index=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('partial', 'Partial'), ('unmatched', 'Unmatched'), ('conflict', 'Conflict')], default='unmatched', max_length=16)),
                ('match_score', models.DecimalField(blank=True, decimal_places=3, help_text='Normalised similarity score in the range [0, 1].', max_digits=4, null=True)),
                ('match_details', models.JSONField(blank=True, default=dict, help_text="Structured details of what was compared and how, e.g. {'amount_match': True, 'date_delta_days': 3, 'vendor_match': True}.")),
                ('auto_detected', models.BooleanField(default=True, help_text='True when the link was created automatically by a rule.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cross-Document Link',
                'verbose_name_plural': 'Cross-Document Links',
                'db_table': 're_cross_document_link',
            },
        ),
        migrations.CreateModel(
            name='ManualReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated'), ('deferred', 'Deferred')], max_length=16)),
                ('notes', models.TextField(blank=True, help_text="Free-text notes justifying the reviewer's decision.")),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('is_false_positive', models.BooleanField(default=False, help_text='True when the reviewer determines the rule fired incorrectly for this document.  Used for rule quality reporting.')),
                ('false_positive_reason', models.TextField(blank=True, help_text='Reason the reviewer considers this a false positive.')),
            ],
            options={
                'verbose_name': 'Manual Review Decision',
                'verbose_name_plural': 'Manual Review Decisions',
                'db_table': 're_manual_review_decision',
            },
        ),
        migrations.CreateModel(
            name='RiskScoreSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=32)),
                ('document_id', models.UUIDField(db_index=True, help_text='UUID of the audited document in its own table.', unique=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, help_text='Composite risk score (0 – 100).', max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('fraud_indicators', models.PositiveSmallIntegerField(default=0, help_text='Number of rules tagged as fraud indicators that failed.')),
                ('compliance_failures', models.PositiveSmallIntegerField(default=0, help_text='Number of compliance rules that failed.')),
                ('blocking_failures', models.PositiveSmallIntegerField(default=0, help_text='Number of failures on rules marked blocks_approval.')),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('blocks_approval', models.BooleanField(default=False)),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text="Dict keyed by rule category with per-category score contributions, e.g. {'data_integrity': 10.5, 'compliance': 5.0}.")),
                ('top_failed_rules', models.JSONField(blank=True, default=list, help_text='Ordered list of dicts describing the highest-impact failures, each with keys: rule_code, severity, risk_contribution, explanation.')),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Score Summary',
                'verbose_name_plural': 'Risk Score Summaries',
                'db_table': 're_risk_score_summary',
            },
        ),
        migrations.CreateModel(
            name='RuleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Sheet'), ('expense', 'Expense Report'), ('tax_return', 'VAT / Tax Return'), ('fixed_asset', 'Fixed Asset Register'), ('sales_receipt', 'Sales Receipt'), ('other', 'Other')], db_index=True, max_length=32)),
                ('applicability', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('conditional', 'Conditional')], default='full', max_length=16)),
                ('condition_expression', models.JSONField(blank=True, default=dict, help_text='JSONLogic expression evaluated at runtime against the normalised document payload. Rule is skipped when the expression evaluates to False.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('severity_override', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=16, null=True)),
                ('config_override', models.JSONField(blank=True, default=dict, help_text='JSON object deep-merged on top of RuleDefinition.default_config.')),
                ('blocks_approval_override', models.BooleanField(blank=True, help_text='When set, overrides RuleDefinition.blocks_approval for this assignment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule Assignment',
                'verbose_name_plural': 'Rule Assignments',
                'db_table': 're_rule_assignment',
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('category', models.CharField(choices=[('data_integrity', 'Data Integrity'), ('financial_logic', 'Financial Logic'), ('compliance', 'Compliance'), ('anomaly', 'Anomaly'), ('risk', 'Risk'), ('reconciliation', 'Reconciliation')], max_length=32)),
                ('rule_type', models.CharField(choices=[('validation', 'Validation'), ('compliance', 'Compliance'), ('anomaly', 'Anomaly'), ('reconciliation', 'Reconciliation'), ('risk', 'Risk')], max_length=32)),
                ('scope', models.CharField(choices=[('generic', 'Generic'), ('specialized', 'Specialized'), ('cross_document', 'Cross Document')], max_length=32)),
                ('default_severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=16)),
                ('implementation_class', models.CharField(help_text="Dotted Python import path to the class that implements this rule, e.g. 'apps.rule_engine.rules.generic.missing_fields.MissingFieldsRule'.", max_length=256)),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Default JSON configuration passed to the rule at runtime.')),
                ('blocks_approval', models.BooleanField(default=False, help_text='When True a failure on this rule prevents document approval.')),
                ('requires_cross_document', models.BooleanField(default=False, help_text='Rule needs data from more than one document.')),
                ('requires_external_reference', models.BooleanField(default=False, help_text='Rule queries an external data source (e.g. VAT registry).')),
                ('requires_historical_comparison', models.BooleanField(default=False, help_text='Rule compares against historical records for the same entity.')),
                ('is_ai_rule', models.BooleanField(default=False, help_text='Rule delegates to an AI/ML model for evaluation.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system_rule', models.BooleanField(default=True, help_text='System rules ship with the platform and cannot be deleted.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_reason', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule Definition',
                'verbose_name_plural': 'Rule Definitions',
                'db_table': 're_rule_definition',
            },
        ),
        migrations.CreateModel(
            name='RuleDefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text="BCP-47 language tag, e.g. 'en' or 'ar'.", max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('fail_message', models.TextField(help_text='Template string shown when this rule fails. May contain {field} placeholders.')),
                ('pass_message', models.TextField(blank=True, help_text='Template string shown when this rule passes (optional).')),
                ('suggested_action', models.TextField(blank=True, help_text='Guidance for the reviewer when the rule fails.')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rule_engine.ruledefinition')),
            ],
            options={
                'verbose_name': 'Rule Definition Translation',
                'verbose_name_plural': 'Rule Definition Translations',
                'db_table': 're_rule_definition_translation',
            },
        ),
        migrations.AddIndex(
            model_name='ruledefinition',
            index=models.Index(fields=['category', 'is_active'], name='re_ruledef_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='ruledefinition',
            index=models.Index(fields=['rule_type', 'scope'], name='re_ruledef_type_scope_idx'),
        ),
        migrations.AddField(
            model_name='ruleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleassignment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='NULL = system default that applies to all organisations unless a more specific assignment exists for a given org.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_assignments', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='ruleassignment',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rule_engine.ruledefinition'),
        ),
        migrations.AddField(
            model_name='riskscoresummary',
            name='latest_audit_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_summary', to='rule_engine.auditrun'),
        ),
        migrations.AddField(
            model_name='riskscoresummary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_summaries', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='manualreviewdecision',
            name='audit_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_review', to='rule_engine.auditresult'),
        ),
        migrations.AddField(
            model_name='manualreviewdecision',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossdocumentlink',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_document_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crossdocumentlink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_document_links', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_runs', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='audit_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rule_engine.auditrun'),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='rule_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='rule_engine.ruleassignment'),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='audit_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='rule_engine.auditresult'),
        ),
        migrations.AlterUniqueTogether(
            name='ruledefinitiontranslation',
            unique_together={('rule', 'language')},
        ),
        migrations.AddIndex(
            model_name='ruleassignment',
            index=models.Index(fields=['document_type', 'status'], name='re_assign_doctype_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleassignment',
            index=models.Index(fields=['organization', 'document_type'], name='re_assignment_org_doctype_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleassignment',
            unique_together={('rule', 'document_type', 'organization')},
        ),
        migrations.AddIndex(
            model_name='riskscoresummary',
            index=models.Index(fields=['organization', 'risk_level'], name='re_risk_org_level_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscoresummary',
            index=models.Index(fields=['blocks_approval'], name='re_risk_blocks_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdocumentlink',
            index=models.Index(fields=['source_document_type', 'source_document_id'], name='re_cdlink_source_idx'),
        ),
        migrations.AddIndex(
            model_name='crossdocumentlink',
            index=models.Index(fields=['organization', 'link_type', 'match_status'], name='re_cdlink_org_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrun',
            index=models.Index(fields=['organization', 'document_type', 'document_id'], name='re_run_org_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrun',
            index=models.Index(fields=['status', 'started_at'], name='re_run_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='auditresult',
            index=models.Index(fields=['rule_code', 'status'], name='re_result_rulecode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditresult',
            index=models.Index(fields=['audit_run', 'applied_severity'], name='re_result_run_severity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditresult',
            unique_together={('audit_run', 'rule_code')},
        ),
    ]
