# Generated by Django 4.2.29 on 2026-03-22 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFieldDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_field_code', models.CharField(db_index=True, help_text='References CanonicalFieldDefinition.field_code', max_length=100)),
                ('dependency_type', models.CharField(choices=[('required', 'Required — rule returns NOT_APPLICABLE if absent'), ('optional', 'Optional — rule degrades gracefully'), ('supporting', 'Supporting — used for evidence/context only'), ('cross_doc', 'Cross-Document — needs a linked document')], default='required', max_length=20)),
                ('null_behavior', models.CharField(choices=[('not_applicable', 'Return NOT_APPLICABLE'), ('fail', 'Fail the rule'), ('warning', 'Return WARNING'), ('skip', 'Skip this sub-check only')], default='not_applicable', max_length=20)),
                ('null_message_en', models.CharField(blank=True, max_length=500)),
                ('null_message_ar', models.CharField(blank=True, max_length=500)),
                ('linked_document_type', models.CharField(blank=True, max_length=50)),
                ('rule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_dependencies', to='rule_engine.ruledefinition')),
            ],
            options={
                'verbose_name': 'Rule Field Dependency',
                'verbose_name_plural': 'Rule Field Dependencies',
                'unique_together': {('rule_definition', 'canonical_field_code')},
            },
        ),
    ]
