# Generated by Django 4.2.29 on 2026-03-25

from django.db import migrations


GAAP_RULES = [
    {
        "rule_code": "GAAP-COMP-001",
        "version": 1,
        "category": "compliance",
        "rule_type": "validation",
        "scope": "generic",
        "default_severity": "high",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.completeness.GAAPCompletenessCoreFieldsRule",
        "default_config": {
            "required_fields": ["date", "amount", "account", "counterparty", "supporting_reference"],
        },
        "blocks_approval": True,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "completeness"],
    },
    {
        "rule_code": "GAAP-CUT-001",
        "version": 1,
        "category": "compliance",
        "rule_type": "compliance",
        "scope": "generic",
        "default_severity": "high",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.cutoff.GAAPCutoffPeriodRule",
        "default_config": {"max_posting_gap_days": 7},
        "blocks_approval": True,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "cutoff"],
    },
    {
        "rule_code": "GAAP-DOC-001",
        "version": 1,
        "category": "compliance",
        "rule_type": "compliance",
        "scope": "generic",
        "default_severity": "high",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.documentation.GAAPDocumentationSupportRule",
        "default_config": {"materiality_amount": "10000"},
        "blocks_approval": True,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "documentation"],
    },
    {
        "rule_code": "GAAP-CLS-001",
        "version": 1,
        "category": "financial_logic",
        "rule_type": "validation",
        "scope": "specialized",
        "default_severity": "medium",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.classification.GAAPClassificationCapexOpexRule",
        "default_config": {"capex_threshold": "5000"},
        "blocks_approval": False,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "classification"],
    },
    {
        "rule_code": "GAAP-REV-001",
        "version": 1,
        "category": "compliance",
        "rule_type": "compliance",
        "scope": "specialized",
        "default_severity": "high",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.recognition.GAAPRevenueRecognitionRule",
        "default_config": {},
        "blocks_approval": True,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "recognition", "revenue"],
    },
    {
        "rule_code": "GAAP-EXP-001",
        "version": 1,
        "category": "financial_logic",
        "rule_type": "compliance",
        "scope": "specialized",
        "default_severity": "medium",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.recognition.GAAPExpenseMatchingRule",
        "default_config": {"max_period_gap_days": 90},
        "blocks_approval": False,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "matching", "expense"],
    },
    {
        "rule_code": "GAAP-CONS-001",
        "version": 1,
        "category": "compliance",
        "rule_type": "validation",
        "scope": "generic",
        "default_severity": "medium",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.consistency.GAAPConsistencyTreatmentRule",
        "default_config": {},
        "blocks_approval": False,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "consistency"],
    },
    {
        "rule_code": "GAAP-ANO-001",
        "version": 1,
        "category": "anomaly",
        "rule_type": "anomaly",
        "scope": "generic",
        "default_severity": "high",
        "implementation_class": "apps.rule_engine.rules.gaap.categories.anomaly.GAAPAnomalyPatternRule",
        "default_config": {"materiality_amount": "50000", "rounded_step": "1000"},
        "blocks_approval": False,
        "is_active": True,
        "is_system_rule": True,
        "tags": ["gaap", "anomaly", "materiality"],
    },
]


GAAP_ASSIGNMENTS = {
    "GAAP-COMP-001": ["sales_invoice", "purchase_order", "expense", "bank_statement", "other"],
    "GAAP-CUT-001": ["sales_invoice", "purchase_order", "expense", "tax_return", "other"],
    "GAAP-DOC-001": ["sales_invoice", "purchase_order", "expense", "fixed_asset", "other"],
    "GAAP-CLS-001": ["expense", "purchase_order", "fixed_asset", "sales_invoice", "other"],
    "GAAP-REV-001": ["sales_invoice", "sales_receipt", "other"],
    "GAAP-EXP-001": ["expense", "purchase_order", "sales_invoice", "other"],
    "GAAP-CONS-001": ["sales_invoice", "purchase_order", "expense", "bank_statement", "other"],
    "GAAP-ANO-001": ["sales_invoice", "purchase_order", "expense", "bank_statement", "sales_receipt", "other"],
}


def seed_gaap_rules(apps, schema_editor):
    RuleDefinition = apps.get_model("rule_engine", "RuleDefinition")
    RuleAssignment = apps.get_model("rule_engine", "RuleAssignment")

    code_to_obj = {}
    for rule in GAAP_RULES:
        obj, _ = RuleDefinition.objects.update_or_create(
            rule_code=rule["rule_code"],
            defaults={k: v for k, v in rule.items() if k != "rule_code"},
        )
        code_to_obj[rule["rule_code"]] = obj

    for rule_code, document_types in GAAP_ASSIGNMENTS.items():
        for document_type in document_types:
            RuleAssignment.objects.update_or_create(
                rule=code_to_obj[rule_code],
                document_type=document_type,
                organization=None,
                defaults={
                    "status": "active",
                    "applicability": "full",
                    "config_override": {},
                    "blocks_approval_override": None,
                },
            )


def unseed_gaap_rules(apps, schema_editor):
    RuleDefinition = apps.get_model("rule_engine", "RuleDefinition")
    codes = [row["rule_code"] for row in GAAP_RULES]
    RuleDefinition.objects.filter(rule_code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rule_engine", "0002_canonical_schema"),
    ]

    operations = [
        migrations.RunPython(seed_gaap_rules, reverse_code=unseed_gaap_rules),
    ]
