# Generated by Django 4.2.29 on 2026-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_seed_gaap_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleassignment',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Sheet'), ('expense', 'Expense Report'), ('tax_return', 'VAT / Tax Return'), ('fixed_asset', 'Fixed Asset Register'), ('sales_receipt', 'Sales Receipt'), ('grn', 'Goods Receipt Note'), ('payment', 'Payment Voucher'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
