# Generated by Django 4.2.30 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0006_backfill_audit_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrunv2metadata',
            name='decision',
            field=models.JSONField(blank=True, default=dict, help_text='Final decision: action, confidence, auto_action, escalate_to, reasoning, blocking_rules, risk_snapshot, ai_snapshot.'),
        ),
        migrations.AlterField(
            model_name='auditrunv2metadata',
            name='pipeline_version',
            field=models.CharField(default='3.0', help_text='AuditPipelineV2 version string at time of execution.', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditrunv2metadata',
            name='stages_skipped',
            field=models.JSONField(blank=True, default=list, help_text='List of stage names that were skipped (e.g. ai_engine for low-risk docs).'),
        ),
        migrations.AlterField(
            model_name='crossdocumentlink',
            name='link_type',
            field=models.CharField(choices=[('po_to_invoice', 'Purchase Order → Invoice'), ('grn_to_po', 'Goods Receipt → Purchase Order'), ('grn_to_invoice', 'Goods Receipt → Invoice'), ('invoice_to_payment', 'Invoice → Payment'), ('payroll_to_bank', 'Payroll → Bank Statement'), ('tax_to_invoice', 'Tax Return → Invoice'), ('asset_to_purchase', 'Fixed Asset → Purchase'), ('expense_to_receipt', 'Expense → Receipt')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ruleassignment',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Sheet'), ('expense', 'Expense Report'), ('expense_report', 'Expense Report'), ('tax_return', 'VAT / Tax Return'), ('fixed_asset', 'Fixed Asset Register'), ('sales_receipt', 'Sales Receipt'), ('grn', 'Goods Receipt Note'), ('payment', 'Payment Voucher'), ('payment_voucher', 'Payment Voucher'), ('purchase_invoice', 'Purchase Invoice'), ('sales_order', 'Sales Order'), ('quotation', 'Quotation'), ('proforma_invoice', 'Proforma Invoice'), ('receipt_voucher', 'Receipt Voucher'), ('cash_voucher', 'Cash Voucher'), ('journal_entry', 'Journal Entry'), ('general_ledger', 'General Ledger'), ('ledger', 'Ledger'), ('contract', 'Contract'), ('supplier_statement', 'Supplier Statement'), ('customer_statement', 'Customer Statement'), ('tax_vat_document', 'Tax / VAT Document'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
