# Generated by Django 4.2.30 on 2026-07-30 13:18

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used for /partners/<slug>/. Unique across all partners.', max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='An approved partner logo is INTENDED to be public, so ordinary media storage is correct here. This is not the private-document path used for commercial registrations and certificates (Phase 2B).', null=True, upload_to='partners/logos/')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('short_description', models.CharField(blank=True, help_text='Card blurb on /partners/.', max_length=300)),
                ('long_description', models.TextField(blank=True, help_text='Detail page body.')),
                ('website', models.URLField(blank=True)),
                ('partner_type', models.CharField(choices=[('distributor', 'Authorized Distributor'), ('technical', 'Technical Partner'), ('training', 'Training Partner'), ('strategic', 'Strategic Partner')], default='distributor', max_length=20)),
                ('partner_tier', models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('strategic', 'Strategic')], help_text='Commercial level. Blank is valid: a Technical or Training partner may hold no tier, in which case they have no public section.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='INTERNAL. Excluded from PUBLIC_FIELDS — §N requires consent to publish.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='INTERNAL. Excluded from PUBLIC_FIELDS — §N requires consent to publish.', max_length=30)),
                ('source_application', models.UUIDField(blank=True, help_text='Phase 2B will add PartnerApplication and turn this into a real FK. A plain UUID for now so 2A does not ship a half-built application model that 2B would have to migrate around.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Card order within a tier. Lower shows first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='First time this partner was published. Hiding does NOT clear it — the original publication date stays available.', null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['display_order', 'company_name'],
                'indexes': [models.Index(fields=['status', 'partner_tier'], name='partners_pa_status_d4286f_idx'), models.Index(fields=['status', 'partner_type'], name='partners_pa_status_03ac30_idx'), models.Index(fields=['slug'], name='partners_pa_slug_d21a98_idx')],
            },
        ),
    ]
