# Generated by Django 4.2.30 on 2026-07-30 16:17

import apps.partners.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=20)),
                ('requested_partner_type', models.CharField(choices=[('distributor', 'Authorized Distributor'), ('technical', 'Technical Partner'), ('training', 'Training Partner'), ('strategic', 'Strategic Partner')], help_text='What the applicant asked for. The reviewer decides the actual type and tier.', max_length=20)),
                ('business_areas', models.JSONField(blank=True, default=list, help_text='List of BusinessArea values. Validated at the serializer.')),
                ('company_summary', models.TextField(blank=True)),
                ('partnership_reason', models.TextField(blank=True)),
                ('key_clients', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('declaration_accepted', models.BooleanField(default=False, help_text='§E.6 — required. Enforced server-side at the serializer, not just the form.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='INTERNAL. Not echoed verbatim in outbound email.')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, help_text='Personal data. Abuse triage only. Staff-only; never served publicly.', null=True)),
                ('submitted_user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Application',
                'verbose_name_plural': 'Partner Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='partners.partnerapplication')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Application Note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Private storage. Not reachable by URL — see apps/partners/uploads.py.', storage=apps.partners.models.get_partner_document_storage, upload_to='')),
                ('file_type', models.CharField(choices=[('logo', 'Company logo'), ('profile', 'Company profile'), ('commercial_register', 'Commercial registration'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=30)),
                ('original_filename', models.CharField(help_text='DISPLAY ONLY. Never used as the on-disk name — see uploads.safe_stored_name.', max_length=200)),
                ('stored_filename', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, help_text="Detected from the file's actual bytes, not from its extension.", max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.partnerapplication')),
            ],
            options={
                'verbose_name': 'Partner Application Attachment',
                'verbose_name_plural': 'Partner Application Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='source_application',
            field=models.ForeignKey(blank=True, help_text='The application this partner was approved from, when there was one. SET_NULL rather than CASCADE: deleting an application must not delete a live published partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partners', to='partners.partnerapplication'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['status', 'created_at'], name='partners_pa_status_575fef_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['email'], name='partners_pa_email_32a4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['country'], name='partners_pa_country_591b1f_idx'),
        ),
    ]
