# Generated by Django 4.2.30 on 2026-07-30 18:45

import apps.partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerapplication_partnerapplicationnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationattachment',
            name='file',
            field=models.FileField(help_text='Private storage outside MEDIA_ROOT. `.url` RAISES by design — retrieval is the staff-only download endpoint. See apps/partners/uploads.py.', storage=apps.partners.models.get_partner_document_storage, upload_to=''),
        ),
    ]
