# Generated by Django 4.2.30 on 2026-08-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partnerapplicationattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name_ar',
            field=models.CharField(blank=True, help_text='Arabic legal/trading name. Blank falls back to company_name — a partner with no Arabic name should read in Latin script rather than not at all. Follows the Plan.name_ar / name_en pattern.', max_length=200),
        ),
    ]
