# Generated by Django 4.2.30 on 2026-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='long_description_en',
            field=models.TextField(blank=True, help_text='English detail body. Blank falls back to the Arabic one.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='English card blurb. Blank falls back to the Arabic one.', max_length=300),
        ),
        migrations.AlterField(
            model_name='partner',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detail page body — Arabic.'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='short_description',
            field=models.CharField(blank=True, help_text='Card blurb on /partners/ — Arabic.', max_length=300),
        ),
    ]
