# Generated by Django 4.2.30 on 2026-05-03 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('anomaly', 'Streaming anomaly hit'), ('audit_case', 'Audit case created'), ('sla_breach', 'SLA breached')], db_index=True, default='anomaly', max_length=20)),
                ('trigger_detector', models.CharField(blank=True, max_length=64)),
                ('min_severity', models.CharField(choices=[('low', 'Low and above'), ('medium', 'Medium and above'), ('high', 'High and above'), ('critical', 'Critical only')], default='medium', max_length=10)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('cooldown_minutes', models.PositiveSmallIntegerField(default=30, help_text='Suppress duplicate alerts for the same dedup_key within this many minutes.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='authentication.organization')),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(max_length=24)),
                ('channel_target', models.CharField(blank=True, help_text='Email address / Slack webhook / phone number / URL.', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed by cooldown'), ('acknowledged', 'Acknowledged')], db_index=True, max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('severity', models.CharField(blank=True, max_length=12)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='authentication.organization')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'db_table': 'alert_events',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'is_active'], name='alert_rules_organiz_9559e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='alert_rule_unique_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['organization', 'status', 'sent_at'], name='alert_event_organiz_ea4f76_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['rule', 'dedup_key', 'sent_at'], name='alert_event_rule_id_378722_idx'),
        ),
    ]
