# Generated by Django 4.2.30 on 2026-06-14 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical'), ('upload_issue', 'Upload Issue'), ('audit_report', 'Audit Report'), ('subscription', 'Subscription'), ('account_access', 'Account Access'), ('compliance', 'Compliance'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_customer', 'Pending Customer'), ('pending_internal', 'Pending Internal'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('finance', 'Finance'), ('risk', 'Risk'), ('general', 'General')], default='general', max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_crm_notes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_message_added', 'Ticket Message Added'), ('ticket_status_changed', 'Ticket Status Changed'), ('note_added', 'Note Added'), ('crm_role_checked', 'CRM Role Checked'), ('crm_audit_logged', 'CRM Audit Logged'), ('customer_viewed', 'Customer Viewed'), ('general', 'General')], default='general', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Customer Activity',
                'verbose_name_plural': 'Customer Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('internal_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='platform_admin.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='platform_ad_ticket__144f79_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', '-created_at'], name='platform_ad_organiz_b4ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='platform_ad_status_d971af_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='platform_ad_priorit_59c475_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='platform_ad_assigne_c10aff_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='platform_ad_created_b07288_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['organization', '-created_at'], name='platform_ad_organiz_522e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['category'], name='platform_ad_categor_74715f_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['created_at'], name='platform_ad_created_caa3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['organization', '-created_at'], name='platform_ad_organiz_a54e32_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['activity_type'], name='platform_ad_activit_f069d7_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['created_at'], name='platform_ad_created_ca8f91_idx'),
        ),
    ]
