# Generated by Django 4.2.30 on 2026-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivity',
            name='activity_type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_message_added', 'Ticket Message Added'), ('ticket_status_changed', 'Ticket Status Changed'), ('note_added', 'Note Added'), ('crm_role_checked', 'CRM Role Checked'), ('crm_audit_logged', 'CRM Audit Logged'), ('customer_viewed', 'Customer Viewed'), ('general', 'General'), ('subscription_extended', 'Subscription Extended'), ('customer_suspended', 'Customer Suspended'), ('customer_reactivated', 'Customer Reactivated'), ('manual_payment_added', 'Manual Payment Added'), ('manual_payment_confirmed', 'Manual Payment Confirmed'), ('manual_payment_rejected', 'Manual Payment Rejected')], default='general', max_length=32),
        ),
    ]
