# Generated by Django 4.2.29 on 2026-03-20 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_verified_at_emailotpverification'),
        ('storage_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='authentication.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_management.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_path', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storage_management.auditfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_versions', to=settings.AUTH_USER_MODEL)),
                ('storage_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_versions', to='storage_management.storageprovider')),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditFileProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanitized_name', models.CharField(blank=True, help_text='Filesystem-safe version of the original filename.', max_length=255)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Current (latest) version number for this file.')),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata (tags, purpose, custom fields).')),
                ('storage_path', models.TextField(blank=True, help_text='Cached storage path for the latest version — avoids an extra join.')),
                ('audit_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='storage_management.auditfile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_management.folder')),
                ('storage_provider', models.ForeignKey(blank=True, help_text='Storage provider used for the latest version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiled_files', to='storage_management.storageprovider')),
            ],
            options={
                'verbose_name': 'Audit File Profile',
                'verbose_name_plural': 'Audit File Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['organization', 'parent'], name='file_manage_organiz_bbbbe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('organization', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['audit_file', 'version_number'], name='file_manage_audit_f_d46111_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('audit_file', 'version_number')},
        ),
    ]
