"""Phase-1 canonical rule catalog for the 20 supported document types.

Single source of truth — every rule the platform ships with is defined here
as a plain dict so we can:
    • seed `RuleDefinition` + `RuleDefinitionTranslation` (AR/EN) into the DB
    • render labels + recommendations in reports without round-tripping the DB
    • diff future migrations cleanly

Each entry follows this shape:

    {
        "rule_id":           "PI-007",                          # unique code
        "document_type":     "purchase_invoice",                # SupportedDocumentType value
        "name_en":           "Duplicate supplier invoice number",
        "name_ar":           "رقم فاتورة مورد مكرّر",
        "description_en":    "Same invoice number already exists for this supplier.",
        "description_ar":    "نفس رقم الفاتورة موجود مسبقاً لهذا المورد.",
        "severity":          "high",                            # critical / high / medium / low
        "category":          "duplicate_detection",             # see RULE_CATEGORIES
        "rule_type":         "anomaly",                         # validation / compliance / anomaly / reconciliation / risk
        "fail_message_en":   "Invoice {invoice_number} duplicates an earlier invoice from {supplier}.",
        "fail_message_ar":   "الفاتورة {invoice_number} مكرّرة لفاتورة سابقة من {supplier}.",
        "recommendation_en": "Hold payment and verify with the vendor before approving.",
        "recommendation_ar": "احجب الدفع وتأكّد من المورد قبل الاعتماد.",
        "blocks_approval":   True,
    }

`category` values map to RuleCategory in the DB:
    completeness          → data_integrity
    date_validation       → data_integrity
    amount_validation     → data_integrity
    vat_validation        → compliance
    duplicate_detection   → anomaly
    matching              → reconciliation
    approval_control      → compliance
    vendor_customer_risk  → risk
    bank_reconciliation   → reconciliation
    payroll_control       → compliance
    contract_compliance   → compliance
    anomaly_detection     → anomaly
    benford_analysis      → anomaly
    policy_compliance     → compliance
    audit_trail           → compliance

We keep the user-facing "category" name granular so reports can group findings
clearly, and map to the broader DB enum at seed time.
"""
from __future__ import annotations

# ─── Category → RuleCategory enum mapping ──────────────────────────────────
CATEGORY_TO_DB = {
    "completeness":         "data_integrity",
    "date_validation":      "data_integrity",
    "amount_validation":    "financial_logic",
    "vat_validation":       "compliance",
    "duplicate_detection":  "anomaly",
    "matching":             "reconciliation",
    "approval_control":     "compliance",
    "vendor_customer_risk": "risk",
    "bank_reconciliation":  "reconciliation",
    "payroll_control":      "compliance",
    "contract_compliance":  "compliance",
    "anomaly_detection":    "anomaly",
    "benford_analysis":     "anomaly",
    "policy_compliance":    "compliance",
    "audit_trail":          "compliance",
}

# ─── Category → RuleType enum mapping ──────────────────────────────────────
CATEGORY_TO_TYPE = {
    "completeness":         "validation",
    "date_validation":      "validation",
    "amount_validation":    "validation",
    "vat_validation":       "compliance",
    "duplicate_detection":  "anomaly",
    "matching":             "reconciliation",
    "approval_control":     "compliance",
    "vendor_customer_risk": "risk",
    "bank_reconciliation":  "reconciliation",
    "payroll_control":      "compliance",
    "contract_compliance":  "compliance",
    "anomaly_detection":    "anomaly",
    "benford_analysis":     "anomaly",
    "policy_compliance":    "compliance",
    "audit_trail":          "compliance",
}


# ─── Helper to keep entries terse ──────────────────────────────────────────
def _r(rule_id, dtype, name_en, name_ar, severity, category, rec_en, rec_ar,
       *, description_en="", description_ar="", blocks=False, rule_type=None):
    return {
        "rule_id":           rule_id,
        "document_type":     dtype,
        "name_en":           name_en,
        "name_ar":           name_ar,
        "description_en":    description_en or name_en,
        "description_ar":    description_ar or name_ar,
        "severity":          severity,
        "category":          category,
        "rule_type":         rule_type or CATEGORY_TO_TYPE.get(category, "validation"),
        "fail_message_en":   description_en or name_en,
        "fail_message_ar":   description_ar or name_ar,
        "recommendation_en": rec_en,
        "recommendation_ar": rec_ar,
        "blocks_approval":   blocks,
    }


# ═══════════════════════════════════════════════════════════════════════════
# A. Sales Invoice (SI-001..012)
# ═══════════════════════════════════════════════════════════════════════════
SALES_INVOICE_RULES = [
    _r("SI-001", "sales_invoice", "Sales invoice number is required",
       "رقم فاتورة البيع مطلوب", "high", "completeness",
       "Reject invoices missing a number; require resubmission.",
       "ارفض الفواتير بلا رقم؛ اطلب إعادة الإصدار.", blocks=True),
    _r("SI-002", "sales_invoice", "Invoice date is required and valid",
       "تاريخ الفاتورة مطلوب وصحيح", "high", "date_validation",
       "Reject invoices missing a date or with an unparseable date.",
       "ارفض الفواتير بلا تاريخ أو بتاريخ غير صحيح.", blocks=True),
    _r("SI-003", "sales_invoice", "No unjustified future-dated invoices",
       "لا يسمح بتاريخ مستقبلي غير مبرر", "medium", "date_validation",
       "Investigate any future-dated invoices before posting.",
       "حقّق في أي فاتورة بتاريخ مستقبلي قبل الترحيل."),
    _r("SI-004", "sales_invoice", "Customer is required",
       "العميل مطلوب", "high", "completeness",
       "Block any invoice with no customer — basic control failure.",
       "احجب أي فاتورة بدون عميل — فشل ضبط أساسي.", blocks=True),
    _r("SI-005", "sales_invoice", "Customer TRN required when taxable",
       "الرقم الضريبي للعميل مطلوب إذا كان خاضعاً للضريبة", "high", "vat_validation",
       "Add a valid customer TRN before issuing a tax invoice.",
       "أضِف رقم ضريبي صالح للعميل قبل إصدار الفاتورة الضريبية."),
    _r("SI-006", "sales_invoice", "Total equals lines + VAT",
       "إجمالي الفاتورة = مجموع البنود + الضريبة", "critical", "amount_validation",
       "Recompute the line-item total and reconcile.",
       "أعد احتساب مجموع البنود وسَوِّ الفروق.", blocks=True),
    _r("SI-007", "sales_invoice", "VAT calculated correctly",
       "VAT محسوبة بشكل صحيح", "critical", "vat_validation",
       "Recalculate VAT at the correct rate before approval.",
       "أعد احتساب الضريبة بالنسبة الصحيحة قبل الاعتماد.", blocks=True),
    _r("SI-008", "sales_invoice", "No duplicate invoice number per customer",
       "لا توجد فاتورة بيع مكررة بنفس الرقم والعميل", "critical", "duplicate_detection",
       "Block duplicate invoices to prevent double-billing.",
       "احجب الفواتير المكرّرة لمنع الفوترة المزدوجة.", blocks=True),
    _r("SI-009", "sales_invoice", "No duplicate by amount + date + customer",
       "لا توجد فاتورة بيع مكررة بنفس المبلغ والتاريخ والعميل", "high", "duplicate_detection",
       "Investigate likely duplicates before approval.",
       "حقّق في الفواتير المرجّح أنها مكرّرة قبل الاعتماد."),
    _r("SI-010", "sales_invoice", "Collection status reasonable",
       "تحقق من حالة التحصيل", "medium", "matching",
       "Reconcile against the customer statement / collections.",
       "سَوِّ مع كشف العميل أو سجلات التحصيل."),
    _r("SI-011", "sales_invoice", "Currency is supported",
       "العملة مدعومة", "medium", "completeness",
       "Add the currency to the supported list or correct the document.",
       "أضِف العملة لقائمة المعتمدة أو صحّح المستند."),
    _r("SI-012", "sales_invoice", "Amount unusual vs. customer history",
       "كشف مبلغ غير طبيعي مقارنة بسجل العميل", "medium", "anomaly_detection",
       "Compare against customer history before approving.",
       "قارن بسجل العميل قبل الاعتماد."),
]

# ═══════════════════════════════════════════════════════════════════════════
# B. Purchase Invoice (PI-001..015)
# ═══════════════════════════════════════════════════════════════════════════
PURCHASE_INVOICE_RULES = [
    _r("PI-001", "purchase_invoice", "Purchase invoice number is required",
       "رقم فاتورة الشراء مطلوب", "high", "completeness",
       "Reject invoices missing a number.",
       "ارفض الفواتير بلا رقم.", blocks=True),
    _r("PI-002", "purchase_invoice", "Invoice date is required and valid",
       "تاريخ الفاتورة مطلوب وصحيح", "high", "date_validation",
       "Reject invoices without a valid date.",
       "ارفض الفواتير بلا تاريخ صحيح.", blocks=True),
    _r("PI-003", "purchase_invoice", "Supplier is required",
       "المورد مطلوب", "high", "completeness",
       "Block invoices without a vendor — control failure.",
       "احجب الفواتير بلا مورد — فشل ضبط.", blocks=True),
    _r("PI-004", "purchase_invoice", "Supplier TRN required",
       "الرقم الضريبي للمورد مطلوب", "high", "vat_validation",
       "Withhold VAT recovery until a valid TRN is provided.",
       "أوقف استرداد الضريبة حتى يقدّم المورد رقماً ضريبياً صالحاً."),
    _r("PI-005", "purchase_invoice", "Total = lines + VAT",
       "الإجمالي = البنود + الضريبة", "critical", "amount_validation",
       "Recompute the total and reconcile.",
       "أعد احتساب الإجمالي وسَوِّ الفروق.", blocks=True),
    _r("PI-006", "purchase_invoice", "VAT calculated correctly",
       "حساب الضريبة صحيح", "critical", "vat_validation",
       "Recalculate VAT before approval.",
       "أعد احتساب الضريبة قبل الاعتماد.", blocks=True),
    _r("PI-007", "purchase_invoice", "Duplicate supplier invoice number",
       "فاتورة مكرّرة بنفس الرقم والمورد", "critical", "duplicate_detection",
       "Block until duplicate is reconciled.",
       "احجب حتى تتم تسوية التكرار.", blocks=True),
    _r("PI-008", "purchase_invoice", "Duplicate by amount + date + supplier",
       "فاتورة مكرّرة بنفس المبلغ والتاريخ والمورد", "high", "duplicate_detection",
       "Investigate likely duplicates before approval.",
       "حقّق في التكرار المحتمل قبل الاعتماد."),
    _r("PI-009", "purchase_invoice", "Linked to a Purchase Order",
       "الفاتورة مرتبطة بأمر شراء", "high", "matching",
       "Match against the originating PO before payment.",
       "طابق مع أمر الشراء الأصلي قبل الدفع."),
    _r("PI-010", "purchase_invoice", "Invoice amount ≤ PO amount",
       "مبلغ الفاتورة لا يتجاوز أمر الشراء", "high", "matching",
       "Hold payment and review the PO variance.",
       "احجب الدفع وراجع فروق أمر الشراء."),
    _r("PI-011", "purchase_invoice", "Linked to GRN when goods received",
       "الفاتورة مرتبطة بـ GRN عند وجود بضائع مستلمة", "high", "matching",
       "Match the GRN before approval to confirm receipt.",
       "طابق مع GRN قبل الاعتماد لتأكيد الاستلام."),
    _r("PI-012", "purchase_invoice", "Approval required before payment",
       "لا يتم الدفع بدون موافقة", "high", "approval_control",
       "Route to the responsible approver before payment.",
       "وجّه إلى المعتمد المسؤول قبل الدفع."),
    _r("PI-013", "purchase_invoice", "No double payment for same invoice",
       "لا يتم الدفع مرتين لنفس الفاتورة", "critical", "duplicate_detection",
       "Match against existing payments before release.",
       "طابق مع المدفوعات القائمة قبل الإفراج.", blocks=True),
    _r("PI-014", "purchase_invoice", "High-value new vendor needs review",
       "مورد جديد عالي القيمة يحتاج مراجعة", "high", "vendor_customer_risk",
       "Onboard the vendor through procurement before processing.",
       "أدرج المورد عبر المشتريات قبل المعالجة."),
    _r("PI-015", "purchase_invoice", "Amount unusual vs. supplier history",
       "مبلغ غير طبيعي مقارنة بسجل المورد", "medium", "anomaly_detection",
       "Compare against vendor history before approving.",
       "قارن بسجل المورد قبل الاعتماد."),
]

# ═══════════════════════════════════════════════════════════════════════════
# C. Purchase Order (PO-001..012)  [extends existing PO-001..010]
# ═══════════════════════════════════════════════════════════════════════════
PURCHASE_ORDER_RULES = [
    _r("PO-001", "purchase_order", "PO number is required",
       "رقم أمر الشراء مطلوب", "high", "completeness",
       "Reject POs missing a number.", "ارفض أوامر الشراء بلا رقم.", blocks=True),
    _r("PO-002", "purchase_order", "Vendor is required",
       "المورد مطلوب", "high", "completeness",
       "Block POs without a vendor.", "احجب أوامر الشراء بلا مورد.", blocks=True),
    _r("PO-003", "purchase_order", "PO date is required",
       "تاريخ أمر الشراء مطلوب", "high", "date_validation",
       "Reject POs without a date.", "ارفض أوامر الشراء بلا تاريخ."),
    _r("PO-004", "purchase_order", "PO must contain line items",
       "أمر الشراء يجب أن يحتوي على بنود", "high", "completeness",
       "Reject empty POs.", "ارفض أوامر الشراء الفارغة."),
    _r("PO-005", "purchase_order", "Quantities and prices > 0",
       "الكميات والأسعار أكبر من صفر", "high", "amount_validation",
       "Investigate non-positive quantities or prices.",
       "حقّق في الكميات أو الأسعار غير الموجبة."),
    _r("PO-006", "purchase_order", "Approval required by amount tier",
       "أمر الشراء يحتاج اعتماداً حسب القيمة", "high", "approval_control",
       "Route POs to the appropriate approver tier.",
       "وجّه أوامر الشراء حسب درجة الاعتماد المناسبة."),
    _r("PO-007", "purchase_order", "Within approved budget",
       "ضمن الميزانية المعتمدة", "high", "approval_control",
       "Escalate to budget owner for over-budget approval.",
       "صعّد إلى مالك الميزانية لاعتماد التجاوز."),
    _r("PO-008", "purchase_order", "No duplicate POs",
       "لا توجد أوامر شراء مكررة", "critical", "duplicate_detection",
       "Investigate duplicate POs before issuance.",
       "حقّق في أوامر الشراء المكرّرة قبل الإصدار.", blocks=True),
    _r("PO-009", "purchase_order", "No invoicing on closed PO",
       "لا يسمح بإصدار فاتورة على PO مغلق", "high", "matching",
       "Reopen the PO before invoicing or reject the invoice.",
       "أعد فتح أمر الشراء قبل الفوترة أو ارفض الفاتورة."),
    _r("PO-010", "purchase_order", "Received qty ≤ ordered qty",
       "الكمية المستلمة لا تتجاوز الكمية المطلوبة", "high", "matching",
       "Reconcile the GRN with the PO line quantity.",
       "سَوِّ كميات GRN مع بنود أمر الشراء."),
    _r("PO-011", "purchase_order", "Vendor must be approved",
       "المورد معتمد", "high", "vendor_customer_risk",
       "Onboard the vendor before placing POs.",
       "أدرج المورد قبل إصدار أوامر الشراء."),
    _r("PO-012", "purchase_order", "Unusual price change",
       "تغيير سعر غير طبيعي", "medium", "anomaly_detection",
       "Verify the price change is supported by an updated contract.",
       "تحقّق أن تغيير السعر مدعوم بعقد محدّث."),
]

# ═══════════════════════════════════════════════════════════════════════════
# D. Sales Order (SO-001..010)
# ═══════════════════════════════════════════════════════════════════════════
SALES_ORDER_RULES = [
    _r("SO-001", "sales_order", "SO number is required",
       "رقم أمر البيع مطلوب", "high", "completeness",
       "Reject SOs missing a number.", "ارفض أوامر البيع بلا رقم.", blocks=True),
    _r("SO-002", "sales_order", "Customer is required",
       "العميل مطلوب", "high", "completeness",
       "Block SOs without a customer.", "احجب أوامر البيع بلا عميل.", blocks=True),
    _r("SO-003", "sales_order", "SO date is required",
       "تاريخ أمر البيع مطلوب", "high", "date_validation",
       "Reject SOs without a date.", "ارفض أوامر البيع بلا تاريخ."),
    _r("SO-004", "sales_order", "SO must contain line items",
       "أمر البيع يجب أن يحتوي على بنود", "high", "completeness",
       "Reject empty SOs.", "ارفض أوامر البيع الفارغة."),
    _r("SO-005", "sales_order", "Quantities and prices valid",
       "الكميات والأسعار صحيحة", "high", "amount_validation",
       "Investigate invalid line values.", "حقّق في قيم البنود غير الصحيحة."),
    _r("SO-006", "sales_order", "No duplicate SOs",
       "لا توجد أوامر بيع مكررة", "high", "duplicate_detection",
       "Investigate duplicates before issuance.", "حقّق في التكرار قبل الإصدار."),
    _r("SO-007", "sales_order", "Customer credit limit respected",
       "تحقق من حد ائتمان العميل", "high", "vendor_customer_risk",
       "Block SO if customer exceeds credit limit.",
       "احجب أمر البيع عند تجاوز حد الائتمان."),
    _r("SO-008", "sales_order", "No invoicing if credit limit exceeded",
       "لا يتم إصدار فاتورة إذا تجاوز العميل حد الائتمان", "high", "approval_control",
       "Escalate to credit control before invoicing.",
       "صعّد لإدارة الائتمان قبل الفوترة."),
    _r("SO-009", "sales_order", "Products / services availability",
       "تحقق من توفر المنتجات أو الخدمة", "medium", "completeness",
       "Confirm inventory / capacity before commitment.",
       "تأكّد من المخزون / السعة قبل الالتزام."),
    _r("SO-010", "sales_order", "Unusual discount detected",
       "كشف خصم غير عادي", "medium", "anomaly_detection",
       "Require manager approval for outlier discounts.",
       "اشترِط موافقة المدير على الخصومات الشاذة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# E. Quotation (QT-001..010)
# ═══════════════════════════════════════════════════════════════════════════
QUOTATION_RULES = [
    _r("QT-001", "quotation", "Quotation number is required",
       "رقم عرض السعر مطلوب", "high", "completeness",
       "Reject quotations without a number.", "ارفض العروض بلا رقم.", blocks=True),
    _r("QT-002", "quotation", "Customer or supplier is required",
       "العميل أو المورد مطلوب", "high", "completeness",
       "Block quotations without a counter-party.",
       "احجب العروض بلا طرف مقابل.", blocks=True),
    _r("QT-003", "quotation", "Quotation date is required",
       "تاريخ العرض مطلوب", "high", "date_validation",
       "Reject quotations without a date.", "ارفض العروض بلا تاريخ."),
    _r("QT-004", "quotation", "Expiry date is required",
       "تاريخ انتهاء العرض مطلوب", "high", "date_validation",
       "Add an explicit expiry date to every quotation.",
       "أضِف تاريخ انتهاء صريحاً لكل عرض."),
    _r("QT-005", "quotation", "Expired quotation can't create an order",
       "العرض المنتهي لا يستخدم لإنشاء طلب", "high", "policy_compliance",
       "Reject orders linked to expired quotations.",
       "ارفض الطلبات المرتبطة بعروض منتهية.", blocks=True),
    _r("QT-006", "quotation", "Lines and prices required",
       "البنود والأسعار مطلوبة", "high", "completeness",
       "Reject quotations missing line items.", "ارفض العروض بلا بنود."),
    _r("QT-007", "quotation", "Discount within allowed limit",
       "الخصم لا يتجاوز الحد المسموح", "high", "policy_compliance",
       "Escalate over-limit discounts for approval.",
       "صعّد الخصومات المتجاوزة للحد للاعتماد."),
    _r("QT-008", "quotation", "Currency is required",
       "العملة مطلوبة", "medium", "completeness",
       "Specify a valid currency on every quotation.",
       "حدّد عملة صالحة لكل عرض."),
    _r("QT-009", "quotation", "No duplicate quotations",
       "لا توجد عروض أسعار مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before issuance.", "حقّق في التكرار قبل الإصدار."),
    _r("QT-010", "quotation", "Approval required for high discount",
       "تحقق من الموافقة إذا كان الخصم عالياً", "high", "approval_control",
       "Route high-discount quotations to senior approvers.",
       "وجّه العروض ذات الخصم العالي للمعتمدين الكبار."),
]

# ═══════════════════════════════════════════════════════════════════════════
# F. Proforma Invoice (PF-001..010)
# ═══════════════════════════════════════════════════════════════════════════
PROFORMA_INVOICE_RULES = [
    _r("PF-001", "proforma_invoice", "Proforma invoice number required",
       "رقم الفاتورة المبدئية مطلوب", "high", "completeness",
       "Reject proformas without a number.", "ارفض الفواتير المبدئية بلا رقم.", blocks=True),
    _r("PF-002", "proforma_invoice", "Customer is required",
       "العميل مطلوب", "high", "completeness",
       "Block proformas without a customer.",
       "احجب الفواتير المبدئية بلا عميل.", blocks=True),
    _r("PF-003", "proforma_invoice", "Date is required",
       "التاريخ مطلوب", "high", "date_validation",
       "Reject proformas without a date.", "ارفض الفواتير المبدئية بلا تاريخ."),
    _r("PF-004", "proforma_invoice", "Validity / expiry date is required",
       "تاريخ الصلاحية مطلوب", "high", "date_validation",
       "Add an explicit validity period.", "أضِف فترة صلاحية صريحة."),
    _r("PF-005", "proforma_invoice", "Not recorded as actual revenue",
       "لا يتم تسجيلها كإيراد فعلي", "high", "policy_compliance",
       "Ensure proformas are excluded from revenue posting.",
       "تأكّد من استبعاد الفواتير المبدئية من ترحيل الإيرادات."),
    _r("PF-006", "proforma_invoice", "Marked clearly as Proforma",
       "يجب تمييزها بوضوح كـ Proforma", "medium", "policy_compliance",
       "Add an explicit 'Proforma' watermark or label.",
       "أضِف علامة مائية أو تسمية 'Proforma' صريحة."),
    _r("PF-007", "proforma_invoice", "Total and VAT correctly computed",
       "الإجمالي والضريبة محسوبان بشكل صحيح", "high", "amount_validation",
       "Recompute the totals before sharing with the customer.",
       "أعد احتساب الإجماليات قبل مشاركتها مع العميل."),
    _r("PF-008", "proforma_invoice", "No final payment without final invoice",
       "لا يتم الدفع النهائي بدون فاتورة نهائية", "high", "policy_compliance",
       "Block payment until a tax invoice is issued.",
       "احجب الدفع حتى تصدر فاتورة ضريبية نهائية.", blocks=True),
    _r("PF-009", "proforma_invoice", "No duplicate proformas",
       "لا توجد Proforma مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before sharing.",
       "حقّق في التكرار قبل المشاركة."),
    _r("PF-010", "proforma_invoice", "Conversion to real invoice tracked",
       "تحقق من تحويلها لفاتورة بيع إذا تمت العملية", "medium", "matching",
       "Reconcile against issued tax invoices.",
       "سَوِّ مع الفواتير الضريبية الصادرة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# G. GRN — Goods Receipt Note (GRN-001..010)
# ═══════════════════════════════════════════════════════════════════════════
GRN_RULES = [
    _r("GRN-001", "grn", "GRN number is required",
       "رقم سند الاستلام مطلوب", "high", "completeness",
       "Reject GRNs without a number.", "ارفض سندات الاستلام بلا رقم.", blocks=True),
    _r("GRN-002", "grn", "Linked to a Purchase Order",
       "يجب أن يرتبط بأمر شراء", "high", "matching",
       "Match the GRN to the originating PO.",
       "طابق سند الاستلام مع أمر الشراء الأصلي."),
    _r("GRN-003", "grn", "Receipt date is required",
       "تاريخ الاستلام مطلوب", "high", "date_validation",
       "Reject GRNs without a receipt date.",
       "ارفض سندات الاستلام بلا تاريخ."),
    _r("GRN-004", "grn", "Supplier is required",
       "المورد مطلوب", "high", "completeness",
       "Block GRNs without a supplier.",
       "احجب سندات الاستلام بلا مورد.", blocks=True),
    _r("GRN-005", "grn", "Received line items required",
       "البنود المستلمة مطلوبة", "high", "completeness",
       "Reject GRNs without line items.",
       "ارفض سندات الاستلام بلا بنود."),
    _r("GRN-006", "grn", "Received qty ≤ ordered qty",
       "الكمية المستلمة لا تتجاوز الكمية المطلوبة في PO", "high", "matching",
       "Reconcile excess quantities with the PO.",
       "سَوِّ الكميات الزائدة مع أمر الشراء."),
    _r("GRN-007", "grn", "Quantity variance vs. PO",
       "كشف فرق الكمية بين PO وGRN", "medium", "matching",
       "Investigate quantity variances before invoice approval.",
       "حقّق في فروق الكميات قبل اعتماد الفاتورة."),
    _r("GRN-008", "grn", "No duplicate GRNs",
       "لا توجد GRN مكررة", "high", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("GRN-009", "grn", "Invoice rejected without GRN when required",
       "لا يتم قبول فاتورة بدون GRN إذا كان مطلوباً", "high", "matching",
       "Hold invoice until a matching GRN is recorded.",
       "علّق الفاتورة حتى يُسجّل GRN مطابق.", blocks=True),
    _r("GRN-010", "grn", "Inspection / acceptance status valid",
       "تحقق من حالة الفحص أو القبول", "medium", "policy_compliance",
       "Confirm acceptance status before invoice processing.",
       "تأكّد من حالة القبول قبل معالجة الفاتورة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# H. Payment Voucher (PV-001..012)
# ═══════════════════════════════════════════════════════════════════════════
PAYMENT_VOUCHER_RULES = [
    _r("PV-001", "payment_voucher", "Payment voucher number is required",
       "رقم سند الدفع مطلوب", "high", "completeness",
       "Reject vouchers without a number.", "ارفض السندات بلا رقم.", blocks=True),
    _r("PV-002", "payment_voucher", "Payee is required",
       "المستفيد مطلوب", "high", "completeness",
       "Block payments without a beneficiary.",
       "احجب المدفوعات بلا مستفيد.", blocks=True),
    _r("PV-003", "payment_voucher", "Amount > 0",
       "المبلغ أكبر من صفر", "critical", "amount_validation",
       "Block zero/negative payments.",
       "احجب المدفوعات الصفرية أو السالبة.", blocks=True),
    _r("PV-004", "payment_voucher", "Payment method is required",
       "طريقة الدفع مطلوبة", "high", "completeness",
       "Specify cash / bank / cheque before posting.",
       "حدّد نقدي / بنكي / شيك قبل الترحيل."),
    _r("PV-005", "payment_voucher", "Payment date is required",
       "تاريخ الدفع مطلوب", "high", "date_validation",
       "Reject vouchers without a payment date.",
       "ارفض السندات بلا تاريخ دفع."),
    _r("PV-006", "payment_voucher", "Linked to invoice / clear reason",
       "يجب أن يرتبط الدفع بفاتورة أو سبب واضح", "high", "matching",
       "Reference an invoice or written justification.",
       "اربط بفاتورة أو مبرّر مكتوب."),
    _r("PV-007", "payment_voucher", "No double payment for same invoice",
       "لا يتم الدفع مرتين لنفس الفاتورة", "critical", "duplicate_detection",
       "Match against existing payments before release.",
       "طابق مع المدفوعات القائمة قبل الإفراج.", blocks=True),
    _r("PV-008", "payment_voucher", "Approved before release",
       "الدفع معتمد", "critical", "approval_control",
       "Route vouchers through the standard approval flow.",
       "وجّه السندات عبر مسار الاعتماد القياسي.", blocks=True),
    _r("PV-009", "payment_voucher", "Cash payment over threshold approved",
       "الدفع النقدي فوق حد معين يحتاج موافقة", "high", "approval_control",
       "Escalate large cash payments to the CFO / FD.",
       "صعّد المدفوعات النقدية الكبيرة للمدير المالي."),
    _r("PV-010", "payment_voucher", "Matches bank statement",
       "تحقق من مطابقة الدفع مع كشف البنك", "high", "bank_reconciliation",
       "Reconcile each voucher against the bank statement.",
       "سَوِّ كل سند مع كشف البنك."),
    _r("PV-011", "payment_voucher", "High-value new payee detected",
       "كشف مستفيد جديد عالي القيمة", "high", "vendor_customer_risk",
       "Onboard new payees through KYC before payment.",
       "أدرج المستفيدين الجدد عبر KYC قبل الدفع."),
    _r("PV-012", "payment_voucher", "Split payments to bypass approval",
       "كشف دفعات مقسمة لتجنب الموافقة", "critical", "anomaly_detection",
       "Investigate suspected structuring before payment.",
       "حقّق في الـ structuring المشتبه به قبل الدفع.", blocks=True),
]

# ═══════════════════════════════════════════════════════════════════════════
# I. Receipt Voucher (RV-001..010)
# ═══════════════════════════════════════════════════════════════════════════
RECEIPT_VOUCHER_RULES = [
    _r("RV-001", "receipt_voucher", "Receipt number is required",
       "رقم سند القبض مطلوب", "high", "completeness",
       "Reject vouchers without a number.", "ارفض السندات بلا رقم.", blocks=True),
    _r("RV-002", "receipt_voucher", "Payer / customer is required",
       "الدافع أو العميل مطلوب", "high", "completeness",
       "Block receipts without a payer.",
       "احجب السندات بلا دافع.", blocks=True),
    _r("RV-003", "receipt_voucher", "Amount > 0",
       "المبلغ أكبر من صفر", "critical", "amount_validation",
       "Block zero/negative receipts.",
       "احجب المقبوضات الصفرية أو السالبة.", blocks=True),
    _r("RV-004", "receipt_voucher", "Receipt method required",
       "طريقة القبض مطلوبة", "high", "completeness",
       "Specify cash / bank / cheque.",
       "حدّد نقدي / بنكي / شيك."),
    _r("RV-005", "receipt_voucher", "Receipt date is required",
       "تاريخ القبض مطلوب", "high", "date_validation",
       "Reject vouchers without a date.",
       "ارفض السندات بلا تاريخ."),
    _r("RV-006", "receipt_voucher", "Linked to invoice / clear reason",
       "يجب أن يرتبط القبض بفاتورة أو سبب واضح", "high", "matching",
       "Reference an invoice or written justification.",
       "اربط بفاتورة أو مبرّر مكتوب."),
    _r("RV-007", "receipt_voucher", "No duplicate receipts",
       "لا توجد سندات قبض مكررة", "high", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("RV-008", "receipt_voucher", "Matches bank statement",
       "تحقق من مطابقة القبض مع كشف البنك", "high", "bank_reconciliation",
       "Reconcile each voucher against the bank statement.",
       "سَوِّ كل سند مع كشف البنك."),
    _r("RV-009", "receipt_voucher", "Variance vs. invoice needs review",
       "فرق التحصيل عن الفاتورة يحتاج مراجعة", "medium", "matching",
       "Investigate variances before crediting the customer.",
       "حقّق في الفروق قبل قيد الإيداع للعميل."),
    _r("RV-010", "receipt_voucher", "Unjustified collections detected",
       "كشف تحصيل غير مبرر", "medium", "anomaly_detection",
       "Investigate collections without an underlying invoice.",
       "حقّق في التحصيلات بدون فواتير أصلية."),
]

# ═══════════════════════════════════════════════════════════════════════════
# J. Cash Voucher (CV-001..010)
# ═══════════════════════════════════════════════════════════════════════════
CASH_VOUCHER_RULES = [
    _r("CV-001", "cash_voucher", "Cash voucher number is required",
       "رقم السند النقدي مطلوب", "high", "completeness",
       "Reject vouchers without a number.", "ارفض السندات بلا رقم.", blocks=True),
    _r("CV-002", "cash_voucher", "Movement type required (in / out)",
       "نوع الحركة مطلوب: قبض أو صرف", "high", "completeness",
       "Specify whether the voucher is a receipt or a payment.",
       "حدّد إن كان السند قبض أم صرف."),
    _r("CV-003", "cash_voucher", "Amount > 0",
       "المبلغ أكبر من صفر", "critical", "amount_validation",
       "Block zero/negative cash movements.",
       "احجب الحركات النقدية الصفرية أو السالبة.", blocks=True),
    _r("CV-004", "cash_voucher", "Date is required",
       "التاريخ مطلوب", "high", "date_validation",
       "Reject vouchers without a date.",
       "ارفض السندات بلا تاريخ."),
    _r("CV-005", "cash_voucher", "Reason is required",
       "سبب الحركة مطلوب", "high", "completeness",
       "Add a documented reason before posting.",
       "أضِف سبباً موثّقاً قبل الترحيل."),
    _r("CV-006", "cash_voucher", "Receipt / attachment required",
       "المرفق أو الإيصال مطلوب", "high", "completeness",
       "Attach the supporting receipt before approval.",
       "أرفق الإيصال الداعم قبل الاعتماد."),
    _r("CV-007", "cash_voucher", "Over-threshold cash needs approval",
       "الحركة النقدية فوق الحد تحتاج موافقة", "high", "approval_control",
       "Escalate large cash movements to senior management.",
       "صعّد الحركات النقدية الكبيرة للإدارة العليا."),
    _r("CV-008", "cash_voucher", "No duplicate cash movements",
       "لا توجد حركة نقدية مكررة", "high", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("CV-009", "cash_voucher", "Unusual cash expense detected",
       "كشف مصروف نقدي غير عادي", "medium", "anomaly_detection",
       "Compare against historical norms before approving.",
       "قارن بالمعدّلات السابقة قبل الاعتماد."),
    _r("CV-010", "cash_voucher", "Cashbox balance sane after movement",
       "تحقق من رصيد الصندوق بعد الحركة", "medium", "amount_validation",
       "Reconcile the cashbox balance after each posting.",
       "سَوِّ رصيد الصندوق بعد كل ترحيل."),
]

# ═══════════════════════════════════════════════════════════════════════════
# K. Bank Statement (BS-001..015) — augments existing BNK-* codes
# ═══════════════════════════════════════════════════════════════════════════
BANK_STATEMENT_RULES = [
    _r("BS-001", "bank_statement", "Bank account number required",
       "رقم الحساب البنكي مطلوب", "high", "completeness",
       "Add a valid bank account number.",
       "أضِف رقم حساب بنكي صالح."),
    _r("BS-002", "bank_statement", "Bank name required",
       "اسم البنك مطلوب", "medium", "completeness",
       "Specify the bank explicitly.", "حدّد اسم البنك صراحةً."),
    _r("BS-003", "bank_statement", "Transaction date required",
       "تاريخ العملية مطلوب", "high", "date_validation",
       "Reject statements with missing transaction dates.",
       "ارفض كشوف الحسابات بلا تاريخ معاملات."),
    _r("BS-004", "bank_statement", "Description / reference required",
       "الوصف أو المرجع مطلوب", "medium", "completeness",
       "Require a clear description for each line.",
       "اشترِط وصفاً واضحاً لكل بند."),
    _r("BS-005", "bank_statement", "Either debit or credit must be present",
       "يجب وجود مدين أو دائن وليس كلاهما فارغ", "high", "amount_validation",
       "Reject lines with no amount on either side.",
       "ارفض البنود التي لا تحمل مبلغاً مدين أو دائن."),
    _r("BS-006", "bank_statement", "Closing balance reconciles",
       "الرصيد الختامي منطقي", "critical", "bank_reconciliation",
       "Reconcile closing balance against the running totals.",
       "سَوِّ الرصيد الختامي مع المجاميع التراكمية.", blocks=True),
    _r("BS-007", "bank_statement", "Duplicate transactions detected",
       "كشف عمليات مكررة", "critical", "duplicate_detection",
       "Investigate duplicates — possible double-posting.",
       "حقّق في التكرار — احتمال تسجيل مزدوج.", blocks=True),
    _r("BS-008", "bank_statement", "Outflow without invoice detected",
       "كشف دفعات بدون فاتورة", "high", "matching",
       "Match outflows against invoices or vouchers.",
       "طابق المخارج مع فواتير أو سندات."),
    _r("BS-009", "bank_statement", "Inflow without invoice detected",
       "كشف قبض بدون فاتورة", "high", "matching",
       "Match inflows against invoices or vouchers.",
       "طابق المداخل مع فواتير أو سندات."),
    _r("BS-010", "bank_statement", "Outflows match Payment Vouchers",
       "مطابقة الدفعات مع Payment Voucher", "high", "matching",
       "Reconcile each outflow with its payment voucher.",
       "سَوِّ كل مخرج مع سند دفع."),
    _r("BS-011", "bank_statement", "Inflows match Receipt Vouchers",
       "مطابقة المقبوضات مع Receipt Voucher", "high", "matching",
       "Reconcile each inflow with its receipt voucher.",
       "سَوِّ كل مدخل مع سند قبض."),
    _r("BS-012", "bank_statement", "Unusual transactions detected",
       "كشف معاملات غير طبيعية", "medium", "anomaly_detection",
       "Sample unusual transactions for review.",
       "أخذ عيّنة من المعاملات غير الطبيعية للمراجعة."),
    _r("BS-013", "bank_statement", "Off-hours / holiday transactions",
       "كشف معاملات خارج ساعات العمل أو في العطلات", "medium", "anomaly_detection",
       "Investigate off-hours transactions before posting.",
       "حقّق في المعاملات خارج ساعات العمل قبل الترحيل."),
    _r("BS-014", "bank_statement", "Unusual balance shift detected",
       "كشف تغير غير طبيعي في الرصيد", "high", "anomaly_detection",
       "Investigate large unexplained balance changes.",
       "حقّق في التغيّرات الكبيرة غير المبرّرة في الرصيد."),
    _r("BS-015", "bank_statement", "Benford-law analysis on amounts",
       "تحليل بنفورد على المبالغ", "medium", "benford_analysis",
       "Sample non-conforming transactions for fraud review.",
       "أخذ عيّنة من المعاملات غير المطابقة للقانون لمراجعة الاحتيال."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L. Journal Entry (JE-001..014)
# ═══════════════════════════════════════════════════════════════════════════
JOURNAL_ENTRY_RULES = [
    _r("JE-001", "journal_entry", "Entry number required",
       "رقم القيد مطلوب", "high", "completeness",
       "Reject entries without a number.", "ارفض القيود بلا رقم.", blocks=True),
    _r("JE-002", "journal_entry", "Entry date required",
       "تاريخ القيد مطلوب", "high", "date_validation",
       "Reject entries without a date.", "ارفض القيود بلا تاريخ."),
    _r("JE-003", "journal_entry", "Description required",
       "الوصف مطلوب", "medium", "completeness",
       "Require a clear narrative for every entry.",
       "اشترِط وصفاً واضحاً لكل قيد."),
    _r("JE-004", "journal_entry", "At least two lines",
       "القيد يحتوي على سطرين على الأقل", "critical", "completeness",
       "Reject single-line entries — accounting error.",
       "ارفض القيود ذات السطر الواحد — خطأ محاسبي.", blocks=True),
    _r("JE-005", "journal_entry", "Each line has a valid account",
       "كل سطر يحتوي على حساب صحيح", "critical", "completeness",
       "Reject entries with missing or invalid accounts.",
       "ارفض القيود بحسابات مفقودة أو غير صحيحة.", blocks=True),
    _r("JE-006", "journal_entry", "Total debit equals total credit",
       "إجمالي المدين = إجمالي الدائن", "critical", "amount_validation",
       "Reject unbalanced entries.",
       "ارفض القيود غير المتوازنة.", blocks=True),
    _r("JE-007", "journal_entry", "No unbalanced entries posted",
       "لا يسمح بقيد غير متوازن", "critical", "amount_validation",
       "Block posting of unbalanced entries.",
       "احجب ترحيل القيود غير المتوازنة.", blocks=True),
    _r("JE-008", "journal_entry", "No duplicate entries",
       "لا توجد قيود مكررة", "high", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("JE-009", "journal_entry", "No unjustified future-dated entries",
       "لا يسمح بتاريخ مستقبلي غير مبرر", "medium", "date_validation",
       "Investigate future-dated entries before posting.",
       "حقّق في القيود ذات التاريخ المستقبلي قبل الترحيل."),
    _r("JE-010", "journal_entry", "Accounts exist in Chart of Accounts",
       "الحسابات موجودة في دليل الحسابات", "high", "completeness",
       "Reject entries on undefined accounts.",
       "ارفض القيود على حسابات غير مُعرَّفة."),
    _r("JE-011", "journal_entry", "Unusual amount detected",
       "قيد بمبلغ غير طبيعي", "medium", "anomaly_detection",
       "Investigate outlier amounts before posting.",
       "حقّق في المبالغ الشاذة قبل الترحيل."),
    _r("JE-012", "journal_entry", "High-risk manual entry",
       "قيد يدوي عالي المخاطر", "high", "anomaly_detection",
       "Require senior approval for manual entries above threshold.",
       "اشترِط اعتماداً أعلى للقيود اليدوية فوق الحد."),
    _r("JE-013", "journal_entry", "Period-end entry detected",
       "قيد في نهاية الفترة المالية", "medium", "anomaly_detection",
       "Sample period-end entries for cutoff review.",
       "أخذ عيّنة من قيود نهاية الفترة لمراجعة القطع الزمني."),
    _r("JE-014", "journal_entry", "Attachment required when policy says so",
       "قيد بدون مرفق إذا كان مطلوباً", "medium", "policy_compliance",
       "Attach supporting documents per policy.",
       "أرفق المستندات الداعمة وفق السياسة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# M. General Ledger (GL-001..012)
# ═══════════════════════════════════════════════════════════════════════════
GENERAL_LEDGER_RULES = [
    _r("GL-001", "general_ledger", "Account is required",
       "الحساب مطلوب", "high", "completeness",
       "Reject GL rows without an account.",
       "ارفض صفوف الأستاذ بلا حساب."),
    _r("GL-002", "general_ledger", "Opening balance required",
       "الرصيد الافتتاحي مطلوب", "high", "completeness",
       "Reject GL rows without an opening balance.",
       "ارفض صفوف الأستاذ بلا رصيد افتتاحي."),
    _r("GL-003", "general_ledger", "Movements required",
       "الحركات مطلوبة", "medium", "completeness",
       "Reject empty ledgers.",
       "ارفض دفاتر الأستاذ الفارغة."),
    _r("GL-004", "general_ledger", "Closing = Opening + Debit − Credit",
       "الرصيد الختامي = الافتتاحي + المدين − الدائن", "critical", "amount_validation",
       "Recompute closing balances and reconcile.",
       "أعد احتساب الأرصدة الختامية وسَوِّ الفروق.", blocks=True),
    _r("GL-005", "general_ledger", "Each movement linked to a JE",
       "كل حركة مرتبطة بقيد يومية", "high", "matching",
       "Match movements to journal entries.",
       "طابق الحركات مع قيود اليومية."),
    _r("GL-006", "general_ledger", "Movements without JE detected",
       "كشف حركات بدون قيد يومية", "high", "matching",
       "Investigate orphan movements before relying on the GL.",
       "حقّق في الحركات اليتيمة قبل الاعتماد على الأستاذ."),
    _r("GL-007", "general_ledger", "Accounts with abnormal balances",
       "حسابات ذات أرصدة غير طبيعية", "high", "anomaly_detection",
       "Investigate accounts with unexpected sign or magnitude.",
       "حقّق في الحسابات بأرصدة غير متوقّعة."),
    _r("GL-008", "general_ledger", "Roll-forward variances",
       "كشف فروقات Rollforward", "high", "amount_validation",
       "Reconcile period-on-period roll-forward.",
       "سَوِّ التراكب من فترة لفترة."),
    _r("GL-009", "general_ledger", "Duplicate movements",
       "كشف حركات مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("GL-010", "general_ledger", "Inactive accounts with activity",
       "حسابات خاملة عليها حركة", "medium", "anomaly_detection",
       "Investigate dormant accounts with sudden activity.",
       "حقّق في الحسابات الخاملة التي لها حركة مفاجئة."),
    _r("GL-011", "general_ledger", "Abnormal account-level changes",
       "تغيرات غير طبيعية في الحساب", "medium", "anomaly_detection",
       "Compare period balances against expectations.",
       "قارن أرصدة الفترة مع التوقّعات."),
    _r("GL-012", "general_ledger", "Benford-law analysis on movements",
       "تحليل بنفورد على الحركات", "medium", "benford_analysis",
       "Sample non-conforming entries for review.",
       "أخذ عيّنة من القيود غير المطابقة للمراجعة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# N. Ledger (account-level, LDG-001..010)
# ═══════════════════════════════════════════════════════════════════════════
LEDGER_RULES = [
    _r("LDG-001", "ledger", "Account number required",
       "رقم الحساب مطلوب", "high", "completeness",
       "Reject ledger rows without an account number.",
       "ارفض صفوف الأستاذ بلا رقم حساب."),
    _r("LDG-002", "ledger", "Account name required",
       "اسم الحساب مطلوب", "medium", "completeness",
       "Reject ledger rows without an account name.",
       "ارفض صفوف الأستاذ بلا اسم حساب."),
    _r("LDG-003", "ledger", "Opening balance required",
       "الرصيد الافتتاحي مطلوب", "high", "completeness",
       "Reject ledgers without an opening balance.",
       "ارفض الدفاتر بلا رصيد افتتاحي."),
    _r("LDG-004", "ledger", "Movements have date / description / amount",
       "الحركات تحتوي على تاريخ ووصف ومبلغ", "high", "completeness",
       "Reject incomplete movement rows.",
       "ارفض صفوف الحركات الناقصة."),
    _r("LDG-005", "ledger", "Closing balance correct",
       "الرصيد الختامي صحيح", "critical", "amount_validation",
       "Recompute closing balances and reconcile.",
       "أعد احتساب الأرصدة الختامية وسَوِّ الفروق.", blocks=True),
    _r("LDG-006", "ledger", "Movement without reference detected",
       "كشف حركة بدون مرجع", "medium", "audit_trail",
       "Add a reference (invoice / voucher / JE) to each movement.",
       "أضِف مرجعاً (فاتورة / سند / قيد) لكل حركة."),
    _r("LDG-007", "ledger", "Duplicate movement detected",
       "حركة مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before posting.",
       "حقّق في التكرار قبل الترحيل."),
    _r("LDG-008", "ledger", "Unusual movement detected",
       "حركة غير طبيعية", "medium", "anomaly_detection",
       "Compare against historical norms.",
       "قارن بالمعدّلات السابقة."),
    _r("LDG-009", "ledger", "Movements linked to JEs",
       "تحقق من ارتباط الحركات بقيود يومية", "high", "matching",
       "Match each movement to its journal entry.",
       "طابق كل حركة مع قيد يومية."),
    _r("LDG-010", "ledger", "No unjustified negative balances",
       "لا توجد أرصدة سالبة غير مبررة", "high", "amount_validation",
       "Investigate accounts with unexpected negative balances.",
       "حقّق في الحسابات بأرصدة سالبة غير متوقّعة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# O. Contract (CTR-001..013)
# ═══════════════════════════════════════════════════════════════════════════
CONTRACT_RULES = [
    _r("CTR-001", "contract", "Contract number required",
       "رقم العقد مطلوب", "high", "completeness",
       "Reject contracts without a number.", "ارفض العقود بلا رقم.", blocks=True),
    _r("CTR-002", "contract", "Contract parties required",
       "أطراف العقد مطلوبة", "high", "completeness",
       "Block contracts without identified parties.",
       "احجب العقود بلا أطراف محدّدة.", blocks=True),
    _r("CTR-003", "contract", "Start date required",
       "تاريخ البداية مطلوب", "high", "date_validation",
       "Reject contracts without a start date.",
       "ارفض العقود بلا تاريخ بداية."),
    _r("CTR-004", "contract", "End date required",
       "تاريخ النهاية مطلوب", "high", "date_validation",
       "Reject contracts without an end date.",
       "ارفض العقود بلا تاريخ نهاية."),
    _r("CTR-005", "contract", "Contract value required",
       "قيمة العقد مطلوبة", "high", "completeness",
       "Reject contracts without a stated value.",
       "ارفض العقود بلا قيمة محدّدة."),
    _r("CTR-006", "contract", "Contract is signed",
       "العقد موقع", "critical", "policy_compliance",
       "Block reliance on unsigned contracts.",
       "احجب الاعتماد على العقود غير الموقّعة.", blocks=True),
    _r("CTR-007", "contract", "Expired contract not used for new invoices",
       "العقد المنتهي لا يرتبط بفواتير جديدة", "high", "contract_compliance",
       "Reject invoices linked to expired contracts.",
       "ارفض الفواتير المرتبطة بعقود منتهية."),
    _r("CTR-008", "contract", "Invoice date within contract period",
       "الفاتورة داخل مدة العقد", "high", "contract_compliance",
       "Reject out-of-period invoicing.",
       "ارفض الفوترة خارج المدة."),
    _r("CTR-009", "contract", "Total invoiced ≤ contract value",
       "إجمالي الفواتير لا يتجاوز قيمة العقد", "high", "contract_compliance",
       "Block over-invoicing against the contract cap.",
       "احجب تجاوز الفوترة لسقف العقد."),
    _r("CTR-010", "contract", "Payment terms clearly stated",
       "شروط الدفع واضحة", "medium", "contract_compliance",
       "Add explicit payment terms before signing.",
       "أضِف شروط دفع صريحة قبل التوقيع."),
    _r("CTR-011", "contract", "Contract attachment present",
       "العقد مرفق", "medium", "audit_trail",
       "Attach the signed contract document.",
       "أرفق نسخة العقد الموقّعة."),
    _r("CTR-012", "contract", "Value modification approved",
       "تعديل قيمة العقد معتمد", "high", "approval_control",
       "Route value changes through formal approval.",
       "وجّه تعديلات القيمة عبر اعتماد رسمي."),
    _r("CTR-013", "contract", "Counterparty matches invoice",
       "الطرف المقابل يطابق الفاتورة", "high", "matching",
       "Reject invoices from parties not on the contract.",
       "ارفض الفواتير من أطراف ليست في العقد."),
]

# ═══════════════════════════════════════════════════════════════════════════
# P. Payroll (PR-001..012)  [augments existing PAY-* codes]
# ═══════════════════════════════════════════════════════════════════════════
PAYROLL_RULES = [
    _r("PR-001", "payroll", "Payroll number required",
       "رقم مسير الرواتب مطلوب", "high", "completeness",
       "Reject sheets without a number.", "ارفض المسير بلا رقم.", blocks=True),
    _r("PR-002", "payroll", "Period required",
       "فترة الرواتب مطلوبة", "high", "completeness",
       "Specify the explicit payroll period.",
       "حدّد فترة كشف الرواتب بوضوح."),
    _r("PR-003", "payroll", "Each employee has an employee ID",
       "كل موظف له رقم وظيفي", "high", "completeness",
       "Add employee IDs for traceability.",
       "أضِف أرقام الموظفين للتتبّع."),
    _r("PR-004", "payroll", "Basic salary required",
       "الراتب الأساسي مطلوب", "high", "completeness",
       "Reject rows without a basic salary.",
       "ارفض الصفوف بلا راتب أساسي."),
    _r("PR-005", "payroll", "Net = entitlements − deductions",
       "صافي الراتب = المستحقات − الخصومات", "critical", "amount_validation",
       "Recalculate net pay and reconcile.",
       "أعد احتساب صافي الراتب وسَوِّ الفروق.", blocks=True),
    _r("PR-006", "payroll", "No duplicate employees in same period",
       "لا يوجد موظف مكرر في نفس المسير", "critical", "duplicate_detection",
       "Investigate duplicate employee rows.",
       "حقّق في تكرار صفوف الموظفين.", blocks=True),
    _r("PR-007", "payroll", "No salaries for terminated / resigned",
       "لا يصرف راتب لموظف موقوف أو مستقيل", "critical", "policy_compliance",
       "Cross-check against HR master records.",
       "تحقّق مع سجلات الموارد البشرية الرئيسية.", blocks=True),
    _r("PR-008", "payroll", "Unusual salary change detected",
       "تغير غير طبيعي في الراتب", "high", "anomaly_detection",
       "Document business justification before approval.",
       "وثّق المبرّر التجاري قبل الاعتماد."),
    _r("PR-009", "payroll", "Unusual allowances detected",
       "بدلات غير عادية", "medium", "anomaly_detection",
       "Compare against historical norms before approving.",
       "قارن بالمعدّلات السابقة قبل الاعتماد."),
    _r("PR-010", "payroll", "Unusual deductions detected",
       "خصومات غير عادية", "medium", "anomaly_detection",
       "Investigate unexplained deductions.",
       "حقّق في الخصومات غير المبرّرة."),
    _r("PR-011", "payroll", "Total matches accounting entry",
       "إجمالي الرواتب يطابق القيد المحاسبي", "high", "matching",
       "Reconcile total payroll against the GL.",
       "سَوِّ إجمالي الرواتب مع الأستاذ العام."),
    _r("PR-012", "payroll", "Bank disbursement matches net pay",
       "الدفع البنكي يطابق صافي الرواتب", "high", "bank_reconciliation",
       "Reconcile the bank batch against net pay.",
       "سَوِّ دفعة البنك مع صافي الرواتب."),
]

# ═══════════════════════════════════════════════════════════════════════════
# Q. Expense Report (ER-001..013)
# ═══════════════════════════════════════════════════════════════════════════
EXPENSE_REPORT_RULES = [
    _r("ER-001", "expense_report", "Expense report number required",
       "رقم تقرير المصروف مطلوب", "high", "completeness",
       "Reject reports without a number.", "ارفض التقارير بلا رقم.", blocks=True),
    _r("ER-002", "expense_report", "Employee required",
       "الموظف مطلوب", "high", "completeness",
       "Block reports without an employee.",
       "احجب التقارير بلا موظف.", blocks=True),
    _r("ER-003", "expense_report", "Department required",
       "القسم مطلوب", "medium", "completeness",
       "Specify the cost-centre / department.",
       "حدّد مركز التكلفة / القسم."),
    _r("ER-004", "expense_report", "Expense type required",
       "نوع المصروف مطلوب", "medium", "completeness",
       "Categorise each line by type.",
       "صنّف كل بند حسب النوع."),
    _r("ER-005", "expense_report", "Date required",
       "التاريخ مطلوب", "high", "date_validation",
       "Reject expenses without a valid date.",
       "ارفض المصروفات بلا تاريخ صحيح."),
    _r("ER-006", "expense_report", "Amount > 0",
       "المبلغ أكبر من صفر", "critical", "amount_validation",
       "Block zero/negative expenses.",
       "احجب المصروفات الصفرية أو السالبة.", blocks=True),
    _r("ER-007", "expense_report", "Receipt / attachment required",
       "الإيصال أو المرفق مطلوب", "high", "completeness",
       "Attach the supporting receipt before approval.",
       "أرفق الإيصال الداعم قبل الاعتماد."),
    _r("ER-008", "expense_report", "Within company policy",
       "ضمن سياسة الشركة", "high", "policy_compliance",
       "Escalate over-policy items to the responsible manager.",
       "صعّد البنود المتجاوزة للسياسة للمدير المسؤول."),
    _r("ER-009", "expense_report", "Over-threshold needs approval",
       "فوق الحد يحتاج موافقة", "high", "approval_control",
       "Route over-threshold expenses for approval.",
       "وجّه المصروفات فوق الحد للاعتماد."),
    _r("ER-010", "expense_report", "Duplicate expense detected",
       "مصروف مكرر", "high", "duplicate_detection",
       "Investigate duplicates before reimbursement.",
       "حقّق في التكرار قبل التعويض."),
    _r("ER-011", "expense_report", "Off-hours / holiday expense",
       "مصروف في عطلة أو خارج وقت العمل", "medium", "anomaly_detection",
       "Investigate expenses outside business hours.",
       "حقّق في المصروفات خارج ساعات العمل."),
    _r("ER-012", "expense_report", "Expense not tied to clear work",
       "مصروف غير مرتبط بعمل واضح", "medium", "policy_compliance",
       "Require business justification for ambiguous expenses.",
       "اشترِط مبرّراً تجارياً للمصروفات الغامضة."),
    _r("ER-013", "expense_report", "Unusual amount per employee / dept",
       "مبالغ غير طبيعية للموظف أو القسم", "medium", "anomaly_detection",
       "Compare against historical norms.",
       "قارن بالمعدّلات السابقة."),
]

# ═══════════════════════════════════════════════════════════════════════════
# R. Tax / VAT Document (VATD-001..012) — separate from invoice VAT-* codes
# ═══════════════════════════════════════════════════════════════════════════
TAX_VAT_DOCUMENT_RULES = [
    _r("VATD-001", "tax_vat_document", "TRN required",
       "الرقم الضريبي مطلوب", "critical", "vat_validation",
       "Validate TRN against ZATCA records.",
       "تحقّق من الرقم الضريبي عبر سجلات ZATCA.", blocks=True),
    _r("VATD-002", "tax_vat_document", "VAT period required",
       "الفترة الضريبية مطلوبة", "high", "completeness",
       "Specify the explicit VAT return period.",
       "حدّد فترة الإقرار الضريبي بوضوح."),
    _r("VATD-003", "tax_vat_document", "Standard-rated sales total required",
       "إجمالي المبيعات الخاضعة للضريبة مطلوب", "high", "completeness",
       "Provide explicit standard-rated sales total.",
       "قدّم إجمالي المبيعات الخاضعة للضريبة."),
    _r("VATD-004", "tax_vat_document", "Standard-rated purchases total required",
       "إجمالي المشتريات الخاضعة للضريبة مطلوب", "high", "completeness",
       "Provide explicit standard-rated purchases total.",
       "قدّم إجمالي المشتريات الخاضعة للضريبة."),
    _r("VATD-005", "tax_vat_document", "Output VAT computed correctly",
       "VAT Output محسوبة بشكل صحيح", "critical", "vat_validation",
       "Recalculate output VAT = sales × rate.",
       "أعد احتساب ضريبة المخرجات = المبيعات × النسبة.", blocks=True),
    _r("VATD-006", "tax_vat_document", "Input VAT computed correctly",
       "VAT Input محسوبة بشكل صحيح", "critical", "vat_validation",
       "Recalculate input VAT = purchases × rate.",
       "أعد احتساب ضريبة المدخلات = المشتريات × النسبة.", blocks=True),
    _r("VATD-007", "tax_vat_document", "Net VAT = Output − Input",
       "صافي الضريبة = Output − Input", "critical", "amount_validation",
       "Recompute net VAT and reconcile.",
       "أعد احتساب صافي الضريبة وسَوِّ الفروق.", blocks=True),
    _r("VATD-008", "tax_vat_document", "Invoices without TRN detected",
       "كشف فواتير بدون رقم ضريبي", "high", "vat_validation",
       "Investigate non-compliant invoices in the period.",
       "حقّق في الفواتير غير الممتثلة في الفترة."),
    _r("VATD-009", "tax_vat_document", "Invoices with incorrect VAT detected",
       "كشف فواتير بضريبة غير صحيحة", "high", "vat_validation",
       "Correct invoices with mis-calculated VAT.",
       "صحّح الفواتير ذات الضريبة المحتسبة بشكل خاطئ."),
    _r("VATD-010", "tax_vat_document", "Invoices outside the VAT period",
       "فواتير خارج الفترة الضريبية", "high", "matching",
       "Reclassify invoices to the correct period.",
       "أعد تصنيف الفواتير للفترة الصحيحة."),
    _r("VATD-011", "tax_vat_document", "No VAT double-counting",
       "لا ازدواج في احتساب الضريبة", "critical", "duplicate_detection",
       "Investigate double-counted VAT entries.",
       "حقّق في ضريبة المخرجات / المدخلات المزدوجة.", blocks=True),
    _r("VATD-012", "tax_vat_document", "VAT report matches sales/purchase invoices",
       "تقرير VAT يطابق فواتير البيع والشراء", "high", "matching",
       "Reconcile VAT return totals against invoice ledger.",
       "سَوِّ إجماليات الإقرار الضريبي مع دفتر الفواتير."),
]

# ═══════════════════════════════════════════════════════════════════════════
# S. Supplier Statement (SS-001..012)
# ═══════════════════════════════════════════════════════════════════════════
SUPPLIER_STATEMENT_RULES = [
    _r("SS-001", "supplier_statement", "Supplier name required",
       "اسم المورد مطلوب", "high", "completeness",
       "Reject statements without a supplier.",
       "ارفض الكشوف بلا مورد."),
    _r("SS-002", "supplier_statement", "Supplier ID / TRN required",
       "رقم المورد أو الرقم الضريبي مطلوب", "high", "completeness",
       "Add the vendor reference for matching.",
       "أضِف مرجع المورد للمطابقة."),
    _r("SS-003", "supplier_statement", "Period required",
       "الفترة مطلوبة", "high", "completeness",
       "Specify the explicit statement period.",
       "حدّد فترة الكشف بوضوح."),
    _r("SS-004", "supplier_statement", "Opening balance required",
       "الرصيد الافتتاحي مطلوب", "high", "completeness",
       "Add the opening balance.",
       "أضِف الرصيد الافتتاحي."),
    _r("SS-005", "supplier_statement", "Movements required",
       "الحركات مطلوبة", "medium", "completeness",
       "Reject empty supplier statements.",
       "ارفض كشوف الموردين الفارغة."),
    _r("SS-006", "supplier_statement", "Closing balance correct",
       "الرصيد الختامي صحيح", "critical", "amount_validation",
       "Recompute closing balance and reconcile.",
       "أعد احتساب الرصيد الختامي وسَوِّ الفروق.", blocks=True),
    _r("SS-007", "supplier_statement", "Supplier invoices match system",
       "مطابقة فواتير المورد مع النظام", "high", "matching",
       "Reconcile invoices against system records.",
       "سَوِّ الفواتير مع سجلات النظام."),
    _r("SS-008", "supplier_statement", "Payments match Payment Vouchers",
       "مطابقة المدفوعات مع Payment Vouchers", "high", "matching",
       "Reconcile payments against vouchers.",
       "سَوِّ المدفوعات مع السندات."),
    _r("SS-009", "supplier_statement", "Invoices on statement missing in system",
       "فواتير في كشف المورد غير موجودة في النظام", "high", "matching",
       "Add missing invoices or reject the statement.",
       "أضِف الفواتير المفقودة أو ارفض الكشف."),
    _r("SS-010", "supplier_statement", "Payments in system missing on statement",
       "مدفوعات في النظام غير موجودة في كشف المورد", "high", "matching",
       "Investigate unrecorded payments with the supplier.",
       "حقّق مع المورد في المدفوعات غير المسجّلة."),
    _r("SS-011", "supplier_statement", "Balance variance detected",
       "كشف فروقات الرصيد", "high", "amount_validation",
       "Reconcile any balance variance before period close.",
       "سَوِّ أي فرق رصيد قبل إقفال الفترة."),
    _r("SS-012", "supplier_statement", "Duplicate transactions detected",
       "كشف معاملات مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before reconciliation.",
       "حقّق في التكرار قبل التسوية."),
]

# ═══════════════════════════════════════════════════════════════════════════
# T. Customer Statement (CS-001..012)
# ═══════════════════════════════════════════════════════════════════════════
CUSTOMER_STATEMENT_RULES = [
    _r("CS-001", "customer_statement", "Customer name required",
       "اسم العميل مطلوب", "high", "completeness",
       "Reject statements without a customer.",
       "ارفض الكشوف بلا عميل."),
    _r("CS-002", "customer_statement", "Customer ID / TRN required",
       "رقم العميل أو الرقم الضريبي مطلوب", "high", "completeness",
       "Add the customer reference for matching.",
       "أضِف مرجع العميل للمطابقة."),
    _r("CS-003", "customer_statement", "Period required",
       "الفترة مطلوبة", "high", "completeness",
       "Specify the explicit statement period.",
       "حدّد فترة الكشف بوضوح."),
    _r("CS-004", "customer_statement", "Opening balance required",
       "الرصيد الافتتاحي مطلوب", "high", "completeness",
       "Add the opening balance.",
       "أضِف الرصيد الافتتاحي."),
    _r("CS-005", "customer_statement", "Movements required",
       "الحركات مطلوبة", "medium", "completeness",
       "Reject empty customer statements.",
       "ارفض كشوف العملاء الفارغة."),
    _r("CS-006", "customer_statement", "Closing balance correct",
       "الرصيد الختامي صحيح", "critical", "amount_validation",
       "Recompute closing balance and reconcile.",
       "أعد احتساب الرصيد الختامي وسَوِّ الفروق.", blocks=True),
    _r("CS-007", "customer_statement", "Customer invoices match system",
       "مطابقة فواتير العميل مع النظام", "high", "matching",
       "Reconcile invoices against system records.",
       "سَوِّ الفواتير مع سجلات النظام."),
    _r("CS-008", "customer_statement", "Receipts match Receipt Vouchers",
       "مطابقة المقبوضات مع Receipt Vouchers", "high", "matching",
       "Reconcile receipts against vouchers.",
       "سَوِّ المقبوضات مع السندات."),
    _r("CS-009", "customer_statement", "Invoices on statement missing in system",
       "فواتير في كشف العميل غير موجودة في النظام", "high", "matching",
       "Add missing invoices or reject the statement.",
       "أضِف الفواتير المفقودة أو ارفض الكشف."),
    _r("CS-010", "customer_statement", "Receipts in system missing on statement",
       "مقبوضات في النظام غير موجودة في كشف العميل", "high", "matching",
       "Investigate unrecorded receipts with the customer.",
       "حقّق مع العميل في المقبوضات غير المسجّلة."),
    _r("CS-011", "customer_statement", "Balance variance detected",
       "كشف فروقات الرصيد", "high", "amount_validation",
       "Reconcile any balance variance before period close.",
       "سَوِّ أي فرق رصيد قبل إقفال الفترة."),
    _r("CS-012", "customer_statement", "Duplicate transactions detected",
       "كشف معاملات مكررة", "medium", "duplicate_detection",
       "Investigate duplicates before reconciliation.",
       "حقّق في التكرار قبل التسوية."),
]

# ─── Aggregate ──────────────────────────────────────────────────────────────
ALL_RULES: list[dict] = (
    SALES_INVOICE_RULES
    + PURCHASE_INVOICE_RULES
    + PURCHASE_ORDER_RULES
    + SALES_ORDER_RULES
    + QUOTATION_RULES
    + PROFORMA_INVOICE_RULES
    + GRN_RULES
    + PAYMENT_VOUCHER_RULES
    + RECEIPT_VOUCHER_RULES
    + CASH_VOUCHER_RULES
    + BANK_STATEMENT_RULES
    + JOURNAL_ENTRY_RULES
    + GENERAL_LEDGER_RULES
    + LEDGER_RULES
    + CONTRACT_RULES
    + PAYROLL_RULES
    + EXPENSE_REPORT_RULES
    + TAX_VAT_DOCUMENT_RULES
    + SUPPLIER_STATEMENT_RULES
    + CUSTOMER_STATEMENT_RULES
)


def stats() -> dict:
    """Quick summary helpful for the seed command's stdout report."""
    by_type: dict[str, int] = {}
    by_severity: dict[str, int] = {}
    by_category: dict[str, int] = {}
    for r in ALL_RULES:
        by_type[r["document_type"]] = by_type.get(r["document_type"], 0) + 1
        by_severity[r["severity"]] = by_severity.get(r["severity"], 0) + 1
        by_category[r["category"]] = by_category.get(r["category"], 0) + 1
    return {
        "total":        len(ALL_RULES),
        "by_type":      by_type,
        "by_severity":  by_severity,
        "by_category":  by_category,
    }
