# Generated by Django 4.2.30 on 2026-05-12 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        ('documents', '0010_bulkuploadjob_bulkuploaditem_and_more'),
        ('rule_engine', '0007_alter_auditrunv2metadata_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('business', 'Business'), ('professional', 'Professional')], help_text='Stable identifier used by code and APIs.', max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('invoice_limit', models.PositiveIntegerField(help_text='Invoices auditable per billing period.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_free', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False, help_text='Trial plans can be activated only once per organisation.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='billing_pla_is_acti_015c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('payment_failed', 'Payment Failed')], default='pending_payment', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_limit', models.PositiveIntegerField(default=0)),
                ('used_invoices', models.PositiveIntegerField(default=0)),
                ('reserved_invoices', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('payment_transaction', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='authentication.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('reserve', 'Reserve'), ('consume', 'Consume'), ('release', 'Release'), ('refund', 'Refund')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_ledger_entries', to='rule_engine.auditrun')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_ledger_entries', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_ledger_entries', to='authentication.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='billing.organizationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'action'], name='billing_usa_organiz_c455d3_idx'), models.Index(fields=['subscription', 'action'], name='billing_usa_subscri_c389c1_idx'), models.Index(fields=['document', 'action'], name='billing_usa_documen_53428a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['organization', 'status'], name='billing_org_organiz_4c38fc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'ends_at'], name='billing_org_status_8a24dd_idx'),
        ),
    ]
