# Generated by Django 4.2.30 on 2026-05-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_paymentproviderconfig'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_funded', to='payments.paymenttransaction'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trialing'])), fields=('organization',), name='billing_one_usable_sub_per_org'),
        ),
    ]
