# Generated by Django 4.2.30 on 2026-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_organizationsubscription_payment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='user_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_custom_quote',
            field=models.BooleanField(default=False, help_text='Priced by negotiation. Not purchasable through self-service checkout.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Seats (active users in the organisation). NULL = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='invoice_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='invoice_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Invoices auditable per billing period. NULL = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NULL when is_custom_quote is set — the plan has no list price.', max_digits=10, null=True),
        ),
    ]
