# Generated by Django 4.2.30 on 2026-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_organizationsubscription_user_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('basic', 'Basic'), ('business', 'Business'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('accounting_partner', 'Accounting Partner'), ('accounting_professional', 'Accounting Professional'), ('accounting_enterprise', 'Accounting Enterprise')], help_text='Stable identifier used by code and APIs.', max_length=32, unique=True),
        ),
    ]
