# Generated by Django 4.2.30 on 2026-08-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='currency_at_purchase',
            field=models.CharField(blank=True, default='', help_text='Currency frozen alongside price_at_purchase.', max_length=8),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price, frozen at creation. NULL = pre-snapshot row.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='price_is_negotiated',
            field=models.BooleanField(default=False),
        ),
    ]
