# Generated by Django 4.2.30 on 2026-08-01 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_price_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('billing_type', models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time'), ('custom_quote', 'Custom quote')], max_length=16)),
                ('dimension', models.CharField(choices=[('users', 'Users'), ('invoices', 'Invoices'), ('none', 'No quota')], default='none', max_length=16)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('is_price_from', models.BooleanField(default=False, help_text='Spec says "starts from": a floor for negotiation, not a payable price.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_type', models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time'), ('custom_quote', 'Custom quote')], max_length=16)),
                ('dimension', models.CharField(choices=[('users', 'Users'), ('invoices', 'Invoices'), ('none', 'No quota')], max_length=16)),
                ('quantity_at_purchase', models.PositiveIntegerField(blank=True, null=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_at_purchase', models.CharField(default='SAR', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('used_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='billing.addon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='billing.organizationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'is_active'], name='billing_sub_subscri_6ce3d2_idx'), models.Index(fields=['subscription', 'dimension', 'is_active'], name='billing_sub_subscri_115478_idx')],
            },
        ),
    ]
