# Generated by Django 4.2.30 on 2026-08-01 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('invoice_credit_rollover', models.CharField(choices=[('carry_over', 'Carry unused credit over'), ('expire', 'Expire unused credit at reset')], default='carry_over', help_text='What happens to unused one-time invoice credit at cycle reset.', max_length=16)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billing policy',
                'verbose_name_plural': 'billing policy',
            },
        ),
    ]
