# Generated by Django 5.2.17 on 2026-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_billing_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsubscription",
            name="backup_frequency_snapshot",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="feature_tiers_snapshot",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="retention_months_snapshot",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="backup_frequency",
            field=models.CharField(
                default="none",
                help_text="Operational backup cadence included by this plan (none, weekly, daily).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="feature_tiers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Central package capabilities and tier values exposed by billing services.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="retention_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Document retention period. NULL = retention negotiated separately.",
                null=True,
            ),
        ),
    ]
