# Generated by Django 4.2.30 on 2026-05-04 10:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        ('documents', '0008_journalentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0011_working_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.CharField(db_index=True, help_text='e.g. PR-2026-00123 — auto-generated.', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('cost_center', models.CharField(blank=True, max_length=64)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Preferred vendor; not binding until the PO is issued.', max_length=200)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed (PO issued)')], db_index=True, default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='authentication.organization')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Filled when the PR is converted to a PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='documents.purchaseorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_prs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('account_code', models.CharField(blank=True, help_text='GL account this line will debit when the matching invoice posts.', max_length=24)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequisition')),
            ],
            options={
                'db_table': 'procurement_pr_lines',
                'ordering': ['requisition', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='PRApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to next tier')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('threshold_role', models.CharField(blank=True, help_text='The approval-tier role at which this decision was made.', max_length=32)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_decisions', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.purchaserequisition')),
            ],
            options={
                'db_table': 'procurement_pr_approvals',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatched'), ('partial', 'Partial match'), ('pending', 'Pending documents')], db_index=True, default='pending', max_length=12)),
                ('differences', models.JSONField(blank=True, default=list, help_text='List of {field, po, grn, invoice, message} dicts.')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threeway_matches', to='documents.goodsreceiptnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threeway_matches', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threeway_matches', to='authentication.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threeway_matches', to='documents.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_threeway_matches',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='procurement_organiz_e918be_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'status'], name='procurement_organiz_0ccfd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('organization', 'pr_number'), name='procurement_pr_unique_number_per_org'),
        ),
    ]
