# Generated by Django 5.2.17 on 2026-08-19 13:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0011_chain_partition_and_fork_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_prefix", models.CharField(db_index=True, max_length=12)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("monthly_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used_this_month", models.PositiveIntegerField(default=0)),
                (
                    "usage_period",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_api_keys",
            },
        ),
        migrations.CreateModel(
            name="APIUsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="api_access.organizationapikey",
                    ),
                ),
            ],
            options={
                "db_table": "api_usage_events",
            },
        ),
        migrations.AddConstraint(
            model_name="organizationapikey",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_org_api_key_name"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusageevent",
            index=models.Index(
                fields=["api_key", "created_at"], name="api_usage_e_api_key_cc63fc_idx"
            ),
        ),
    ]
