# Generated by Django 4.2.29 on 2026-03-19 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_verified_at_emailotpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('stored', 'Stored'), ('failed', 'Failed'), ('archived', 'Archived')], default='uploaded', max_length=20)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_files', to='authentication.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audit_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit File',
                'verbose_name_plural': 'Audit Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO'), ('azure', 'Azure Blob')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Provider',
                'verbose_name_plural': 'Storage Providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('allowed_mime_types', models.JSONField(default=list)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('require_signed_urls', models.BooleanField(default=False)),
                ('require_encryption', models.BooleanField(default=False)),
                ('antivirus_scan_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_policy', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Storage Policy',
                'verbose_name_plural': 'Storage Policies',
            },
        ),
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('endpoint_url', models.URLField(blank=True)),
                ('base_path', models.CharField(blank=True, help_text='For LOCAL: filesystem path. For S3/MinIO: key prefix', max_length=500)),
                ('access_key_encrypted', models.TextField(blank=True)),
                ('secret_key_encrypted', models.TextField(blank=True)),
                ('use_ssl', models.BooleanField(default=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global config', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_configs', to='authentication.organization')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='storage_management.storageprovider')),
            ],
            options={
                'verbose_name': 'Storage Config',
                'verbose_name_plural': 'Storage Configs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationStoragePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_for', to='storage_management.storageprovider')),
                ('backup_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_for', to='storage_management.storageprovider')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_policy', to='authentication.organization')),
                ('primary_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for', to='storage_management.storageprovider')),
                ('temp_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_for', to='storage_management.storageprovider')),
            ],
            options={
                'verbose_name': 'Organization Storage Policy',
                'verbose_name_plural': 'Organization Storage Policies',
            },
        ),
        migrations.CreateModel(
            name='FileStorageMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField()),
                ('storage_bucket', models.CharField(blank=True, max_length=255)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_mappings', to='storage_management.auditfile')),
                ('storage_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage_management.storageprovider')),
            ],
            options={
                'verbose_name': 'File Storage Mapping',
                'verbose_name_plural': 'File Storage Mappings',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='StorageActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('provider_created', 'Provider Created'), ('provider_updated', 'Provider Updated'), ('provider_deleted', 'Provider Deleted'), ('config_updated', 'Config Updated'), ('connection_tested', 'Connection Tested'), ('file_uploaded', 'File Uploaded'), ('file_deleted', 'File Deleted'), ('policy_updated', 'Policy Updated'), ('file_moved', 'File Moved')], max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Activity Log',
                'verbose_name_plural': 'Storage Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='storage_man_organiz_71ca84_idx'), models.Index(fields=['action'], name='storage_man_action_8d0c9e_idx'), models.Index(fields=['user'], name='storage_man_user_id_afba02_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['organization', 'created_at'], name='storage_man_organiz_8c67c7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['checksum'], name='storage_man_checksu_8d7769_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['status'], name='storage_man_status_485dba_idx'),
        ),
    ]
