# Generated by Django 5.2.17 on 2026-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_management", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="filestoragemapping",
            constraint=models.UniqueConstraint(
                fields=("file", "version_number"),
                name="uniq_storage_mapping_version_per_file",
            ),
        ),
    ]
