# Generated by Django 4.2.29 on 2026-03-20 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_verified_at_emailotpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('file_uploaded', 'File Uploaded'), ('file_archived', 'File Archived'), ('file_restored', 'File Restored'), ('file_deleted', 'File Deleted'), ('file_moved', 'File Moved'), ('file_downloaded', 'File Downloaded'), ('folder_created', 'Folder Created'), ('folder_renamed', 'Folder Renamed'), ('folder_deleted', 'Folder Deleted'), ('audit_started', 'Audit Started'), ('audit_completed', 'Audit Completed'), ('audit_failed', 'Audit Failed'), ('audit_canceled', 'Audit Canceled'), ('report_generated', 'Report Generated'), ('report_downloaded', 'Report Downloaded'), ('storage_changed', 'Storage Changed'), ('policy_changed', 'Policy Changed'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='authentication.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='activity_lo_organiz_d78627_idx'), models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_fb0911_idx'), models.Index(fields=['action'], name='activity_lo_action_de9b3e_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__456622_idx')],
            },
        ),
    ]
