# Generated by Django 4.2.30 on 2026-05-13 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='chain_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EvidenceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_kind', models.CharField(help_text='"document" | "working_paper" | "report" | ...', max_length=32)),
                ('evidence_id', models.CharField(db_index=True, max_length=64)),
                ('evidence_sha', models.CharField(blank=True, help_text='Content hash at moment of access.', max_length=64)),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('emailed', 'Emailed'), ('exported', 'Exported'), ('hash_verify', 'Hash re-verified'), ('attached', 'Attached to case'), ('detached', 'Detached from case')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('case_id', models.CharField(blank=True, db_index=True, help_text='AuditCase id at the moment of access.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('chain_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_accesses', to='authentication.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='evidence_ac_organiz_b6c246_idx'), models.Index(fields=['evidence_kind', 'evidence_id'], name='evidence_ac_evidenc_6a769f_idx'), models.Index(fields=['user', 'created_at'], name='evidence_ac_user_id_9b0d6a_idx')],
            },
        ),
    ]
