# Generated by Django 4.2.30 on 2026-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_activitylog_chain_hash_activitylog_previous_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('file_uploaded', 'File Uploaded'), ('file_archived', 'File Archived'), ('file_restored', 'File Restored'), ('file_deleted', 'File Deleted'), ('file_moved', 'File Moved'), ('file_downloaded', 'File Downloaded'), ('folder_created', 'Folder Created'), ('folder_renamed', 'Folder Renamed'), ('folder_deleted', 'Folder Deleted'), ('audit_started', 'Audit Started'), ('audit_completed', 'Audit Completed'), ('audit_failed', 'Audit Failed'), ('audit_canceled', 'Audit Canceled'), ('report_generated', 'Report Generated'), ('report_downloaded', 'Report Downloaded'), ('storage_changed', 'Storage Changed'), ('policy_changed', 'Policy Changed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('engagement_stage_changed', 'Engagement Stage Changed'), ('finding_status_changed', 'Finding Status Changed')], max_length=30),
        ),
    ]
