# Generated by Django 4.2.30 on 2026-08-04 14:36
#
# EDITED after review of commit 8102cf1, before this ever reached production.
#
# The generated version opened with `RemoveField(chain_hash)`. Dropping that
# column destroys the only tamper-evidence every pre-existing ActivityLog row
# has, irreversibly and with no export — while AuditLog, in the same commit,
# deliberately kept its `chain_hash` as a legacy mirror. There was no reason
# for the two to differ, and the asymmetry was an oversight rather than a
# decision.
#
# `chain_hash` is therefore retained on ActivityLog exactly as on AuditLog: a
# read-only mirror of `event_hash`, written by save(). Old rows keep their
# original hash until 0005 re-chains them; new rows get the mirror.
#
# This file is edited rather than superseded by a 0005 AddField on purpose. A
# later re-add cannot recover values that this migration would already have
# dropped, and production has never applied it — so editing here is the only
# version in which the data survives at all.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_alter_activitylog_action'),
    ]

    operations = [
        # NOTE: no RemoveField. See the module docstring above.
        migrations.AddField(
            model_name='activitylog',
            name='chain_position',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text="1-based position within this org's chain"),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + ts + org)', max_length=64),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text="event_hash of the previous row in this org's chain", max_length=64),
        ),
    ]
