# Generated by Django 4.2.30 on 2026-08-04 17:23

"""Freeze the chain partition, then make a forked chain impossible.

See authentication/0011 for why the backfill must run between the AddFields
and the AddConstraint — in short, every existing row has chain_partition="" at
that moment and each organisation's chain independently starts at position 1,
so the constraint would compare ("", 1) across tenants and fail.
"""

from django.db import migrations, models


def freeze_partitions(apps, schema_editor):
    ActivityLog = apps.get_model("activity_logs", "ActivityLog")

    for organization_id in (
        ActivityLog.objects.order_by().values_list("organization_id", flat=True).distinct()
    ):
        ActivityLog.objects.filter(organization_id=organization_id).update(
            chain_partition=str(organization_id or "")
        )

    ActivityLog.objects.filter(chain_actor="", user_id__isnull=False).update(
        chain_actor=models.F("user_id")
    )
    ActivityLog.objects.filter(event_hash="").update(chain_position=None)


def unfreeze_partitions(apps, schema_editor):
    ActivityLog = apps.get_model("activity_logs", "ActivityLog")
    ActivityLog.objects.filter(chain_position__isnull=True).update(chain_position=0)
    ActivityLog.objects.update(chain_partition="", chain_actor="")


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0005_rebuild_activity_log_chains'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='chain_actor',
            field=models.CharField(blank=True, default='', help_text='user id frozen at write time; survives user deletion', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='chain_partition',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Frozen partition key (organization id) this row's chain belongs to", max_length=64),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='chain_position',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=None, help_text='1-based position within this chain; NULL until chained', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + partition)', max_length=64),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='event_hash of the previous row in this chain', max_length=64),
        ),
        # Must run before AddConstraint — see the module docstring.
        migrations.RunPython(freeze_partitions, unfreeze_partitions),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['chain_partition', 'chain_position'], name='activitylog_chain_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.UniqueConstraint(fields=('chain_partition', 'chain_position'), name='uniq_chain_position_activitylog'),
        ),
    ]
