# Generated by Django 4.2.30 on 2026-08-04 17:28

"""Move EvidenceAccess onto HashChainMixin and re-chain its rows.

This model kept a hand-rolled chain — no serialisation between appends, and
ordered by `created_at`, which ties — when ActivityLog and AuditLog were
converted. The guard test meant to catch that could not see it, because it
skipped any models.py containing the string "HashChainMixin" and this class
shares a file with ActivityLog.

Rows are re-chained rather than left alone, for the reason set out in
authentication/0010: verify_chain walks by chain_position, so un-backfilled
rows would read as a broken chain from the first record. The old `chain_hash`
values are preserved as a mirror rather than dropped.
"""

from django.db import migrations, models


GENESIS_HASH = "0" * 64
BATCH = 1000


def rechain(apps, schema_editor):
    import hashlib
    import json

    EvidenceAccess = apps.get_model("activity_logs", "EvidenceAccess")

    def _json_default(obj):
        if hasattr(obj, "isoformat"):
            return obj.isoformat()
        return str(obj)

    # .order_by() clears Meta.ordering before .distinct() — see
    # authentication/0010 for what happens without it.
    for organization_id in (
        EvidenceAccess.objects.order_by()
        .values_list("organization_id", flat=True).distinct()
    ):
        partition = str(organization_id or "")
        rows = (
            EvidenceAccess.objects
            .filter(organization_id=organization_id)
            .order_by("created_at", "pk")
            .iterator(chunk_size=BATCH)
        )

        previous_hash = GENESIS_HASH
        position = 0
        batch = []

        for row in rows:
            position += 1
            # Must match EvidenceAccess._chain_payload() exactly.
            payload = {
                "org":  partition,
                "user": str(row.user_id or ""),
                "kind": row.evidence_kind,
                "evid": row.evidence_id,
                "sha":  row.evidence_sha,
                "act":  row.action,
                "ip":   str(row.ip_address or ""),
                "ua":   row.user_agent,
                "case": row.case_id,
                "meta": row.metadata or {},
            }
            serialised = json.dumps(payload, sort_keys=True,
                                    separators=(",", ":"), default=_json_default)
            material = f"{previous_hash}|{serialised}|{partition}".encode("utf-8")
            event_hash = hashlib.sha256(material).hexdigest()

            row.chain_partition = partition
            row.chain_actor = str(row.user_id or "")
            row.previous_hash = previous_hash
            row.event_hash = event_hash
            row.chain_hash = event_hash
            row.chain_position = position
            batch.append(row)

            if len(batch) >= BATCH:
                EvidenceAccess.objects.bulk_update(batch, [
                    "chain_partition", "chain_actor", "previous_hash",
                    "event_hash", "chain_hash", "chain_position",
                ])
                batch = []

            previous_hash = event_hash

        if batch:
            EvidenceAccess.objects.bulk_update(batch, [
                "chain_partition", "chain_actor", "previous_hash",
                "event_hash", "chain_hash", "chain_position",
            ])


def unchain(apps, schema_editor):
    EvidenceAccess = apps.get_model("activity_logs", "EvidenceAccess")
    EvidenceAccess.objects.update(
        chain_partition="", chain_actor="", previous_hash="",
        event_hash="", chain_hash="", chain_position=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0006_chain_partition_and_fork_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceaccess',
            name='chain_actor',
            field=models.CharField(blank=True, default='', help_text='user id frozen at write time; survives user deletion', max_length=64),
        ),
        migrations.AddField(
            model_name='evidenceaccess',
            name='chain_partition',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Frozen partition key (organization id) this row's chain belongs to", max_length=64),
        ),
        migrations.AddField(
            model_name='evidenceaccess',
            name='chain_position',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=None, help_text='1-based position within this chain; NULL until chained', null=True),
        ),
        migrations.AddField(
            model_name='evidenceaccess',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + partition)', max_length=64),
        ),
        migrations.AlterField(
            model_name='evidenceaccess',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='event_hash of the previous row in this chain', max_length=64),
        ),
        # Must run before AddConstraint: until every row has a partition
        # and a distinct position, the constraint would reject them.
        migrations.RunPython(rechain, unchain),
        migrations.AddIndex(
            model_name='evidenceaccess',
            index=models.Index(fields=['chain_partition', 'chain_position'], name='evidenceaccess_chain_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceaccess',
            constraint=models.UniqueConstraint(fields=('chain_partition', 'chain_position'), name='uniq_chain_position_evidenceaccess'),
        ),
    ]
