# Generated by Django 4.2.30 on 2026-05-13 21:44

import core.utils.encrypted_json
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sap', 'SAP ECC / S/4HANA'), ('oracle', 'Oracle Fusion Cloud'), ('odoo', 'Odoo'), ('dynamics', 'Microsoft Dynamics 365 F&O'), ('quickbooks', 'QuickBooks Online'), ('netsuite', 'Oracle NetSuite')], max_length=16)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox'), ('mock', 'Mock')], default='sandbox', max_length=12)),
                ('base_url', models.URLField(blank=True)),
                ('credentials', core.utils.encrypted_json.EncryptedJSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_paused_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_erp_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_connections', to='authentication.organization')),
            ],
            options={
                'db_table': 'erp_connections',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ingest', 'Ingest (ERP → Tadgeeg)'), ('egress', 'Egress (Tadgeeg → ERP)')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=10)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('kinds', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='erp.erpconnection')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_erp_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_sync_runs',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('payload_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('local_model', models.CharField(blank=True, max_length=64)),
                ('local_pk', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('created', 'Created locally'), ('updated', 'Updated locally'), ('skipped', 'Skipped (no change)'), ('failed', 'Mapping failed')], default='created', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='erp.syncrun')),
            ],
            options={
                'db_table': 'erp_sync_records',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('diff_type', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('local_pk', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_diffs', to='erp.erpconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_diffs', to='authentication.organization')),
            ],
            options={
                'db_table': 'erp_reconciliation_diffs',
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['connection', 'status'], name='erp_sync_ru_connect_ca59f5_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['direction', 'status'], name='erp_sync_ru_directi_48074a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['run', 'kind'], name='erp_sync_re_run_id_0f45bf_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['external_id', 'kind'], name='erp_sync_re_externa_227507_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationdiff',
            index=models.Index(fields=['organization', 'resolved', 'severity'], name='erp_reconci_organiz_490e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='erpconnection',
            index=models.Index(fields=['organization', 'status'], name='erp_connect_organiz_cb69bc_idx'),
        ),
        migrations.AddIndex(
            model_name='erpconnection',
            index=models.Index(fields=['provider'], name='erp_connect_provide_7ac833_idx'),
        ),
        migrations.AddConstraint(
            model_name='erpconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'environment'), name='erp_one_connection_per_org_provider_env'),
        ),
    ]
