# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="invoices/%Y/%m/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("vendor_name_ar", models.CharField(blank=True, max_length=255)),
                ("vendor_vat_number", models.CharField(blank=True, max_length=20)),
                ("vendor_cr_number", models.CharField(blank=True, max_length=20)),
                ("vendor_address", models.TextField(blank=True)),
                ("vendor_phone", models.CharField(blank=True, max_length=30)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_vat_number", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("QAR", "Qatari Riyal"),
                            ("OMR", "Omani Rial"),
                            ("BHD", "Bahraini Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("line_items", models.JSONField(default=list)),
                ("has_qr_code", models.BooleanField(default=False)),
                ("qr_code_valid", models.BooleanField(default=False)),
                ("is_handwritten", models.BooleanField(default=False)),
                ("is_clear", models.BooleanField(default=True)),
                ("has_alterations", models.BooleanField(default=False)),
                ("ocr_confidence", models.FloatField(default=0.0)),
                ("language", models.CharField(default="unknown", max_length=10)),
                ("raw_text", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(default=dict)),
                ("cost_center", models.CharField(blank=True, max_length=50)),
                ("account_code", models.CharField(blank=True, max_length=50)),
                ("budget_code", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("processing", "Processing"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                ("processing_error", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceValidationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_invoice_number", models.BooleanField(default=False)),
                ("has_invoice_date", models.BooleanField(default=False)),
                ("has_vendor_name", models.BooleanField(default=False)),
                ("has_vendor_vat", models.BooleanField(default=False)),
                ("has_total_amount", models.BooleanField(default=False)),
                ("has_currency", models.BooleanField(default=False)),
                ("total_greater_zero", models.BooleanField(default=False)),
                ("no_vat_without_base", models.BooleanField(default=False)),
                ("duplicate_invoice_number", models.BooleanField(default=False)),
                ("duplicate_vendor_and_number", models.BooleanField(default=False)),
                ("duplicate_vendor_amount_date", models.BooleanField(default=False)),
                ("duplicate_file_hash", models.BooleanField(default=False)),
                ("duplicate_across_months", models.BooleanField(default=False)),
                ("vat_rate_correct", models.BooleanField(default=False)),
                ("vat_calculation_correct", models.BooleanField(default=False)),
                ("vat_subtotal_correct", models.BooleanField(default=False)),
                ("vat_number_present", models.BooleanField(default=False)),
                ("qr_code_valid", models.BooleanField(default=False)),
                ("amount_unusually_high", models.BooleanField(default=False)),
                ("new_unknown_vendor", models.BooleanField(default=False)),
                ("many_invoices_same_day", models.BooleanField(default=False)),
                ("sudden_price_change", models.BooleanField(default=False)),
                ("many_invoices_year_end", models.BooleanField(default=False)),
                ("vendor_dominates_invoices", models.BooleanField(default=False)),
                ("has_cost_center", models.BooleanField(default=False)),
                ("has_account_code", models.BooleanField(default=False)),
                ("within_budget", models.BooleanField(default=True)),
                ("no_edit_after_approve", models.BooleanField(default=True)),
                ("has_approver", models.BooleanField(default=False)),
                ("has_audit_trail", models.BooleanField(default=True)),
                ("document_is_clear", models.BooleanField(default=False)),
                ("appears_genuine", models.BooleanField(default=False)),
                ("no_alterations", models.BooleanField(default=False)),
                ("has_qr_code", models.BooleanField(default=False)),
                ("total_rules", models.PositiveSmallIntegerField(default=30)),
                ("rules_passed", models.PositiveSmallIntegerField(default=0)),
                ("rules_failed", models.PositiveSmallIntegerField(default=0)),
                ("validation_score", models.FloatField(default=0.0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=dict)),
                ("validated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_validation_results",
            },
        ),
        migrations.CreateModel(
            name="InvoiceBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partial", "Partial (some failed)"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
                (
                    "source_zip",
                    models.FileField(blank=True, null=True, upload_to="batches/%Y/%m/"),
                ),
                ("processing_log", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_batches",
                        to="authentication.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("uploaded", "Invoice Uploaded"),
                            ("processed", "OCR / AI Processed"),
                            ("validated", "Validation Run"),
                            ("flagged", "Flagged"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("commented", "Comment Added"),
                            ("exported", "Exported"),
                            ("reprocessed", "Re-processed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("before_data", models.JSONField(default=dict)),
                ("after_data", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_audit_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.invoicebatch",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("vendor_vat_number", models.CharField(blank=True, max_length=20)),
                ("vendor_cr_number", models.CharField(blank=True, max_length=20)),
                ("first_seen", models.DateField(blank=True, null=True)),
                ("last_seen", models.DateField(blank=True, null=True)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "avg_invoice_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "max_invoice_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("flagged_count", models.PositiveIntegerField(default=0)),
                ("is_new", models.BooleanField(default=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("blocked", "Blocked"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("risk_notes", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profiles",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_profiles",
                "ordering": ["-total_amount"],
                "unique_together": {("organization", "vendor_name")},
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "invoice_number"],
                name="invoices_organiz_78a80e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "vendor_name"],
                name="invoices_organiz_ec248b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "invoice_date"],
                name="invoices_organiz_382970_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status"], name="invoices_organiz_9b03bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["risk_level"], name="invoices_risk_le_2440af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["is_duplicate"], name="invoices_is_dupl_597ae0_idx"
            ),
        ),
    ]
