# Generated by Django 4.2.29 on 2026-03-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_auditsession"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="audit_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="audit.auditsession",
            ),
        ),
        migrations.AddField(
            model_name="invoicebatch",
            name="audit_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_batches",
                to="audit.auditsession",
            ),
        ),
    ]
