# Generated by Django 4.2.29 on 2026-03-30 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cash_flow_class',
            field=models.CharField(choices=[('operating', 'Operating Activities (IAS 7 §15)'), ('investing', 'Investing Activities (IAS 7 §16)'), ('financing', 'Financing Activities (IAS 7 §17)'), ('unclassified', 'Unclassified (Pending Manual Review)')], db_index=True, default='unclassified', help_text='IAS 7 cash flow statement classification per operating/investing/financing', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_flow_confidence',
            field=models.FloatField(default=0.0, help_text='Auto-classification confidence (0.0-1.0); manually set invoices have 1.0'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_flow_subcategory',
            field=models.CharField(blank=True, choices=[('op_revenue', 'Sales Revenue'), ('op_supplies', 'Supplies & Materials'), ('op_utilities', 'Utilities (Water, Electricity, Gas)'), ('op_rent', 'Rent & Leasing'), ('op_salary', 'Salaries & Wages'), ('op_professional', 'Professional Services (Legal, Consulting)'), ('op_maintenance', 'Repairs & Maintenance'), ('op_insurance', 'Insurance'), ('op_travel', 'Travel & Transportation'), ('op_other', 'Other Operating Expenses'), ('inv_equipment', 'Equipment & Machinery'), ('inv_property', 'Property (Real Estate)'), ('inv_intangible', 'Intangible Assets (Software, Patents)'), ('inv_investments', 'Investment Securities'), ('inv_other', 'Other Investing Activities'), ('fin_loan', 'Loan Proceeds'), ('fin_debt_repay', 'Debt Repayment'), ('fin_equity', 'Equity Financing'), ('fin_dividends', 'Dividend Payments'), ('fin_other', 'Other Financing Activities')], help_text='Detailed subcategory for cash flow reporting', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_flow_verified',
            field=models.BooleanField(default=False, help_text='Whether cash flow classification was manually verified by accounting'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_flow_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices_cashflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code_image',
            field=models.TextField(blank=True),
        ),
    ]
