# Generated by Django 4.2.30 on 2026-05-03 18:47
#
# Idempotent variant: the DB ops check information_schema before dropping,
# so this migration succeeds on environments where 0008's constraints/indexes
# never physically materialised (e.g. dump/restore that stripped CHECKs, or a
# past `migrate --fake`). Django's model state still tracks the removals via
# SeparateDatabaseAndState's state_operations.

from django.db import migrations, models


CHECK_CONSTRAINTS = [
    "invoice_total_amount_non_negative",
    "invoice_vat_rate_valid_range",
    "invoice_vat_amount_non_negative",
    "invoice_risk_score_valid_range",
]

# Unique constraints are stored as indexes in MySQL.
UNIQUE_INDEXES_ON_INVOICES = ["invoice_unique_number_per_org"]

PLAIN_INDEXES = [
    ("invoices", "invoice_org_status_active"),
    ("invoices", "invoice_org_risk_active"),
    ("invoices", "invoice_org_date_active"),
    ("vendor_profiles", "vi_org_risk_tier_idx"),
    ("vendor_profiles", "vi_org_approved_idx"),
    ("vendor_profiles", "vi_org_is_new_idx"),
    ("vendor_profiles", "vi_org_risk_score_desc_idx"),
    ("vendor_profiles", "vi_org_compliance_desc_idx"),
    ("vendor_profiles", "vi_org_frequency_desc_idx"),
]


def _drop_db_objects(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cur:
        for cname in CHECK_CONSTRAINTS:
            cur.execute(
                """
                SELECT 1 FROM information_schema.CHECK_CONSTRAINTS
                WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = %s
                """,
                [cname],
            )
            if cur.fetchone():
                cur.execute(f"ALTER TABLE `invoices` DROP CHECK `{cname}`")

        for idx_name in UNIQUE_INDEXES_ON_INVOICES:
            cur.execute(
                """
                SELECT 1 FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'invoices'
                  AND INDEX_NAME = %s
                """,
                [idx_name],
            )
            if cur.fetchone():
                cur.execute(f"ALTER TABLE `invoices` DROP INDEX `{idx_name}`")

        for table, idx_name in PLAIN_INDEXES:
            cur.execute(
                """
                SELECT 1 FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND INDEX_NAME = %s
                """,
                [table, idx_name],
            )
            if cur.fetchone():
                cur.execute(f"ALTER TABLE `{table}` DROP INDEX `{idx_name}`")


def _rename_audit_chain_index(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    table = "invoice_audit_events"
    old_name = "invoice_audit_chain_idx"
    new_name = "invoice_aud_invoice_bfde06_idx"

    with schema_editor.connection.cursor() as cur:
        cur.execute(
            """
            SELECT INDEX_NAME FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND INDEX_NAME IN (%s, %s)
            GROUP BY INDEX_NAME
            """,
            [table, old_name, new_name],
        )
        present = {row[0] for row in cur.fetchall()}

        if new_name in present:
            return
        if old_name in present:
            cur.execute(
                f"ALTER TABLE `{table}` RENAME INDEX `{old_name}` TO `{new_name}`"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_hash_chain_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_drop_db_objects, reverse_code=migrations.RunPython.noop),
                migrations.RunPython(_rename_audit_chain_index, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='invoice_total_amount_non_negative',
                ),
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='invoice_vat_rate_valid_range',
                ),
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='invoice_vat_amount_non_negative',
                ),
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='invoice_risk_score_valid_range',
                ),
                migrations.RemoveConstraint(
                    model_name='invoice',
                    name='invoice_unique_number_per_org',
                ),
                migrations.RemoveIndex(
                    model_name='invoice',
                    name='invoice_org_status_active',
                ),
                migrations.RemoveIndex(
                    model_name='invoice',
                    name='invoice_org_risk_active',
                ),
                migrations.RemoveIndex(
                    model_name='invoice',
                    name='invoice_org_date_active',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_risk_tier_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_approved_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_is_new_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_risk_score_desc_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_compliance_desc_idx',
                ),
                migrations.RemoveIndex(
                    model_name='vendorprofile',
                    name='vi_org_frequency_desc_idx',
                ),
                migrations.RenameIndex(
                    model_name='invoiceauditevent',
                    new_name='invoice_aud_invoice_bfde06_idx',
                    old_name='invoice_audit_chain_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='invoiceauditevent',
            name='event_type',
            field=models.CharField(choices=[('uploaded', 'Invoice Uploaded'), ('processed', 'OCR / AI Processed'), ('validated', 'Validation Run'), ('flagged', 'Flagged'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Comment Added'), ('exported', 'Exported'), ('reprocessed', 'Re-processed'), ('deleted', 'Deleted (Soft)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicevalidationresult',
            name='total_rules',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
