# Generated by Django 4.2.30 on 2026-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_hash_chain_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_total_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_vat_rate_valid_range',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_vat_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_risk_score_valid_range',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_unique_number_per_org',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_status_active',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_risk_active',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_date_active',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_risk_tier_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_approved_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_is_new_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_risk_score_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_compliance_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorprofile',
            name='vi_org_frequency_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceauditevent',
            new_name='invoice_aud_invoice_bfde06_idx',
            old_name='invoice_audit_chain_idx',
        ),
        migrations.AlterField(
            model_name='invoiceauditevent',
            name='event_type',
            field=models.CharField(choices=[('uploaded', 'Invoice Uploaded'), ('processed', 'OCR / AI Processed'), ('validated', 'Validation Run'), ('flagged', 'Flagged'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Comment Added'), ('exported', 'Exported'), ('reprocessed', 'Re-processed'), ('deleted', 'Deleted (Soft)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicevalidationresult',
            name='total_rules',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
