# Generated by Django 4.2.30 on 2026-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_working_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ai_recommendations_ar',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_recommendations_en',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_summary_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_summary_en',
            field=models.TextField(blank=True),
        ),
    ]
