# Generated by Django 4.2.30 on 2026-05-13 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('invoices', '0013_invoice_reviewed_at_invoice_reviewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending countersign'), ('countersigned', 'Countersigned'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countersigned_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_requests_countersigned', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_override_requests', to='authentication.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='invoices_ov_organiz_1bc06e_idx'), models.Index(fields=['invoice', 'status'], name='invoices_ov_invoice_3280ed_idx'), models.Index(fields=['expires_at'], name='invoices_ov_expires_7c4dd8_idx')],
            },
        ),
    ]
