# Generated by Django 4.2.30 on 2026-05-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_overriderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='control_risk',
            field=models.PositiveSmallIntegerField(default=0, help_text='ISA 200: risk that controls fail to prevent/detect (0-100).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='detection_risk',
            field=models.PositiveSmallIntegerField(default=0, help_text="ISA 200: risk that the auditor's procedures miss it (0-100)."),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inherent_risk',
            field=models.PositiveSmallIntegerField(default=0, help_text='ISA 200: susceptibility to misstatement before controls (0-100).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='residual_risk',
            field=models.FloatField(default=0.0, help_text='COSO ERM: inherent_risk × (1 - control_effectiveness).'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'external_source', 'external_id'], name='invoices_organiz_e2f7f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('organization', 'external_source', 'external_id'), name='invoice_unique_ext_per_org'),
        ),
    ]
