# Generated by Django 5.2.17 on 2026-08-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0018_invoice_audit_document_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicevalidationresult",
            name="not_applicable_rule_codes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="invoicevalidationresult",
            name="rules_not_applicable",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="invoicevalidationresult",
            name="rule_results",
            field=models.JSONField(
                default=list,
                help_text="List of per-rule result dicts: [{rule_code, rule_name, group, severity, status, passed, detail}, ...]",
            ),
        ),
    ]
