# Generated by Django 5.2.17 on 2026-08-19 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_chain_partition_and_fork_constraint"),
        ("invoices", "0019_invoicevalidationresult_not_applicable_rule_codes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "stages",
                    models.JSONField(
                        default=list,
                        help_text='Ordered list of role requirements, e.g. [{"role": "finance_manager"}].',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_approval_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflows",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_approval_workflows",
            },
        ),
        migrations.CreateModel(
            name="InvoiceApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("current_stage", models.PositiveSmallIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_request",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_invoice_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="invoices.approvalworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_approval_requests",
            },
        ),
        migrations.CreateModel(
            name="InvoiceApprovalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stage", models.PositiveSmallIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="invoices.invoiceapprovalrequest",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_approval_decisions",
            },
        ),
        migrations.AddConstraint(
            model_name="approvalworkflow",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="uniq_approval_workflow_name_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceapprovalrequest",
            index=models.Index(
                fields=["workflow", "status"], name="invoice_app_workflo_07482f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceapprovaldecision",
            constraint=models.UniqueConstraint(
                fields=("request", "stage"), name="uniq_invoice_approval_stage"
            ),
        ),
    ]
