# Generated by Django 4.2.29 on 2026-03-20 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, default='Saudi Arabia', max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('pricing_inquiry', 'Pricing Inquiry'), ('demo_request', 'Demo Request'), ('partnership', 'Partnership'), ('other', 'Other')], default='contact_form', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.contactlead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'ordering': ['created_at'],
            },
        ),
    ]
