# Generated by Django 4.2.30 on 2026-07-30 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLeadProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, help_text='Reuses Organization.Country (GCC scope) — the single country source.', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='As typed by the registrant, before organisation-name derivation.', max_length=200)),
                ('primary_benefit', models.CharField(blank=True, choices=[('company', 'Use it in my own company'), ('reseller', 'Offer the platform to other companies'), ('accountant', 'I am an accountant'), ('trainer', 'I am a trainer')], max_length=20)),
                ('employee_count', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=10)),
                ('sector', models.CharField(blank=True, help_text='Free text, mirroring Organization.industry.', max_length=100)),
                ('heard_about', models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('friend', 'A friend'), ('partner', 'A partner'), ('other', 'Other')], max_length=20)),
                ('registered_ip', models.GenericIPAddressField(blank=True, help_text='Personal data. Purpose: fraud/abuse triage on trial signups. Staff-only — never serialised to a customer-facing surface.', null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('language', models.CharField(blank=True, help_text="Active locale at registration, e.g. 'ar'.", max_length=10)),
                ('referral_source', models.CharField(blank=True, help_text="Referrer host only (e.g. 'google.com'). Never a full URL — §N data minimisation.", max_length=100)),
                ('campaign_source', models.CharField(blank=True, help_text='utm_source/utm_campaign value only. Never the full tracking URL.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lead_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trial Lead Profile',
                'verbose_name_plural': 'Trial Lead Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country'], name='leads_trial_country_63a204_idx'), models.Index(fields=['primary_benefit'], name='leads_trial_primary_4eb1dd_idx'), models.Index(fields=['created_at'], name='leads_trial_created_14ba26_idx')],
            },
        ),
    ]
