# Generated by Django 4.2.30 on 2026-07-30 12:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_trialleadprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialleadprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='ISO 3166-1 alpha-2. Marketing qualification — where the prospect is. This is NOT Organization.country, which is the billing jurisdiction and stays restricted to the GCC members that map to a currency.', max_length=2),
        ),
    ]
