# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                (
                    "account_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("account_name", models.CharField(blank=True, max_length=255)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("statement_period_from", models.DateField(blank=True, null=True)),
                ("statement_period_to", models.DateField(blank=True, null=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_debits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "calculated_closing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="opening + credits - debits",
                        max_digits=18,
                    ),
                ),
                ("balance_matches", models.BooleanField(default=True)),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                (
                    "transactions",
                    models.JSONField(
                        default=list,
                        help_text="[{date, description, debit, credit, balance, ref}]",
                    ),
                ),
                (
                    "large_tx_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Transactions > 3× avg"
                    ),
                ),
                (
                    "round_amount_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Round-number transactions"
                    ),
                ),
                (
                    "benford_deviation",
                    models.FloatField(
                        default=0.0, help_text="MAD from Benford's Law expected"
                    ),
                ),
                ("duplicate_tx_count", models.PositiveIntegerField(default=0)),
                ("weekend_tx_count", models.PositiveIntegerField(default=0)),
                ("late_night_tx_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "bank_statements",
                "ordering": ["-statement_period_to"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("bank_statement", "Bank Statement"),
                            ("ledger", "General Ledger"),
                            ("contract", "Contract"),
                            ("purchase_order", "Purchase Order"),
                            ("expense_report", "Expense Report"),
                            ("tax_document", "Tax Document"),
                            ("financial_statement", "Financial Statement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("needs_review", "Needs Manual Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("en", "English"),
                            ("mixed", "Arabic + English"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("is_handwritten", models.BooleanField(default=False)),
                ("page_count", models.PositiveIntegerField(default=1)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="0-100 confidence score", null=True
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "processing_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tags", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="authentication.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("employee_name", models.CharField(blank=True, max_length=255)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("report_period_from", models.DateField(blank=True, null=True)),
                ("report_period_to", models.DateField(blank=True, null=True)),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("purpose", models.TextField(blank=True)),
                (
                    "total_claimed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_approved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_rejected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "vat_included",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "expense_lines",
                    models.JSONField(
                        default=list,
                        help_text="[{date, category, description, amount, receipt_attached, receipt_number}]",
                    ),
                ),
                ("missing_receipts_count", models.PositiveIntegerField(default=0)),
                ("duplicate_claims", models.JSONField(default=list)),
                ("over_policy_limit_count", models.PositiveIntegerField(default=0)),
                ("weekend_expense_count", models.PositiveIntegerField(default=0)),
                (
                    "split_transaction_flags",
                    models.JSONField(
                        default=list, help_text="Possible split to avoid limits"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expense_reports",
                "ordering": ["-report_period_to"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("register_date", models.DateField(blank=True, null=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "fiscal_year",
                    models.CharField(blank=True, help_text="e.g. 2024", max_length=9),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_accumulated_depreciation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("asset_count", models.PositiveIntegerField(default=0)),
                (
                    "assets",
                    models.JSONField(
                        default=list,
                        help_text="[{asset_id, name, category, purchase_date, cost, useful_life_years, method, annual_depreciation, accumulated_depreciation, book_value, is_fully_depreciated}]",
                    ),
                ),
                ("negative_book_value_count", models.PositiveIntegerField(default=0)),
                (
                    "over_depreciated_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Accumulated > Cost"
                    ),
                ),
                ("wrong_depreciation_rate", models.JSONField(default=list)),
                ("missing_asset_id_count", models.PositiveIntegerField(default=0)),
                ("duplicate_asset_id_count", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fixed_assets",
                "ordering": ["-register_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payroll_period_from", models.DateField(blank=True, null=True)),
                ("payroll_period_to", models.DateField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "total_gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_gosi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="GOSI / Social insurance",
                        max_digits=18,
                    ),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "employees",
                    models.JSONField(
                        default=list,
                        help_text="[{id, name, gross, allowances, deductions, gosi, net, bank_account}]",
                    ),
                ),
                (
                    "duplicate_employee_ids",
                    models.JSONField(
                        default=list, help_text="Duplicate national IDs found"
                    ),
                ),
                (
                    "ghost_employee_flags",
                    models.JSONField(
                        default=list, help_text="Suspected ghost employees"
                    ),
                ),
                (
                    "salary_spike_flags",
                    models.JSONField(
                        default=list, help_text="Employees with >30% salary increase"
                    ),
                ),
                (
                    "calculation_errors",
                    models.JSONField(
                        default=list, help_text="gross - deductions ≠ net"
                    ),
                ),
                ("missing_gosi_count", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_sheets",
                "ordering": ["-payroll_period_to"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "po_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("po_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("vendor_vat_number", models.CharField(blank=True, max_length=20)),
                ("vendor_cr_number", models.CharField(blank=True, max_length=20)),
                ("requester_name", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("cost_center", models.CharField(blank=True, max_length=50)),
                ("account_code", models.CharField(blank=True, max_length=50)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("received", "Received"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="[{description, qty, unit_price, total}]",
                    ),
                ),
                (
                    "linked_invoice_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Linked Invoice UUID if matched",
                        null=True,
                    ),
                ),
                ("has_price_discrepancy", models.BooleanField(default=False)),
                ("price_discrepancy_pct", models.FloatField(default=0.0)),
                ("quantity_mismatch", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("receipt_date", models.DateField(blank=True, null=True)),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Tax Invoice"),
                            ("simplified", "Simplified Tax Invoice"),
                            ("credit", "Credit Note"),
                            ("debit", "Debit Note"),
                        ],
                        default="simplified",
                        max_length=20,
                    ),
                ),
                ("seller_name", models.CharField(blank=True, max_length=255)),
                ("seller_vat_number", models.CharField(blank=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_vat_number", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("line_items", models.JSONField(default=list)),
                ("has_qr_code", models.BooleanField(default=False)),
                ("qr_code_valid", models.BooleanField(default=False)),
                (
                    "qr_code_data",
                    models.JSONField(default=dict, help_text="Decoded QR TLV fields"),
                ),
                ("zatca_uuid", models.CharField(blank=True, max_length=50)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "file_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.salesreceipt",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_receipts",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="VATReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(default=0.0, help_text="0-100 weighted score"),
                ),
                ("rules_passed", models.PositiveIntegerField(default=0)),
                ("rules_failed", models.PositiveIntegerField(default=0)),
                ("failed_rule_codes", models.JSONField(default=list)),
                ("validation_details", models.JSONField(default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "anomalies_found",
                    models.JSONField(
                        default=list, help_text="List of detected anomalies"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("taxpayer_name", models.CharField(blank=True, max_length=255)),
                (
                    "vat_number",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("cr_number", models.CharField(blank=True, max_length=20)),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted by ZATCA"),
                            ("rejected", "Rejected by ZATCA"),
                            ("amended", "Amended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("zatca_reference", models.CharField(blank=True, max_length=100)),
                (
                    "standard_rated_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "zero_rated_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "exempt_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "output_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "standard_rated_purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "input_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_vat_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "vat_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "calculated_output_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "calculated_input_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "calculated_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "output_discrepancy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "input_discrepancy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_late_filing", models.BooleanField(default=False)),
                ("late_days", models.IntegerField(default=0)),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vat_returns",
                "ordering": ["-period_to"],
            },
        ),
        migrations.CreateModel(
            name="VATReturnValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vat_number_valid", models.BooleanField(default=True)),
                ("output_vat_correct", models.BooleanField(default=True)),
                ("input_vat_correct", models.BooleanField(default=True)),
                ("net_vat_correct", models.BooleanField(default=True)),
                ("no_output_discrepancy", models.BooleanField(default=True)),
                ("no_input_discrepancy", models.BooleanField(default=True)),
                ("filed_on_time", models.BooleanField(default=True)),
                ("period_complete", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vat_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.vatreturn",
                    ),
                ),
            ],
            options={
                "db_table": "vat_return_validations",
            },
        ),
        migrations.CreateModel(
            name="SalesReceiptValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_receipt_number", models.BooleanField(default=True)),
                ("has_receipt_date", models.BooleanField(default=True)),
                ("vat_rate_correct", models.BooleanField(default=True)),
                ("vat_calculation_correct", models.BooleanField(default=True)),
                ("has_qr_code", models.BooleanField(default=True)),
                ("qr_code_valid", models.BooleanField(default=True)),
                ("no_duplicate", models.BooleanField(default=True)),
                ("seller_vat_present", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.salesreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "sales_receipt_validations",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_po_number", models.BooleanField(default=True)),
                ("has_po_date", models.BooleanField(default=True)),
                ("has_vendor_name", models.BooleanField(default=True)),
                ("has_vendor_vat", models.BooleanField(default=True)),
                ("vat_calculation_ok", models.BooleanField(default=True)),
                ("within_budget", models.BooleanField(default=True)),
                ("has_approver", models.BooleanField(default=True)),
                ("no_price_discrepancy", models.BooleanField(default=True)),
                ("no_quantity_mismatch", models.BooleanField(default=True)),
                ("has_cost_center", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "po",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_validations",
            },
        ),
        migrations.CreateModel(
            name="PayrollValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("no_duplicate_ids", models.BooleanField(default=True)),
                ("no_ghost_employees", models.BooleanField(default=True)),
                ("net_calculation_correct", models.BooleanField(default=True)),
                ("gosi_present", models.BooleanField(default=True)),
                ("no_salary_spikes", models.BooleanField(default=True)),
                ("has_bank_accounts", models.BooleanField(default=True)),
                ("period_valid", models.BooleanField(default=True)),
                ("totals_match", models.BooleanField(default=True)),
                ("employee_count_consistent", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payroll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.payrollsheet",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_validations",
            },
        ),
        migrations.CreateModel(
            name="FixedAssetValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("no_negative_book_values", models.BooleanField(default=True)),
                ("no_over_depreciation", models.BooleanField(default=True)),
                ("depreciation_rates_correct", models.BooleanField(default=True)),
                ("no_duplicate_asset_ids", models.BooleanField(default=True)),
                ("all_assets_have_ids", models.BooleanField(default=True)),
                ("book_value_calculation_ok", models.BooleanField(default=True)),
                ("useful_life_reasonable", models.BooleanField(default=True)),
                ("totals_consistent", models.BooleanField(default=True)),
                ("purchase_dates_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.fixedasset",
                    ),
                ),
            ],
            options={
                "db_table": "fixed_asset_validations",
            },
        ),
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, help_text="Full OCR text output"),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        default=dict, help_text="Parsed structured fields"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Validation"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                            ("auto_validated", "Auto-Validated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corrections",
                    models.JSONField(
                        default=dict, help_text="Human corrections applied"
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="tesseract",
                        help_text="tesseract | openai | hybrid",
                        max_length=50,
                    ),
                ),
                ("ai_model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="documents.document",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extracted_data",
            },
        ),
        migrations.CreateModel(
            name="ExpenseReportValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("all_receipts_attached", models.BooleanField(default=True)),
                ("no_duplicate_claims", models.BooleanField(default=True)),
                ("within_policy_limits", models.BooleanField(default=True)),
                ("has_approver", models.BooleanField(default=True)),
                ("no_split_transactions", models.BooleanField(default=True)),
                ("valid_dates", models.BooleanField(default=True)),
                ("vat_calculation_ok", models.BooleanField(default=True)),
                ("totals_match", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.expensereport",
                    ),
                ),
            ],
            options={
                "db_table": "expense_report_validations",
            },
        ),
        migrations.CreateModel(
            name="DocumentPageResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.PositiveSmallIntegerField()),
                ("raw_text", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_results",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_page_results",
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("balance_reconciled", models.BooleanField(default=True)),
                ("no_large_transactions", models.BooleanField(default=True)),
                ("no_duplicate_transactions", models.BooleanField(default=True)),
                ("benford_law_ok", models.BooleanField(default=True)),
                ("no_round_amounts", models.BooleanField(default=True)),
                ("no_weekend_transactions", models.BooleanField(default=True)),
                ("account_number_present", models.BooleanField(default=True)),
                ("period_complete", models.BooleanField(default=True)),
                ("iban_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="documents.bankstatement",
                    ),
                ),
            ],
            options={
                "db_table": "bank_statement_validations",
            },
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="vatreturn",
            index=models.Index(
                fields=["organization", "period_from"],
                name="vat_returns_organiz_20e0df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vatreturn",
            index=models.Index(
                fields=["vat_number"], name="vat_returns_vat_num_1dd40b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vatreturn",
            index=models.Index(
                fields=["filing_status"], name="vat_returns_filing__71d468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreceipt",
            index=models.Index(
                fields=["organization", "receipt_date"],
                name="sales_recei_organiz_83b0b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesreceipt",
            index=models.Index(
                fields=["seller_vat_number"], name="sales_recei_seller__065900_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreceipt",
            index=models.Index(
                fields=["is_duplicate"], name="sales_recei_is_dupl_5b6c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreceipt",
            index=models.Index(
                fields=["file_hash"], name="sales_recei_file_ha_840fca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["organization", "po_date"],
                name="purchase_or_organiz_aef186_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["vendor_name"], name="purchase_or_vendor__46e5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["approval_status"], name="purchase_or_approva_56e3af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollsheet",
            index=models.Index(
                fields=["organization", "payroll_period_from"],
                name="payroll_she_organiz_a83620_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollsheet",
            index=models.Index(
                fields=["department"], name="payroll_she_departm_d96207_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["organization", "fiscal_year"],
                name="fixed_asset_organiz_a14dc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["department"], name="fixed_asset_departm_b3245e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensereport",
            index=models.Index(
                fields=["organization", "submitted_date"],
                name="expense_rep_organiz_0c64b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensereport",
            index=models.Index(
                fields=["employee_name"], name="expense_rep_employe_1fefa1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentpageresult",
            unique_together={("document", "page_number")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "document_type"],
                name="documents_organiz_e6d566_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["processing_status"], name="documents_process_e1e618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_created_3c6eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["organization", "statement_period_from"],
                name="bank_statem_organiz_03247b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["account_number"], name="bank_statem_account_f82e23_idx"
            ),
        ),
    ]
