# Generated by Django 4.2.29 on 2026-03-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_audit_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='vatreturn',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
