# Generated by Django 4.2.29 on 2026-03-22 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_bankstatement_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label_en', models.CharField(max_length=200)),
                ('label_ar', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('json', 'JSON Array/Object')], max_length=20)),
                ('field_group', models.CharField(choices=[('identity', 'Core Identity'), ('counterparty', 'Counterparty'), ('financial', 'Financial'), ('compliance', 'Compliance / ZATCA'), ('timeline', 'Timeline'), ('classification', 'Classification'), ('hr_payroll', 'HR / Payroll'), ('asset', 'Fixed Asset')], max_length=30)),
                ('is_nullable', models.BooleanField(default=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('applicable_document_types', models.JSONField(default=list, help_text='["invoice","purchase_order",...] or ["*"] for all types')),
                ('required_for_storage', models.BooleanField(default=False)),
                ('required_for_rule_execution', models.BooleanField(default=False)),
                ('required_for_reporting', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canonical Field Definition',
                'verbose_name_plural': 'Canonical Field Definitions',
                'ordering': ['field_group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCanonicalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('typed_model_name', models.CharField(max_length=100)),
                ('typed_object_id', models.UUIDField(db_index=True)),
                ('canonical_data', models.JSONField(default=dict)),
                ('extraction_confidence', models.JSONField(default=dict, help_text='{field_code: 0.0-1.0}')),
                ('extraction_source', models.JSONField(default=dict, help_text="{field_code: 'ai'|'ocr'|'direct'|'default'|'human'}")),
                ('raw_ai_output', models.JSONField(default=dict)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Canonical Data',
                'verbose_name_plural': 'Document Canonical Data',
                'indexes': [models.Index(fields=['document_type'], name='documents_d_documen_2843a5_idx'), models.Index(fields=['typed_object_id'], name='documents_d_typed_o_93fe55_idx')],
                'unique_together': {('typed_model_name', 'typed_object_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('source_column', models.CharField(db_index=True, max_length=200)),
                ('source_column_ar', models.CharField(blank=True, max_length=200)),
                ('transform', models.CharField(default='direct', max_length=50)),
                ('transform_args', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='documents.canonicalfielddefinition')),
            ],
            options={
                'verbose_name': 'Document Type Field Mapping',
                'verbose_name_plural': 'Document Type Field Mappings',
                'ordering': ['-priority'],
                'unique_together': {('canonical_field', 'document_type', 'source_column')},
            },
        ),
    ]
