# Generated by Django 4.2.30 on 2026-05-02 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        ('documents', '0007_supplierstatement_salesorder_receiptvoucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('validation_score', models.FloatField(default=0.0, help_text='0-100 weighted score')),
                ('rules_passed', models.PositiveIntegerField(default=0)),
                ('rules_failed', models.PositiveIntegerField(default=0)),
                ('failed_rule_codes', models.JSONField(default=list)),
                ('validation_details', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(default=list)),
                ('anomalies_found', models.JSONField(default=list, help_text='List of detected anomalies')),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('fiscal_period', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lines_count', models.PositiveIntegerField(default=0)),
                ('is_balanced', models.BooleanField(default=False)),
                ('lines', models.JSONField(default=list)),
                ('is_manual', models.BooleanField(default=True, help_text='True if entered manually vs imported')),
                ('has_attachment', models.BooleanField(default=False)),
                ('is_period_close', models.BooleanField(default=False, help_text='Posted at period-end')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entry_documents',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['organization', 'entry_date'], name='journal_ent_organiz_fba64c_idx'), models.Index(fields=['entry_number'], name='journal_ent_entry_n_32df0b_idx'), models.Index(fields=['is_balanced'], name='journal_ent_is_bala_8c0eea_idx')],
            },
        ),
    ]
