# Generated by Django 4.2.30 on 2026-05-11 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_user_last_totp_counter'),
        ('documents', '0009_bankstatement_ai_recommendations_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, help_text="Target doc type (e.g. 'invoice', 'purchase_order'). Blank for ZIP uploads where each member has its own type.", max_length=32)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('zip', 'ZIP archive'), ('xlsx', 'Excel'), ('xls', 'Legacy Excel'), ('csv', 'CSV'), ('jsonl', 'JSON Lines'), ('json', 'JSON array'), ('mixed', 'Multiple kinds inside a ZIP')], default='csv', max_length=12)),
                ('source_file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial — some rows failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('task_ids', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_upload_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_jobs', to='authentication.organization')),
            ],
            options={
                'db_table': 'bulk_upload_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based row index inside the source file (CSV/XLSX/JSONL), or the member index inside a ZIP.')),
                ('source_path', models.CharField(blank=True, help_text="Relative path inside the source (e.g. 'invoices/2026/inv1.pdf').", max_length=512)),
                ('document_type', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('created_document_id', models.UUIDField(blank=True, null=True)),
                ('audit_run_id', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.bulkuploadjob')),
            ],
            options={
                'db_table': 'bulk_upload_items',
                'ordering': ['job', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkuploadjob',
            index=models.Index(fields=['organization', '-created_at'], name='bulk_upload_organiz_9a3d63_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadjob',
            index=models.Index(fields=['organization', 'status'], name='bulk_upload_organiz_721044_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['job', 'status'], name='bulk_upload_job_id_9a4b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploaditem',
            index=models.Index(fields=['job', 'row_number'], name='bulk_upload_job_id_a6a422_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkuploaditem',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='bulk_item_unique_row'),
        ),
    ]
