# Generated by Django 4.2.30 on 2026-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_bulkuploadjob_bulkuploaditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadjob',
            name='allowed_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadjob',
            name='blocked_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadjob',
            name='quota_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadjob',
            name='quota_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadjob',
            name='quota_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('allowed', 'Allowed'), ('partially_allowed', 'Partially allowed'), ('quota_exceeded', 'Quota exceeded')], default='not_checked', max_length=20),
        ),
    ]
