# Generated by Django 4.2.30 on 2026-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_bulkuploadjob_allowed_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
