# Generated by Django 4.2.30 on 2026-08-11 09:48

"""Give every canonical row an explicit owner.

DocumentCanonicalData holds extracted content that audits and reports read, but
it pointed at its parent with `typed_model_name` + `typed_object_id` — a
generic pointer, not a relation. The ORM cannot traverse it, so there was no
join to filter on and no cascade to clean up after a deleted tenant. Isolation
existed only where a caller remembered to resolve the parent first.

The column is nullable on purpose, and the backfill explains why: 1,003 of
2,830 rows name a PurchaseOrder that no longer exists. No organisation can be
derived for them by any means, so they are left NULL and counted rather than
guessed at or deleted. Narrowing to NOT NULL is a later decision about those
rows, not something to force here.
"""

from django.db import migrations, models
import django.db.models.deletion


def backfill_organization(apps, schema_editor):
    """Resolve each row's tenant through the parent it names.

    The lookup goes through django_apps rather than a hand-written map: the
    same class of map, written once in the billing gate, is what sent this
    codebase looking for the wrong JournalEntry.

    `Invoice` is resolved from apps.invoices, not documents — 24 rows name it,
    and scoping the lookup to a single app would silently leave them behind
    while reporting success.
    """
    from django.apps import apps as django_apps

    Canonical = apps.get_model("documents", "DocumentCanonicalData")

    resolved = orphaned = unresolvable_model = 0
    batch, BATCH = [], 500

    for row in Canonical.objects.all().iterator(chunk_size=BATCH):
        model = None
        for app_label in ("documents", "invoices"):
            try:
                model = django_apps.get_model(app_label, row.typed_model_name)
                break
            except LookupError:
                continue
        if model is None:
            unresolvable_model += 1
            continue

        parent = model.objects.filter(pk=row.typed_object_id).first()
        if parent is None:
            orphaned += 1
            continue

        org_id = getattr(parent, "organization_id", None)
        if org_id is None:
            # The parent exists but is itself unowned — nothing to inherit.
            orphaned += 1
            continue

        row.organization_id = org_id
        batch.append(row)
        resolved += 1
        if len(batch) >= BATCH:
            Canonical.objects.bulk_update(batch, ["organization"])
            batch = []

    if batch:
        Canonical.objects.bulk_update(batch, ["organization"])

    print(
        f"\n[0013] canonical rows: assigned={resolved} "
        f"left_null_parent_missing={orphaned} "
        f"left_null_model_unknown={unresolvable_model}"
    )



class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_chain_partition_and_fork_constraint'),
        ('documents', '0012_document_file_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcanonicaldata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_documents', to='authentication.organization'),
        ),
        # Between the column and the index: the index is on a column that
        # would otherwise be entirely NULL at the moment it is built.
        migrations.RunPython(backfill_organization, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='documentcanonicaldata',
            index=models.Index(fields=['organization', 'typed_object_id'], name='canonicaldata_org_object_idx'),
        ),
    ]
