#!/bin/bash
# ============================================================
# FinAI Deployment — Step 07: Monitoring & Log Rotation
# Usage: bash 07_monitoring.sh [live|dev|test]
# Sets up: health-check cron, logrotate, disk-alert cron
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV="${1:-live}"

ENV_FILE="$SCRIPT_DIR/config/${ENV}.env"
[ -f "$ENV_FILE" ] || { echo "❌ Unknown environment: $ENV"; exit 1; }
source "$ENV_FILE"

mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/monitoring.log"
export DEBIAN_FRONTEND=noninteractive

log() { echo "$(date '+%F %T') [$ENV_LABEL] $1" | tee -a "$LOG_FILE"; }

resolve_socket_path() {
  local configured_socket="$1"
  local configured_dir
  configured_dir="$(dirname "$configured_socket")"

  if [ "$configured_dir" = "/run" ]; then
    echo "/run/${SERVICE_NAME}/$(basename "$configured_socket")"
  else
    echo "$configured_socket"
  fi
}

HEALTH_SCRIPT="/usr/local/bin/finai_health_${ENV}.sh"
STATUS_FILE="$LOG_DIR/health.status"
MONITOR_SOCKET="$(resolve_socket_path "$SOCKET")"

echo ""
echo "╔═══════════════════════════════════════════════════╗"
echo "║  FinAI [$ENV_LABEL] — STEP 07: Monitoring Setup  ║"
echo "╚═══════════════════════════════════════════════════╝"
echo ""

# ── Health check script ───────────────────────────────────────────────────────
log "📝 Writing health check script: $HEALTH_SCRIPT"

cat > "$HEALTH_SCRIPT" <<SCRIPT
#!/bin/bash
# FinAI [$ENV_LABEL] — Health Check
# Auto-generated by 07_monitoring.sh

set -euo pipefail

LOG_DIR="$LOG_DIR"
STATUS_FILE="$STATUS_FILE"
LOG_FILE="\$LOG_DIR/health.log"
DOMAIN_MAIN="$DOMAIN_MAIN"
HEALTH_URL="http://127.0.0.1/health/"
SECRET_FILE="$WEB_ROOT/.secret.env"
SOCKET_PATH="$MONITOR_SOCKET"
DB_NAME="$DB_NAME"
DB_USER="$DB_USER"
DB_HOST="$DB_HOST"
DB_PORT="$DB_PORT"
REDIS_URL="${REDIS_URL:-}"

mkdir -p "\$LOG_DIR"
: > "\$STATUS_FILE"   # Clear status file on each run

log() { echo "\$(date '+%F %T') [$ENV_LABEL] \$1" | tee -a "\$LOG_FILE"; }

mark_issue() {
  local code="\$1"
  local detail="\${2:-}"
  echo "\${code}:\${detail}:\$(date +%s)" >> "\$STATUS_FILE"
  HEALTHY=false
}

health_http_code() {
  if command -v curl &>/dev/null; then
    curl -sS -o /dev/null -w "%{http_code}" --max-time 10 -H "Host: \$DOMAIN_MAIN" "\$HEALTH_URL" 2>/dev/null || echo "000"
    return
  fi

  if command -v wget &>/dev/null; then
    wget -q -S --spider --timeout=10 --header="Host: \$DOMAIN_MAIN" "\$HEALTH_URL" 2>&1 | awk '/HTTP\// { code=\$2 } END { print code ? code : "000" }' || echo "000"
    return
  fi

  echo "000"
}

HEALTHY=true

# ── Service checks ──────────────────────────────────────────────────────────
for SVC in $SERVICE_NAME ${SERVICE_NAME}_celery ${SERVICE_NAME}_celerybeat nginx redis-server; do
  if systemctl is-active --quiet "\$SVC" 2>/dev/null; then
    log "✅ Service OK: \$SVC"
  else
    log "❌ Service DOWN: \$SVC"
    mark_issue "DOWN" "\$SVC"
    # Auto-restart attempt
    systemctl restart "\$SVC" 2>/dev/null && log "♻️  Auto-restarted \$SVC" || log "⚠️  Could not restart \$SVC"
  fi
done

# ── HTTP endpoint check ──────────────────────────────────────────────────────
HTTP_CODE=\$(health_http_code)
if [[ "\$HTTP_CODE" == "200" || "\$HTTP_CODE" == "301" || "\$HTTP_CODE" == "302" || "\$HTTP_CODE" == "307" || "\$HTTP_CODE" == "308" ]]; then
  log "✅ HTTP health check OK (\$HTTP_CODE)"
else
  log "❌ HTTP health check FAILED (\$HTTP_CODE)"
  mark_issue "HTTP" "\$HTTP_CODE"
fi

# ── Disk space check ─────────────────────────────────────────────────────────
FREE_KB=\$(df $WEB_ROOT | tail -1 | awk '{print \$4}')
FREE_GB=\$(echo "scale=1; \$FREE_KB/1048576" | bc 2>/dev/null || echo "?")
if [ "\$FREE_KB" -lt 2097152 ]; then   # < 2 GB
  log "⚠️  Low disk space: \${FREE_GB}GB free"
  mark_issue "DISK_LOW" "\${FREE_GB}GB"
else
  log "✅ Disk space: \${FREE_GB}GB free"
fi

# ── MySQL check ──────────────────────────────────────────────────────────────
DB_PASSWORD=""
if [ -f "\$SECRET_FILE" ]; then
  DB_PASSWORD=\$(grep '^DB_PASSWORD=' "\$SECRET_FILE" | head -n 1 | cut -d= -f2- || true)
fi

if ! command -v mysql &>/dev/null; then
  log "⚠️  MySQL client is not installed"
  mark_issue "MYSQL_CLIENT_MISSING" "mysql"
elif MYSQL_PWD="\$DB_PASSWORD" mysql -h "\$DB_HOST" -P "\$DB_PORT" -u "\$DB_USER" -e "SELECT 1;" "\$DB_NAME" &>/dev/null; then
  log "✅ MySQL connection OK"
else
  log "❌ MySQL connection FAILED"
  mark_issue "MYSQL_DOWN" "\$DB_HOST"
fi

# ── Redis check ───────────────────────────────────────────────────────────────
if ! command -v redis-cli &>/dev/null; then
  log "⚠️  redis-cli is not installed"
  mark_issue "REDIS_CLIENT_MISSING" "redis-cli"
elif { [ -n "\$REDIS_URL" ] && redis-cli -u "\$REDIS_URL" ping &>/dev/null; } || { [ -z "\$REDIS_URL" ] && redis-cli ping &>/dev/null; }; then
  log "✅ Redis OK"
else
  log "❌ Redis not responding"
  mark_issue "REDIS_DOWN" "redis"
fi

# ── Gunicorn socket check ──────────────────────────────────────────────────────
if [ -S "\$SOCKET_PATH" ]; then
  log "✅ Gunicorn socket exists"
else
  log "❌ Gunicorn socket missing"
  mark_issue "SOCKET_MISSING" "\$SOCKET_PATH"
fi

# ── Final summary ─────────────────────────────────────────────────────────────
if \$HEALTHY; then
  log "🎉 [$ENV_LABEL] All systems healthy"
else
  log "🚨 [$ENV_LABEL] ISSUES DETECTED — see \$STATUS_FILE"
fi
SCRIPT

chmod +x "$HEALTH_SCRIPT"
log "✅ Health check script created"

# ── Health check cron (every 5 minutes) ──────────────────────────────────────
CRON_FILE="/etc/cron.d/finai_health_${ENV}"
CRON_ENTRY="*/5 * * * * root $HEALTH_SCRIPT >> $LOG_DIR/health_cron.log 2>&1"

echo "$CRON_ENTRY" > "$CRON_FILE"
chmod 644 "$CRON_FILE"
log "⏰ Health check cron installed/updated (every 5 minutes)"

# ── Logrotate ─────────────────────────────────────────────────────────────────
LOGROTATE_FILE="/etc/logrotate.d/finai_${ENV}"
log "📝 Writing logrotate config: $LOGROTATE_FILE"

cat > "$LOGROTATE_FILE" <<LOGROTATE
$LOG_DIR/*.log
/var/log/nginx/finai_${ENV}_*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    create 0640 www-data adm
    postrotate
        systemctl reload nginx 2>/dev/null || true
        systemctl kill -s USR1 ${SERVICE_NAME} 2>/dev/null || true
    endscript
}
LOGROTATE

log "✅ Logrotate configured (14-day retention)"

# ── Run health check immediately ──────────────────────────────────────────────
log "🔍 Running initial health check..."
bash "$HEALTH_SCRIPT" || true

# ── Monitoring summary ────────────────────────────────────────────────────────
log "📊 Services status summary:"
for SVC in "$SERVICE_NAME" "${SERVICE_NAME}_celery" "${SERVICE_NAME}_celerybeat" nginx redis-server; do
  STATUS=$(systemctl is-active "$SVC" 2>/dev/null || echo "not-found")
  [ "$STATUS" = "active" ] && ICON="✅" || ICON="❌"
  log "  $ICON $SVC: $STATUS"
done

echo ""
echo "✅ [STEP 07] Monitoring Setup COMPLETED for [$ENV_LABEL]"
echo "   Health check: $HEALTH_SCRIPT (every 5 minutes)"
echo "   Status file:  $STATUS_FILE"
