# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_description", models.CharField(max_length=255)),
                ("standard", models.CharField(max_length=20)),
                ("severity", models.CharField(default="medium", max_length=10)),
                ("description", models.TextField()),
                ("corrective_action", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_violations",
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("ZATCA", "ZATCA (Saudi e-invoicing)"),
                            ("VAT", "VAT Regulations"),
                            ("IFRS", "IFRS"),
                            ("GAAP", "GAAP"),
                            ("SAMA", "Saudi Arabian Monetary Authority"),
                            ("INTERNAL", "Internal Policy"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("rule_expression", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_rules",
            },
        ),
    ]
