# Generated by Django 4.2.29 on 2026-03-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceviolation",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_violations",
                to="invoices.invoice",
            ),
        ),
    ]
