# Generated by Django 4.2.30 on 2026-05-12 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('moyasar', 'Moyasar'), ('tap', 'Tap Payments'), ('telr', 'Telr')], max_length=16)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription'), ('invoice', 'Invoice'), ('service_order', 'Service Order'), ('wallet_topup', 'Wallet Top-Up'), ('other', 'Other')], max_length=20)),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('redirect_required', 'Redirect Required'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=24)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=1024)),
                ('success_url', models.URLField(blank=True, default='', max_length=1024)),
                ('cancel_url', models.URLField(blank=True, default='', max_length=1024)),
                ('failure_url', models.URLField(blank=True, default='', max_length=1024)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=512)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='authentication.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('moyasar', 'Moyasar'), ('tap', 'Tap Payments'), ('telr', 'Telr')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('public_key', models.CharField(blank=True, default='', max_length=256)),
                ('secret_key', models.CharField(blank=True, default='', max_length=512)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=128)),
                ('store_id', models.CharField(blank=True, default='', max_length=128)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_provider_configs', to='authentication.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('status_before', models.CharField(blank=True, default='', max_length=24)),
                ('status_after', models.CharField(blank=True, default='', max_length=24)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['organization', 'status'], name='payments_pa_organiz_4d9838_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='payments_pa_provide_85e3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['purpose', 'reference_type', 'reference_id'], name='payments_pa_purpose_191017_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderconfig',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='payments_provider_config_org_provider_unique'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['transaction', 'event_type'], name='payments_pa_transac_ef53ab_idx'),
        ),
    ]
