# Generated by Django 4.2.30 on 2026-05-12 16:04

import apps.payments.encryption
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='secret_key',
            field=apps.payments.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='FailedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=16)),
                ('reason', models.CharField(choices=[('unverified', 'Signature/verification failed'), ('bad_payload', 'Unparseable body'), ('unknown_txn', 'No matching transaction'), ('dispatch_err', 'Error during dispatch')], max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.BinaryField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('replayed', models.BooleanField(default=False)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'reason'], name='payments_fa_provide_7345d5_idx'), models.Index(fields=['replayed'], name='payments_fa_replaye_69e69a_idx')],
            },
        ),
    ]
