# Generated by Django 4.2.30 on 2026-05-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentproviderconfig_secret_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentProviderConfig',
        ),
    ]
