# Generated by Django 4.2.30 on 2026-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_paymentproviderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('moyasar', 'Moyasar'), ('tap', 'Tap Payments'), ('telr', 'Telr'), ('manual', 'Manual (offline / bank transfer)')], max_length=16),
        ),
    ]
