# Generated by Django 5.2.17 on 2026-08-16 18:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_paymenttransaction_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="business_action_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="business_action_error",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="business_action_status",
            field=models.CharField(default="pending", max_length=16),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refunded_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction", "status"],
                        name="payments_pa_transac_71b3a2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_refund_id__gt", "")),
                        fields=("transaction", "provider_refund_id"),
                        name="uniq_provider_refund_per_transaction",
                    )
                ],
            },
        ),
    ]
