# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in source ERP system", max_length=100
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income / Revenue"),
                            ("expense", "Expense"),
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("transfer", "Transfer"),
                            ("journal_entry", "Journal Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("sub_category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("vendor_vat_number", models.CharField(blank=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("transaction_date", models.DateField()),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("account_debit", models.CharField(blank=True, max_length=50)),
                ("account_credit", models.CharField(blank=True, max_length=50)),
                ("cost_center", models.CharField(blank=True, max_length=50)),
                (
                    "risk_score",
                    models.FloatField(default=0.0, help_text="0-100 AI risk score"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.TextField(blank=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="authentication.organization",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "transaction_date"],
                        name="transaction_organiz_232c03_idx",
                    ),
                    models.Index(
                        fields=["organization", "transaction_type"],
                        name="transaction_organiz_29bcb8_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="transaction_risk_le_883d2c_idx"
                    ),
                    models.Index(
                        fields=["is_flagged"], name="transaction_is_flag_f9d307_idx"
                    ),
                    models.Index(
                        fields=["vendor_name"], name="transaction_vendor__1a1c64_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="transaction_referen_dda4a8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_number", models.CharField(max_length=50)),
                ("entry_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Manual entries flagged for extra scrutiny",
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversal_date", models.DateField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "lines",
                    models.JSONField(
                        default=list, help_text="List of debit/credit line items"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="authentication.organization",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "journal_entries",
                "ordering": ["-entry_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "entry_date"],
                        name="journal_ent_organiz_069fe9_idx",
                    ),
                    models.Index(
                        fields=["is_manual", "is_suspicious"],
                        name="journal_ent_is_manu_238664_idx",
                    ),
                ],
            },
        ),
    ]
