# Generated by Django 4.2.30 on 2026-05-01 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_auditlog_retain_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(help_text='HMAC-SHA256 secret. We sign every delivery with this so receivers can verify authenticity.', max_length=64)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to, e.g. ["invoice.created", "invoice.flagged"]')),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='authentication.organization')),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('invoice.created', 'Invoice created'), ('invoice.approved', 'Invoice approved'), ('invoice.rejected', 'Invoice rejected'), ('invoice.flagged', 'Invoice flagged'), ('audit.completed', 'Audit completed'), ('document.uploaded', 'Document uploaded')], max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('exhausted', 'Exhausted (gave up)')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_response_body', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='webhook_end_organiz_f3cdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='webhook_del_endpoin_571380_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_741062_idx'),
        ),
    ]
