# Generated by Django 5.2.17 on 2026-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="event_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "event_key"), name="unique_webhook_endpoint_event"
            ),
        ),
    ]
