# Generated by Django 4.2.30 on 2026-05-03 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        ('invoices', '0011_working_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EGSDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(db_index=True, max_length=64)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Fatoora)'), ('simulation', 'Simulation'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('csr_pem', models.TextField(blank=True, help_text='Base64 PEM-encoded Certificate Signing Request.')),
                ('certificate_pem', models.TextField(blank=True, help_text='Base64 PEM-encoded X.509 cert from ZATCA CA.')),
                ('private_key_encrypted', models.BinaryField(blank=True, help_text='Fernet-encrypted PEM private key.', null=True)),
                ('csid_secret_encrypted', models.BinaryField(blank=True, help_text='Fernet-encrypted CSID secret used to sign API requests.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending CSR generation'), ('csr_ready', 'CSR ready for submission'), ('compliance', 'Compliance CSID active (sandbox)'), ('active', 'Production CSID active'), ('expiring', 'Cert expiring within 30 days'), ('expired', 'Cert expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egs_devices', to='authentication.organization')),
            ],
            options={
                'db_table': 'zatca_egs_devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectionCode',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, help_text='BR-KSA / KSA / BR-CO / BR / Schema', max_length=32)),
                ('severity', models.CharField(default='error', help_text='error | warning | info', max_length=12)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('fix_hint_en', models.TextField(blank=True, help_text='Concrete suggestion the auditor can apply.')),
                ('fix_hint_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'zatca_rejection_codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category', 'severity'], name='zatca_rejec_categor_746e98_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zatca_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('submission_type', models.CharField(choices=[('clearance', 'B2B clearance (synchronous)'), ('reporting', 'B2C reporting (asynchronous)')], default='clearance', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed XML ready'), ('submitted', 'Submitted, waiting'), ('cleared', 'Cleared by ZATCA'), ('reported', 'Reported (B2C)'), ('rejected', 'Rejected by ZATCA'), ('warning', 'Accepted with warnings'), ('error', 'Local error before submit')], db_index=True, default='draft', max_length=12)),
                ('xml_unsigned', models.TextField(blank=True)),
                ('xml_signed', models.TextField(blank=True, help_text='UBL XML with cryptographic stamp + Previous Invoice Hash chain.')),
                ('invoice_hash', models.CharField(blank=True, db_index=True, help_text="SHA-256 of the canonicalised signed XML — input for the next invoice's PIH.", max_length=128)),
                ('previous_invoice_hash', models.CharField(blank=True, help_text="The invoice_hash of the previous submission in this org's chain (PIH).", max_length=128)),
                ('chain_position', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('qr_tlv_base64', models.TextField(blank=True)),
                ('response_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('response_status', models.CharField(blank=True, max_length=24)),
                ('response_warnings', models.JSONField(blank=True, default=list)),
                ('response_errors', models.JSONField(blank=True, default=list)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('cleared_xml', models.TextField(blank=True, help_text='Returned cleared XML (B2B only) — what we must keep for legal evidence.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egs_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='zatca.egsdevice')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zatca_submissions', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zatca_submissions', to='authentication.organization')),
            ],
            options={
                'db_table': 'zatca_invoice_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='zatca_invoi_organiz_a46167_idx'), models.Index(fields=['organization', 'chain_position'], name='zatca_invoi_organiz_877c94_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='egsdevice',
            index=models.Index(fields=['organization', 'status'], name='zatca_egs_d_organiz_fd9a43_idx'),
        ),
        migrations.AddConstraint(
            model_name='egsdevice',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='zatca_egs_unique_serial_per_org'),
        ),
    ]
