# Generated by Django 4.2.30 on 2026-05-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('request_path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(blank=True, help_text='SHA-256 of the request body — guard against key reuse on different payloads.', max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_idempotency_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='Stable identifier the app generates on first launch (e.g. iOS identifierForVendor).', max_length=128)),
                ('device_name', models.CharField(blank=True, help_text="Human label shown on the security page (e.g. 'iPhone 15 Pro')", max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web (PWA)')], max_length=8)),
                ('push_token', models.CharField(blank=True, help_text='FCM token (Android/Web) or APNs token (iOS).', max_length=512)),
                ('biometric_pubkey', models.TextField(blank=True, help_text='PEM-encoded ed25519 / WebAuthn-COSE public key bound to the device. Optional.')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='mobile_devi_user_id_e78a57_idx'), models.Index(fields=['push_token'], name='mobile_devi_push_to_624d9b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mobiledevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='mobile_device_unique_per_user'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['user', 'expires_at'], name='mobile_idem_user_id_94f308_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='mobile_idempotency_unique_per_user'),
        ),
    ]
