# Generated by Django 4.2.30 on 2026-05-03 21:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g. 1110 / 4001 / EXP-OFFICE', max_length=24)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('statistical', 'Statistical')], max_length=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='authentication.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.account')),
            ],
            options={
                'db_table': 'ledger_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('previous_hash', models.CharField(blank=True, default='', help_text="event_hash of the previous row in this org's chain", max_length=64)),
                ('event_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + ts + org)', max_length=64)),
                ('chain_position', models.PositiveBigIntegerField(db_index=True, default=0, help_text="1-based position within this org's chain")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(db_index=True, help_text='e.g. JE-2026-00123 — auto-numbered on first save.', max_length=32)),
                ('entry_date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text='External reference (invoice number, bank txn id).', max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('payment', 'Payment voucher'), ('receipt', 'Receipt voucher'), ('zatca', 'ZATCA submission'), ('bank', 'Bank reconciliation'), ('system', 'System (period close, FX revaluation)')], default='manual', max_length=12)),
                ('source_object_id', models.CharField(blank=True, db_index=True, help_text='UUID/PK of the document this entry was posted from.', max_length=64)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('base_currency', models.CharField(default='SAR', help_text='Org reporting currency at posting time.', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='1 currency = fx_rate × base_currency at posting time.', max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided (compensated)')], db_index=True, default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='If supplied, repeated saves with the same key reuse this entry.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='authentication.organization')),
                ('voided_by_entry', models.ForeignKey(blank=True, help_text='The compensating entry that voided this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voids', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'ledger_journal_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, help_text='1 from_currency = rate × to_currency', max_digits=18)),
                ('rate_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, help_text="e.g. 'SAMA', 'OpenExchangeRates', 'manual'.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='authentication.organization')),
            ],
            options={
                'db_table': 'ledger_exchange_rates',
                'ordering': ['-rate_date', 'from_currency'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('base_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='debit converted to org reporting currency.', max_digits=18)),
                ('base_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=64)),
                ('project_code', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'ledger_journal_lines',
                'ordering': ['entry', 'line_number'],
                'indexes': [models.Index(fields=['account', 'entry'], name='ledger_jour_account_3ccfdb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_line_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_line_one_side_only'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'entry_date', 'status'], name='ledger_jour_organiz_3c6254_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'source', 'source_object_id'], name='ledger_jour_organiz_2aacc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('organization', 'entry_number'), name='ledger_je_unique_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization', 'idempotency_key'), name='ledger_je_unique_idempotency_per_org'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['organization', 'from_currency', 'to_currency', 'rate_date'], name='ledger_exch_organiz_8dd108_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('organization', 'from_currency', 'to_currency', 'rate_date'), name='ledger_rate_unique_per_org_pair_date'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'account_type'], name='ledger_acco_organiz_fd16c9_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'is_active'], name='ledger_acco_organiz_cc1b92_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='ledger_account_unique_code_per_org'),
        ),
    ]
