# Generated by Django 4.2.30 on 2026-05-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField(help_text='1-12 for monthly accounting; 13 = year-end adjustment.')),
                ('name', models.CharField(help_text="e.g. '2026-05' or 'FY2026 P05'", max_length=64)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing', 'Closing in progress'), ('closed', 'Closed'), ('locked', 'Locked (auditor sign-off)')], db_index=True, default='open', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='authentication.organization')),
            ],
            options={
                'db_table': 'ledger_periods',
                'ordering': ['-fiscal_year', '-period_number'],
                'indexes': [models.Index(fields=['organization', 'status'], name='ledger_peri_organiz_697e54_idx'), models.Index(fields=['organization', 'start_date', 'end_date'], name='ledger_peri_organiz_c2aeca_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'fiscal_year', 'period_number'), name='ledger_period_unique_per_org'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='ledger_period_dates_ordered'),
        ),
    ]
