# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_number", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Transaction Anomaly"),
                            ("fraud", "Suspected Fraud"),
                            ("compliance", "Compliance Violation"),
                            ("duplicate", "Duplicate Transaction"),
                            ("manual", "Manual Finding"),
                            ("benford", "Benford's Law Violation"),
                            ("journal", "Suspicious Journal Entry"),
                        ],
                        default="anomaly",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("ai_risk_score", models.FloatField(default=0.0)),
                ("ai_findings", models.JSONField(default=dict)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("attachments", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_cases",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal note not visible to external auditors",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "case_comments",
                "ordering": ["created_at"],
            },
        ),
    ]
