# Generated by Django 4.2.29 on 2026-03-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditcase",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_cases",
                to="invoices.invoice",
            ),
        ),
    ]
