# Generated by Django 4.2.29 on 2026-03-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_email_verified_at_emailotpverification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0003_auditcase_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("extracting", "Extracting"),
                            ("normalizing", "Normalizing"),
                            ("validating", "Validating"),
                            ("review_required", "Review Required"),
                            ("action_required", "Action Required"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("review_required_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("high_risk_count", models.PositiveIntegerField(default=0)),
                ("average_risk_score", models.FloatField(default=0.0)),
                ("max_risk_score", models.FloatField(default=0.0)),
                ("last_error", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_audit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_sessions",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="audit_sessi_organiz_aa0332_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_sessi_created_d942f8_idx"
                    ),
                ],
            },
        ),
    ]
