# Generated by Django 4.2.29 on 2026-03-17 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('documents', '0002_add_document_analysis_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_user_email_verified_at_emailotpverification'),
        ('audit', '0003_auditcase_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('received', 'Received'), ('extracting', 'Extracting'), ('normalizing', 'Normalizing'), ('validating', 'Validating'), ('review_required', 'Review Required'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('review_required_count', models.PositiveIntegerField(default=0)),
                ('overall_risk_score', models.FloatField(default=0.0)),
                ('overall_risk_level', models.CharField(default='low', max_length=10)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('compliance_issues', models.PositiveIntegerField(default=0)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('executive_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('duplicate', 'Duplicate Document'), ('compliance', 'Compliance Violation'), ('fraud', 'Fraud Indicator'), ('missing_data', 'Missing Required Data'), ('amount_anomaly', 'Amount Anomaly'), ('date_anomaly', 'Date Anomaly'), ('vendor_risk', 'Vendor Risk'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('remediation', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='documents.document')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_findings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='audit.auditsession')),
            ],
            options={
                'db_table': 'audit_findings',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['organization', 'state'], name='audit_sessi_organiz_92eec8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_by'], name='audit_sessi_created_8f774d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['organization', 'status'], name='audit_findi_organiz_7f8e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['session'], name='audit_findi_session_7b6c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['severity'], name='audit_findi_severit_afb6dd_idx'),
        ),
    ]
