# Generated by Django 4.2.29 on 2026-03-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_auditsession"),
        ("documents", "0003_document_audit_session"),
        ("invoices", "0002_invoice_audit_session_invoicebatch_audit_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rule_code", models.CharField(max_length=20)),
                ("rule_name", models.CharField(max_length=255)),
                ("rule_group", models.CharField(blank=True, max_length=10)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="validation_engine", max_length=50)),
                ("first_detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_detected_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audit_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="audit.auditsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_audit_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_findings",
                        to="documents.document",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_findings",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_findings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_audit_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_findings",
                "ordering": ["-last_detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(fields=["organization", "status", "severity"], name="audit_findi_organiz_716be4_idx"),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(fields=["audit_session", "status"], name="audit_findi_audit_s_1d2adf_idx"),
        ),
        migrations.AddIndex(
            model_name="auditfinding",
            index=models.Index(fields=["invoice", "rule_code"], name="audit_findi_invoice_cac98f_idx"),
        ),
    ]
