# Generated by Django 4.2.29 on 2026-03-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_auditfinding"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditfinding",
            new_name="audit_findi_organiz_dafce2_idx",
            old_name="audit_findi_organiz_716be4_idx",
        ),
        migrations.RenameIndex(
            model_name="auditfinding",
            new_name="audit_findi_audit_s_ccd1fa_idx",
            old_name="audit_findi_audit_s_1d2adf_idx",
        ),
        migrations.RenameIndex(
            model_name="auditfinding",
            new_name="audit_findi_invoice_7481e6_idx",
            old_name="audit_findi_invoice_cac98f_idx",
        ),
    ]
