# Generated by Django 4.2.29 on 2026-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_customruledefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customruledefinition',
            name='condition_params',
            field=models.JSONField(default=dict, help_text='Parameters for the condition. Examples:\n  missing_field:    {"field": "supplier_name"}\n  amount_threshold: {"max_amount": 500000, "min_amount": 0}\n  date_check:       {"no_future_dates": true, "max_days_old": 365}\n  duplicate_check:  {}\n  pattern_match:    {"field": "invoice_number", "pattern": "^INV-\\\\d+$", "must_match": true}'),
        ),
    ]
