# Generated by Django 4.2.30 on 2026-05-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0011_working_papers'),
        ('audit', '0009_add_is_deleted_to_auditcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingPaper',
            fields=[
                ('previous_hash', models.CharField(blank=True, default='', help_text="event_hash of the previous row in this org's chain", max_length=64)),
                ('event_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + ts + org)', max_length=64)),
                ('chain_position', models.PositiveBigIntegerField(db_index=True, default=0, help_text="1-based position within this org's chain")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='e.g. WP-2026-AR-001', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('paper_type', models.CharField(choices=[('lead_schedule', 'Lead Schedule'), ('substantive_test', 'Substantive Test'), ('internal_control_test', 'Internal Control Test'), ('analytical_review', 'Analytical Review'), ('pbc_request', 'PBC (Prepared by Client) Request'), ('memo', 'Audit Memo')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('reviewed', 'Reviewed (Senior)'), ('locked', 'Locked (Partner Signed)'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('partner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('partner_notes', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_papers', to='authentication.organization')),
                ('partner_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_signed_papers', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_papers', to=settings.AUTH_USER_MODEL)),
                ('related_invoices', models.ManyToManyField(blank=True, related_name='working_papers', to='invoices.invoice')),
                ('related_papers', models.ManyToManyField(blank=True, help_text='Other working papers this paper cites (e.g. WP-100 references WP-200.3).', related_name='referenced_by', to='audit.workingpaper')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_working_papers',
                'ordering': ['reference', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WPAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='working_papers/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='audit.workingpaper')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wp_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_wp_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WPSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('preparer', 'Preparer'), ('reviewer', 'Senior Reviewer'), ('partner', 'Partner / Engagement Quality Reviewer')], max_length=16)),
                ('method', models.CharField(choices=[('drawn', 'Drawn (canvas)'), ('typed', 'Typed name'), ('otp', 'One-time-password verification'), ('x509', 'X.509 certificate')], default='typed', max_length=16)),
                ('signature_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='audit.workingpaper')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wp_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_wp_signatures',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['paper', 'role'], name='audit_wp_si_paper_i_19e88b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workingpaper',
            index=models.Index(fields=['organization', 'status'], name='audit_worki_organiz_b38840_idx'),
        ),
        migrations.AddIndex(
            model_name='workingpaper',
            index=models.Index(fields=['organization', 'paper_type'], name='audit_worki_organiz_28fc6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workingpaper',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='wp_unique_reference_per_org'),
        ),
    ]
