# Generated by Django 4.2.30 on 2026-05-03 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0010_working_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customruledefinition',
            name='expression_dsl',
            field=models.JSONField(blank=True, default=dict, help_text='Generic when/then JSON DSL — populated by the visual rule builder.'),
        ),
        migrations.AddField(
            model_name='customruledefinition',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customruledefinition',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customruledefinition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Only PUBLISHED rules run in the audit pipeline.', max_length=12),
        ),
        migrations.AlterField(
            model_name='customruledefinition',
            name='condition_type',
            field=models.CharField(choices=[('missing_field', 'Field must not be empty'), ('amount_threshold', 'Amount above/below threshold'), ('date_check', 'Invoice date validation'), ('duplicate_check', 'Duplicate invoice number'), ('pattern_match', 'Field matches regex pattern'), ('dsl', 'Custom DSL expression')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='customruledefinition',
            index=models.Index(fields=['organization', 'status'], name='custom_rule_organiz_3603c5_idx'),
        ),
    ]
