# Generated by Django 4.2.30 on 2026-05-13 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0011_custom_rule_dsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_audit_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_code', models.CharField(db_index=True, help_text='External reference, e.g. AUD-2026-001', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('engagement_type', models.CharField(choices=[('fs', 'Financial Statement Audit (ISA)'), ('ia', 'Internal Audit (IIA IPPF)'), ('review', 'Review Engagement (ISRE 2400)'), ('aup', 'Agreed-upon Procedures (ISRS 4400)'), ('comp', 'Compliance / Regulatory'), ('fraud', 'Forensic / Fraud Investigation')], default='fs', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('fieldwork_start', models.DateField(blank=True, null=True)),
                ('fieldwork_end', models.DateField(blank=True, null=True)),
                ('expected_report_date', models.DateField(blank=True, null=True)),
                ('archival_due_date', models.DateField(blank=True, help_text='ISA 230 §A21 — 60 days after report sign-off.', null=True)),
                ('stage', models.CharField(choices=[('acceptance', 'Acceptance'), ('planning', 'Planning'), ('risk_assessment', 'Risk Assessment'), ('fieldwork', 'Fieldwork'), ('review', 'Review'), ('eqr', 'Engagement Quality Review'), ('reporting', 'Reporting'), ('archived', 'Archived'), ('withdrawn', 'Withdrawn (post-acceptance)')], db_index=True, default='acceptance', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when ARCHIVED. After this point the engagement is immutable.', null=True)),
                ('strategy', models.JSONField(blank=True, default=dict)),
                ('plan_procedures', models.JSONField(blank=True, default=list)),
                ('materiality', models.JSONField(blank=True, default=dict)),
                ('risk_assessment', models.JSONField(blank=True, default=dict)),
                ('opinion_type', models.CharField(blank=True, choices=[('unmodified', 'Unmodified'), ('qualified', 'Qualified'), ('adverse', 'Adverse'), ('disclaimer', 'Disclaimer of Opinion')], default='', max_length=12)),
                ('opinion_signed_at', models.DateTimeField(blank=True, null=True)),
                ('kams_summary', models.JSONField(blank=True, default=list, help_text='ISA 701 Key Audit Matters.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('engagement_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_engagements', to=settings.AUTH_USER_MODEL)),
                ('engagement_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
                ('eqr_partner', models.ForeignKey(blank=True, help_text='ISA 220 / ISQM 1 — required for listed entity audits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqr_engagements', to=settings.AUTH_USER_MODEL)),
                ('opinion_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_engagements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_engagements', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_engagements',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditcase',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='audit.auditengagement'),
        ),
        migrations.AddIndex(
            model_name='auditengagement',
            index=models.Index(fields=['organization', 'stage'], name='audit_engag_organiz_4be4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditengagement',
            index=models.Index(fields=['engagement_type'], name='audit_engag_engagem_024c17_idx'),
        ),
        migrations.AddIndex(
            model_name='auditengagement',
            index=models.Index(fields=['period_end'], name='audit_engag_period__d421da_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditengagement',
            constraint=models.UniqueConstraint(fields=('organization', 'engagement_code'), name='audit_engagement_code_unique_per_org'),
        ),
    ]
