# Generated by Django 4.2.30 on 2026-06-23 07:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0012_alter_auditcase_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='audit/trial_balance/%Y/%m/')),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel (.xls)')], max_length=8)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validation_failed', 'Validation failed'), ('validated', 'Validated'), ('imported', 'Imported'), ('archived', 'Archived')], db_index=True, default='uploaded', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('invalid_row_count', models.PositiveIntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('difference', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('is_balanced', models.BooleanField(default=False)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_balance_imports', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_imports', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_imports', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_trial_balance_imports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('opening_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('opening_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('period_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('period_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('closing_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('closing_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('net_movement', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_rows', to='audit.auditengagement')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='audit.trialbalanceimport')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_rows', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_trial_balance_rows',
                'ordering': ('import_batch', 'row_number'),
                'indexes': [models.Index(fields=['import_batch', 'row_number'], name='audit_trial_import__1b3f67_idx'), models.Index(fields=['engagement', 'account_code'], name='audit_trial_engagem_4b25d1_idx'), models.Index(fields=['organization', 'is_valid'], name='audit_trial_organiz_55a88e_idx'), models.Index(fields=['account_type'], name='audit_trial_account_270f43_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trialbalancerow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_tb_row_per_import'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceimport',
            index=models.Index(fields=['engagement', '-created_at'], name='audit_trial_engagem_52d56f_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceimport',
            index=models.Index(fields=['organization', 'status'], name='audit_trial_organiz_9d22de_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceimport',
            index=models.Index(fields=['fiscal_year'], name='audit_trial_fiscal__324da9_idx'),
        ),
    ]
