# Generated by Django 4.2.30 on 2026-06-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('ledger', '0003_journalentry_posted_by'),
        ('audit', '0013_trialbalanceimport_trialbalancerow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('mapped_category', models.CharField(choices=[('cash_and_bank', 'Cash & bank'), ('accounts_receivable', 'Accounts receivable'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed assets'), ('other_assets', 'Other assets'), ('accounts_payable', 'Accounts payable'), ('vat_tax', 'VAT / tax'), ('loans', 'Loans'), ('other_liabilities', 'Other liabilities'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of sales'), ('payroll_expense', 'Payroll expense'), ('operating_expense', 'Operating expense'), ('finance_cost', 'Finance cost'), ('other_income_expense', 'Other income / expense'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('rule_based', 'Rule-based'), ('imported', 'Imported')], default='rule_based', max_length=12)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='0.000–1.000 for rule-based suggestions; null for manual.', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_mappings', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='audit.auditengagement')),
                ('mapped_ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_account_mappings', to='ledger.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='authentication.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_account_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_account_mappings',
                'ordering': ('engagement', 'account_code'),
                'indexes': [models.Index(fields=['engagement', 'account_code'], name='audit_accou_engagem_9f6e4b_idx'), models.Index(fields=['organization', 'mapped_category'], name='audit_accou_organiz_2f718b_idx'), models.Index(fields=['mapped_category'], name='audit_accou_mapped__21c074_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='accountmapping',
            constraint=models.UniqueConstraint(fields=('engagement', 'account_code'), name='uniq_account_mapping_per_engagement'),
        ),
    ]
