# Generated by Django 4.2.30 on 2026-06-23 08:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0014_accountmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='audit/general_ledger/%Y/%m/')),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel (.xls)')], max_length=8)),
                ('period_start', models.DateField(blank=True, db_index=True, null=True)),
                ('period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validation_failed', 'Validation failed'), ('validated', 'Validated'), ('imported', 'Imported'), ('archived', 'Archived')], db_index=True, default='uploaded', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('invalid_row_count', models.PositiveIntegerField(default=0)),
                ('journal_count', models.PositiveIntegerField(default=0)),
                ('balanced_journal_count', models.PositiveIntegerField(default=0)),
                ('unbalanced_journal_count', models.PositiveIntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('difference', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('is_balanced', models.BooleanField(default=False)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_ledger_imports', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_imports', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_imports', to='authentication.organization')),
                ('related_trial_balance_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_ledger_imports', to='audit.trialbalanceimport')),
            ],
            options={
                'db_table': 'audit_general_ledger_imports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('journal_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('line_number', models.CharField(blank=True, max_length=32)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('posting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('signed_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('description', models.TextField(blank=True)),
                ('document_number', models.CharField(blank=True, max_length=128)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=64)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('entered_by', models.CharField(blank=True, max_length=128)),
                ('source_system', models.CharField(blank=True, max_length=64)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_rows', to='audit.auditengagement')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='audit.generalledgerimport')),
                ('mapped_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_ledger_rows', to='audit.accountmapping')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_rows', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_general_ledger_rows',
                'ordering': ('import_batch', 'row_number'),
                'indexes': [models.Index(fields=['import_batch', 'row_number'], name='audit_gener_import__e1121a_idx'), models.Index(fields=['engagement', 'account_code'], name='audit_gener_engagem_9c7d6a_idx'), models.Index(fields=['organization', 'is_valid'], name='audit_gener_organiz_a6c227_idx'), models.Index(fields=['journal_number'], name='audit_gener_journal_f5e470_idx'), models.Index(fields=['account_code'], name='audit_gener_account_a4f045_idx'), models.Index(fields=['transaction_date'], name='audit_gener_transac_88353c_idx'), models.Index(fields=['posting_date'], name='audit_gener_posting_d134c1_idx'), models.Index(fields=['mapped_account'], name='audit_gener_mapped__9ad7c5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='generalledgerrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_gl_row_per_import'),
        ),
        migrations.AddIndex(
            model_name='generalledgerimport',
            index=models.Index(fields=['engagement', '-created_at'], name='audit_gener_engagem_25b2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerimport',
            index=models.Index(fields=['organization', 'status'], name='audit_gener_organiz_160e96_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerimport',
            index=models.Index(fields=['fiscal_year'], name='audit_gener_fiscal__77066a_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerimport',
            index=models.Index(fields=['period_start'], name='audit_gener_period__a00c35_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerimport',
            index=models.Index(fields=['period_end'], name='audit_gener_period__6e0f45_idx'),
        ),
    ]
