# Generated by Django 4.2.30 on 2026-06-23 10:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0015_generalledgerimport_generalledgerrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerRiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('risk_code', models.CharField(db_index=True, max_length=64)),
                ('risk_title', models.CharField(max_length=255)),
                ('risk_description', models.TextField(blank=True)),
                ('risk_category', models.CharField(choices=[('manual_entry', 'Manual entry'), ('period_end', 'Period-end posting'), ('unusual_timing', 'Unusual timing (weekend)'), ('round_amount', 'Round amount'), ('threshold_avoidance', 'Threshold avoidance'), ('sensitive_account', 'Sensitive account'), ('rare_account_combination', 'Rare account combination'), ('missing_description', 'Missing description'), ('unbalanced_journal', 'Unbalanced journal'), ('duplicate_entry', 'Duplicate entry'), ('unmapped_account', 'Unmapped account'), ('other', 'Other')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('amount_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('mapped_category', models.CharField(blank=True, max_length=32)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('needs_evidence', 'Needs evidence'), ('escalated', 'Escalated')], db_index=True, default='candidate', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_risk_findings', to='audit.auditengagement')),
                ('general_ledger_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='audit.generalledgerimport')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_risk_findings', to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gl_risk_findings', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_findings', to='audit.generalledgerrow')),
            ],
            options={
                'db_table': 'audit_gl_risk_findings',
                'ordering': ('-score', '-created_at'),
                'indexes': [models.Index(fields=['engagement', 'status'], name='audit_gl_ri_engagem_a79cf0_idx'), models.Index(fields=['organization', 'severity'], name='audit_gl_ri_organiz_f2e2bc_idx'), models.Index(fields=['general_ledger_import', 'risk_code'], name='audit_gl_ri_general_a7dcfa_idx'), models.Index(fields=['account_code'], name='audit_gl_ri_account_378877_idx'), models.Index(fields=['fingerprint'], name='audit_gl_ri_fingerp_28311d_idx')],
            },
        ),
    ]
