# Generated by Django 4.2.30 on 2026-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_generalledgerriskfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='amount_to_overall_materiality_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='amount_to_performance_materiality_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_adjusted_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_adjusted_severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=12),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_basis',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_overall',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_performance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_status',
            field=models.CharField(choices=[('not_assessed', 'Not assessed'), ('trivial', 'Trivial (≤ trivial threshold)'), ('below_performance_materiality', 'Below performance materiality'), ('above_performance_materiality', 'Above performance materiality'), ('above_overall_materiality', 'Above overall materiality'), ('unknown_amount', 'Unknown amount')], db_index=True, default='not_assessed', max_length=32),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='materiality_trivial_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
