# Generated by Django 4.2.30 on 2026-06-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0017_generalledgerriskfinding_amount_to_overall_materiality_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerRiskFindingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reviewer_note', models.TextField(blank=True)),
                ('review_reason', models.CharField(choices=[('evidence_sufficient', 'Evidence sufficient'), ('false_positive', 'False positive'), ('immaterial', 'Immaterial'), ('needs_supporting_document', 'Needs supporting document'), ('management_explanation_required', 'Management explanation required'), ('escalation_required', 'Escalation required'), ('other', 'Other')], default='other', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_risk_finding_reviews', to='audit.auditengagement')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='audit.generalledgerriskfinding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_risk_finding_reviews', to='authentication.organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_risk_finding_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_gl_risk_finding_reviews',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['finding', '-created_at'], name='audit_gl_ri_finding_41c404_idx'), models.Index(fields=['engagement', 'to_status'], name='audit_gl_ri_engagem_21817b_idx'), models.Index(fields=['organization', '-created_at'], name='audit_gl_ri_organiz_f3b357_idx'), models.Index(fields=['reviewer'], name='audit_gl_ri_reviewe_ff9a39_idx'), models.Index(fields=['to_status'], name='audit_gl_ri_to_stat_f4522f_idx')],
            },
        ),
    ]
