# Generated by Django 4.2.30 on 2026-06-23 11:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0018_generalledgerriskfindingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDifferenceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_scope', models.CharField(choices=[('general_ledger', 'General ledger'), ('mixed', 'Mixed')], default='general_ledger', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recalculated', 'Recalculated'), ('reviewed', 'Reviewed'), ('locked', 'Locked')], db_index=True, default='draft', max_length=16)),
                ('total_accepted_findings', models.PositiveIntegerField(default=0)),
                ('total_gross_misstatement', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_debit_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_credit_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_absolute_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('overall_materiality', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('performance_materiality', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('trivial_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('materiality_basis', models.CharField(blank=True, max_length=64)),
                ('exceeds_performance_materiality', models.BooleanField(default=False)),
                ('exceeds_overall_materiality', models.BooleanField(default=False)),
                ('conclusion_status', models.CharField(choices=[('no_accepted_differences', 'No accepted differences'), ('below_trivial', 'Below trivial threshold'), ('below_performance_materiality', 'Below performance materiality'), ('above_performance_materiality', 'Above performance materiality'), ('above_overall_materiality', 'Above overall materiality'), ('not_assessed', 'Not assessed (no materiality)')], db_index=True, default='no_accepted_differences', max_length=32)),
                ('summary_by_category', models.JSONField(blank=True, default=dict)),
                ('summary_by_account', models.JSONField(blank=True, default=dict)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_difference_summaries', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_summaries', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_summaries', to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_difference_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_difference_summaries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditDifferenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('gl_risk_finding', 'GL risk finding')], default='gl_risk_finding', max_length=20)),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('mapped_category', models.CharField(blank=True, db_index=True, max_length=32)),
                ('finding_risk_code', models.CharField(blank=True, max_length=64)),
                ('finding_title', models.CharField(blank=True, max_length=255)),
                ('amount_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('debit_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('credit_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('materiality_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('materiality_adjusted_severity', models.CharField(blank=True, max_length=12)),
                ('is_above_trivial', models.BooleanField(default=False)),
                ('is_above_performance_materiality', models.BooleanField(default=False)),
                ('is_above_overall_materiality', models.BooleanField(default=False)),
                ('management_response_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('agreed', 'Agreed'), ('disagreed', 'Disagreed'), ('adjusted', 'Adjusted'), ('unadjusted', 'Unadjusted')], default='not_requested', max_length=16)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_items', to='audit.auditengagement')),
                ('gl_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difference_items', to='audit.generalledgerriskfinding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_items', to='authentication.organization')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.auditdifferencesummary')),
            ],
            options={
                'db_table': 'audit_difference_items',
                'ordering': ('summary', '-amount_impact'),
            },
        ),
        migrations.AddIndex(
            model_name='auditdifferencesummary',
            index=models.Index(fields=['engagement', '-created_at'], name='audit_diffe_engagem_abf5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferencesummary',
            index=models.Index(fields=['organization', 'status'], name='audit_diffe_organiz_8e83a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferencesummary',
            index=models.Index(fields=['conclusion_status'], name='audit_diffe_conclus_165527_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferencesummary',
            index=models.Index(fields=['calculated_at'], name='audit_diffe_calcula_11bde6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferenceitem',
            index=models.Index(fields=['summary'], name='audit_diffe_summary_cdea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferenceitem',
            index=models.Index(fields=['engagement', 'account_code'], name='audit_diffe_engagem_107292_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferenceitem',
            index=models.Index(fields=['organization', 'materiality_status'], name='audit_diffe_organiz_21b75f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferenceitem',
            index=models.Index(fields=['gl_finding'], name='audit_diffe_gl_find_12e798_idx'),
        ),
        migrations.AddIndex(
            model_name='auditdifferenceitem',
            index=models.Index(fields=['mapped_category'], name='audit_diffe_mapped__0e2ffb_idx'),
        ),
    ]
