# Generated by Django 4.2.30 on 2026-06-23 12:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0019_auditdifferencesummary_auditdifferenceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedAuditAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('reclassification', 'Reclassification'), ('accrual', 'Accrual'), ('correction', 'Correction'), ('reversal', 'Reversal'), ('disclosure_only', 'Disclosure only'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('debit_account_code', models.CharField(blank=True, max_length=64)),
                ('debit_account_name', models.CharField(blank=True, max_length=255)),
                ('credit_account_code', models.CharField(blank=True, max_length=64)),
                ('credit_account_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('management_accepted', models.BooleanField(blank=True, null=True)),
                ('client_posted_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('accepted_by_management', 'Accepted by management'), ('rejected_by_management', 'Rejected by management'), ('posted_by_client', 'Posted by client'), ('not_posted', 'Not posted')], db_index=True, default='draft', max_length=24)),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_adjustments', to='audit.auditengagement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_adjustments', to='audit.auditdifferenceitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_adjustments', to='authentication.organization')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_audit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_adjustments', to='audit.auditdifferencesummary')),
            ],
            options={
                'db_table': 'audit_proposed_adjustments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['item', '-created_at'], name='audit_propo_item_id_6ef66f_idx'), models.Index(fields=['engagement', 'status'], name='audit_propo_engagem_42e555_idx'), models.Index(fields=['organization', 'status'], name='audit_propo_organiz_a4d637_idx'), models.Index(fields=['summary'], name='audit_propo_summary_36aeae_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditDifferenceItemResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('response_note', models.TextField(blank=True)),
                ('response_reason', models.CharField(choices=[('management_agreed', 'Management agreed'), ('management_disagreed', 'Management disagreed'), ('adjustment_to_be_posted_by_client', 'Adjustment to be posted by client'), ('client_refused_adjustment', 'Client refused adjustment'), ('immaterial_unadjusted', 'Immaterial — left unadjusted'), ('pending_management_reply', 'Pending management reply'), ('other', 'Other')], default='other', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difference_item_responses', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_item_responses', to='audit.auditengagement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.auditdifferenceitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_item_responses', to='authentication.organization')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='audit.auditdifferencesummary')),
            ],
            options={
                'db_table': 'audit_difference_item_responses',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['item', '-created_at'], name='audit_diffe_item_id_4446af_idx'), models.Index(fields=['engagement', 'to_status'], name='audit_diffe_engagem_bb320c_idx'), models.Index(fields=['organization', '-created_at'], name='audit_diffe_organiz_174550_idx'), models.Index(fields=['actor'], name='audit_diffe_actor_i_0904e1_idx')],
            },
        ),
    ]
