# Generated by Django 4.2.30 on 2026-06-23 12:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0020_proposedauditadjustment_auditdifferenceitemresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReadinessWorkpaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('auditor_review_required', 'Auditor review required'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('readiness_conclusion', models.CharField(choices=[('no_accepted_differences', 'No accepted differences'), ('differences_below_materiality', 'Differences below materiality'), ('unadjusted_differences_need_evaluation', 'Unadjusted differences need evaluation'), ('possible_material_impact', 'Possible material impact'), ('insufficient_evidence', 'Insufficient evidence'), ('not_assessed', 'Not assessed')], db_index=True, default='not_assessed', max_length=48)),
                ('suggested_opinion_direction', models.CharField(choices=[('no_direction', 'No direction'), ('likely_unmodified_subject_to_auditor_review', 'Likely unmodified — subject to auditor review'), ('possible_modified_opinion_subject_to_auditor_review', 'Possible modified opinion — subject to auditor review'), ('insufficient_basis_subject_to_auditor_review', 'Insufficient basis — subject to auditor review')], default='no_direction', max_length=64)),
                ('total_accepted_differences', models.PositiveIntegerField(default=0)),
                ('total_unadjusted_differences', models.PositiveIntegerField(default=0)),
                ('total_adjusted_differences', models.PositiveIntegerField(default=0)),
                ('total_pending_management_response', models.PositiveIntegerField(default=0)),
                ('total_needs_evidence', models.PositiveIntegerField(default=0)),
                ('total_absolute_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('overall_materiality', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('performance_materiality', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('conclusion_basis', models.JSONField(blank=True, default=dict)),
                ('unadjusted_summary', models.JSONField(blank=True, default=dict)),
                ('management_response_summary', models.JSONField(blank=True, default=dict)),
                ('proposed_adjustment_summary', models.JSONField(blank=True, default=dict)),
                ('legal_disclaimer', models.TextField(default='This workpaper is an AI-assisted audit readiness and opinion preparation aid. It does not constitute a formal audit opinion. The final audit opinion must be prepared and approved by a licensed auditor based on professional judgment and sufficient appropriate audit evidence.')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_workpapers', to='audit.auditengagement')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_readiness_workpapers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_workpapers', to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_readiness_workpapers', to=settings.AUTH_USER_MODEL)),
                ('sad_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_workpapers', to='audit.auditdifferencesummary')),
            ],
            options={
                'db_table': 'audit_readiness_workpapers',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', '-created_at'], name='audit_readi_engagem_707741_idx'), models.Index(fields=['organization', 'status'], name='audit_readi_organiz_8e66c2_idx'), models.Index(fields=['readiness_conclusion'], name='audit_readi_readine_16791f_idx')],
            },
        ),
    ]
