# Generated by Django 4.2.30 on 2026-07-12 09:50

import apps.audit.evidence_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_file_sha256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0021_auditreadinessworkpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvidenceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('request_reason', models.CharField(choices=[('support_finding', 'Support finding'), ('management_explanation', 'Management explanation'), ('supporting_document', 'Supporting document'), ('bank_support', 'Bank support'), ('invoice_support', 'Invoice support'), ('contract_support', 'Contract support'), ('approval_support', 'Approval support'), ('other', 'Other')], default='support_finding', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('more_evidence_required', 'More evidence required'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evidence', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requests', to='audit.auditengagement')),
                ('gl_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requests', to='audit.generalledgerriskfinding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requests', to='authentication.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_evidence', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL)),
                ('sad_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requests', to='audit.auditdifferenceitem')),
            ],
            options={
                'db_table': 'audit_evidence_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvidenceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.audit.evidence_models._evidence_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_evidence_attachments', to='documents.document')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_attachments', to='audit.auditengagement')),
                ('evidence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='audit.auditevidencerequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_attachments', to='authentication.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_evidence_attachments',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvidenceRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Evidence submitted'), ('under_review', 'Marked under review'), ('accepted', 'Evidence accepted'), ('rejected', 'Evidence rejected'), ('more_evidence_required', 'More evidence requested'), ('cancelled', 'Request cancelled'), ('attachment_added', 'Attachment added'), ('note_added', 'Note added')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_request_events', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_request_events', to='audit.auditengagement')),
                ('evidence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='audit.auditevidencerequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_request_events', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_evidence_request_events',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['evidence_request', 'created_at'], name='audit_evide_evidenc_73be09_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditevidencerequest',
            index=models.Index(fields=['organization', 'status'], name='audit_evide_organiz_2a74f3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidencerequest',
            index=models.Index(fields=['engagement', '-created_at'], name='audit_evide_engagem_d496c4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidencerequest',
            index=models.Index(fields=['gl_finding'], name='audit_evide_gl_find_14479f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidencerequest',
            index=models.Index(fields=['sad_item'], name='audit_evide_sad_ite_ffe065_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidenceattachment',
            index=models.Index(fields=['evidence_request', '-uploaded_at'], name='audit_evide_evidenc_01a44c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidenceattachment',
            index=models.Index(fields=['organization', 'is_active'], name='audit_evide_organiz_2857f8_idx'),
        ),
    ]
