# Generated by Django 4.2.30 on 2026-07-24 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0022_auditevidencerequest_auditevidenceattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevidencerequest',
            name='assigned_client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_assigned_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevidencerequest',
            name='management_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditevidencerequest',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='auditevidencerequest',
            index=models.Index(fields=['assigned_client_user', 'status'], name='audit_evide_assigne_48296f_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevidencerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_number__gt', '')), fields=('organization', 'request_number'), name='uniq_evidence_request_number_per_org'),
        ),
    ]
