# Generated by Django 4.2.30 on 2026-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auditevidencerequest_assigned_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevidencerequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Evidence submitted'), ('under_review', 'Marked under review'), ('accepted', 'Evidence accepted'), ('rejected', 'Evidence rejected'), ('more_evidence_required', 'More evidence requested'), ('cancelled', 'Request cancelled'), ('attachment_added', 'Attachment added'), ('note_added', 'Note added'), ('assigned', 'Assigned')], max_length=32),
        ),
    ]
