# Generated by Django 4.2.30 on 2026-07-24 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0024_alter_auditevidencerequestevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='last_verification_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='lifecycle_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='lifecycle_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_lifecycle_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='lifecycle_state',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('frozen', 'Frozen'), ('expired', 'Expired')], db_index=True, default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='audit.auditevidenceattachment'),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auditevidencerequestevent',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='audit.auditevidenceattachment'),
        ),
        migrations.AlterField(
            model_name='auditevidencerequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Evidence submitted'), ('under_review', 'Marked under review'), ('accepted', 'Evidence accepted'), ('rejected', 'Evidence rejected'), ('more_evidence_required', 'More evidence requested'), ('cancelled', 'Request cancelled'), ('attachment_added', 'Attachment added'), ('note_added', 'Note added'), ('assigned', 'Assigned'), ('downloaded', 'Evidence downloaded'), ('version_created', 'New version created'), ('verified', 'Integrity verified'), ('verification_failed', 'Integrity verification FAILED'), ('archived', 'Attachment archived'), ('restored', 'Attachment restored'), ('frozen', 'Attachment frozen'), ('expired', 'Attachment expired'), ('escalated', 'SLA escalation')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='auditevidenceattachment',
            index=models.Index(fields=['organization', 'lifecycle_state'], name='audit_evide_organiz_2054f3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidenceattachment',
            index=models.Index(fields=['evidence_request', 'version'], name='audit_evide_evidenc_7f2aa8_idx'),
        ),
    ]
