# Generated by Django 4.2.30 on 2026-07-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0025_auditevidenceattachment_last_verification_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='verification_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='verification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditevidenceattachment',
            name='verification_result',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('ok', 'Verified'), ('hash_mismatch', 'Hash mismatch (corrupted)'), ('missing_file', 'File missing'), ('unreadable', 'File unreadable'), ('no_digest', 'No stored digest')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditEvidenceRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy', models.CharField(choices=[('years_7', '7 years'), ('years_10', '10 years'), ('forever', 'Retain forever'), ('custom', 'Custom (years)')], default='years_7', max_length=12)),
                ('custom_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('attachments_marked', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_retention_policies', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_retention_policy', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_retention_policies', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_evidence_retention_policies',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'policy'], name='audit_evide_organiz_d2e9ab_idx')],
            },
        ),
    ]
