# Generated by Django 4.2.30 on 2026-07-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0026_auditevidenceattachment_verification_duration_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAnalyticsRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_ms', models.PositiveIntegerField(default=0)),
                ('rules_executed', models.JSONField(blank=True, default=list)),
                ('rows_analyzed', models.PositiveIntegerField(default=0)),
                ('journals_analyzed', models.PositiveIntegerField(default=0)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_analytics_runs', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_runs', to='audit.auditengagement')),
                ('general_ledger_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_runs', to='audit.generalledgerimport')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_runs', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_journal_analytics_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalAnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_journals', models.PositiveIntegerField(default=0)),
                ('analyzed_journals', models.PositiveIntegerField(default=0)),
                ('flagged_journals', models.PositiveIntegerField(default=0)),
                ('high_risk_journals', models.PositiveIntegerField(default=0)),
                ('medium_risk_journals', models.PositiveIntegerField(default=0)),
                ('low_risk_journals', models.PositiveIntegerField(default=0)),
                ('by_rule', models.JSONField(blank=True, default=dict)),
                ('by_severity', models.JSONField(blank=True, default=dict)),
                ('top_accounts', models.JSONField(blank=True, default=list)),
                ('top_users', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_summaries', to='authentication.organization')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='audit.journalanalyticsrun')),
            ],
            options={
                'db_table': 'audit_journal_analytics_summaries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalAnalyticsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('timing', 'Timing'), ('amount', 'Amount'), ('documentation', 'Documentation'), ('account', 'Account'), ('source', 'Source')], default='amount', max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_rules', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_journal_analytics_rules',
                'ordering': ('rule_code',),
            },
        ),
        migrations.CreateModel(
            name='JournalAnalyticsResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=48)),
                ('rule_name', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('journal_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('entered_by', models.CharField(blank=True, db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('affected_rows', models.PositiveIntegerField(default=0)),
                ('execution_ms', models.PositiveIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_analytics_results', to='authentication.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audit.journalanalyticsrun')),
            ],
            options={
                'db_table': 'audit_journal_analytics_results',
                'ordering': ('-score', 'rule_code', 'journal_number'),
            },
        ),
        migrations.AddIndex(
            model_name='journalanalyticsrun',
            index=models.Index(fields=['organization', '-created_at'], name='audit_journ_organiz_7c90d8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsrun',
            index=models.Index(fields=['engagement', '-created_at'], name='audit_journ_engagem_d0a4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsrun',
            index=models.Index(fields=['general_ledger_import', '-created_at'], name='audit_journ_general_d45193_idx'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsrule',
            index=models.Index(fields=['organization', 'is_enabled'], name='audit_journ_organiz_bd9a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalanalyticsrule',
            constraint=models.UniqueConstraint(fields=('organization', 'rule_code'), name='uniq_journal_analytics_rule_per_org'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsresult',
            index=models.Index(fields=['run', '-score'], name='audit_journ_run_id_0b3d18_idx'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsresult',
            index=models.Index(fields=['organization', 'severity'], name='audit_journ_organiz_38a0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='journalanalyticsresult',
            index=models.Index(fields=['run', 'rule_code'], name='audit_journ_run_id_65af2c_idx'),
        ),
    ]
