# Generated by Django 4.2.30 on 2026-07-25 17:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0027_journalanalyticsrun_journalanalyticssummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfirmationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('confirmation_type', models.CharField(choices=[('receivable', 'Customer balance (receivable)'), ('payable', 'Supplier balance (payable)'), ('bank', 'Bank balance'), ('other', 'Other')], default='receivable', max_length=12)),
                ('party_name', models.CharField(max_length=255)),
                ('party_reference', models.CharField(blank=True, max_length=128)),
                ('party_email', models.EmailField(blank=True, max_length=254)),
                ('recorded_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='SAR', max_length=8)),
                ('tolerance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('responded', 'Responded'), ('matched', 'Matched'), ('discrepancy', 'Discrepancy'), ('no_reply', 'No reply'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('response_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to='authentication.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_confirmations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_confirmation_requests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='audit_confi_organiz_d70885_idx'), models.Index(fields=['engagement', '-created_at'], name='audit_confi_engagem_0627ac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditconfirmationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_number__gt', '')), fields=('organization', 'request_number'), name='uniq_confirmation_number_per_org'),
        ),
    ]
