# Generated by Django 4.2.30 on 2026-07-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0028_auditconfirmationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditControlDeficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('financial_reporting', 'Financial reporting'), ('revenue', 'Revenue'), ('procurement_payables', 'Procurement & payables'), ('payroll', 'Payroll'), ('cash_treasury', 'Cash & treasury'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed assets'), ('it_general_controls', 'IT general controls'), ('other', 'Other')], default='other', max_length=24)),
                ('classification', models.CharField(choices=[('material_weakness', 'Material weakness'), ('significant_deficiency', 'Significant deficiency'), ('other_deficiency', 'Other deficiency')], db_index=True, default='other_deficiency', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('potential_effect', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('management_response', models.TextField(blank=True)),
                ('management_action_owner', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('management_responded', 'Management responded'), ('remediated', 'Remediated'), ('accepted_risk', 'Risk accepted')], db_index=True, default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_deficiencies', to='audit.auditengagement')),
                ('gl_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_deficiencies', to='audit.generalledgerriskfinding')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_deficiencies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_deficiencies', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_control_deficiencies',
                'ordering': ('classification', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'status'], name='audit_contr_organiz_c2315b_idx'), models.Index(fields=['engagement', 'classification'], name='audit_contr_engagem_516121_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditcontroldeficiency',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_deficiency_reference_per_org'),
        ),
    ]
