# Generated by Django 4.2.30 on 2026-07-27 12:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0029_auditcontroldeficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstantiveTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('area', models.CharField(choices=[('inventory', 'Inventory (ISA 501)'), ('fixed_assets', 'Fixed assets'), ('payroll', 'Payroll'), ('other', 'Other')], db_index=True, default='inventory', max_length=16)),
                ('item_reference', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('book_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tested_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('tolerance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('quantity_book', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quantity_counted', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('variance', 'Variance'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substantive_test_items', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substantive_test_items', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substantive_test_items', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_substantive_test_items',
                'ordering': ('area', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'status'], name='audit_subst_organiz_0ae97c_idx'), models.Index(fields=['engagement', 'area'], name='audit_subst_engagem_18dc12_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='substantivetestitem',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_substantive_reference_per_org'),
        ),
    ]
