# Generated by Django 4.2.30 on 2026-07-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0030_substantivetestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevidencerequest',
            name='confirmation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requests', to='audit.auditconfirmationrequest'),
        ),
        migrations.AddField(
            model_name='auditevidencerequest',
            name='substantive_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requests', to='audit.substantivetestitem'),
        ),
    ]
