# Generated by Django 4.2.30 on 2026-07-28 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0031_auditevidencerequest_confirmation_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPlanningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('audit_plan', 'Audit strategy & plan (ISA 300)'), ('risk_responses', 'Risk responses (ISA 330)'), ('fraud_plan', 'Fraud response plan (ISA 240)')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_records', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_records', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_records', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_engagement_planning_records',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', 'kind', '-created_at'], name='audit_engag_engagem_6d5cbf_idx'), models.Index(fields=['organization', 'kind'], name='audit_engag_organiz_ddcf6f_idx')],
            },
        ),
    ]
