# Generated by Django 4.2.30 on 2026-07-28 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0032_engagementplanningrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessedRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('fs_area', models.CharField(blank=True, db_index=True, max_length=120)),
                ('assertion', models.CharField(choices=[('existence', 'Existence / Occurrence'), ('completeness', 'Completeness'), ('accuracy', 'Accuracy'), ('cutoff', 'Cut-off'), ('classification', 'Classification'), ('valuation', 'Valuation / Allocation'), ('rights_obligations', 'Rights & obligations'), ('presentation', 'Presentation & disclosure')], db_index=True, default='existence', max_length=20)),
                ('inherent_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('significant', 'Significant')], default='medium', max_length=12)),
                ('control_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('is_significant', models.BooleanField(default=False)),
                ('is_fraud_risk', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('responded', 'Responded'), ('tested', 'Tested'), ('concluded', 'Concluded'), ('closed', 'Closed')], db_index=True, default='identified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_risks', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_risks', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_risks', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_assessed_risks',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', 'status'], name='audit_asses_engagem_43604e_idx'), models.Index(fields=['organization', 'assertion'], name='audit_asses_organiz_230cbb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessedrisk',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_assessed_risk_reference_per_org'),
        ),
    ]
