# Generated by Django 4.2.30 on 2026-07-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0033_assessedrisk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('nature', models.CharField(choices=[('test_of_controls', 'Test of controls'), ('substantive_analytical', 'Substantive analytical'), ('test_of_details', 'Test of details')], default='test_of_details', max_length=24)),
                ('timing', models.CharField(choices=[('interim', 'Interim'), ('year_end', 'Year-end'), ('subsequent', 'Subsequent events'), ('unpredictable', 'Unpredictable')], default='year_end', max_length=16)),
                ('extent', models.CharField(choices=[('reduced', 'Reduced'), ('standard', 'Standard'), ('increased', 'Increased'), ('all', 'All (100%)')], default='standard', max_length=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('not_applicable', 'Not applicable')], db_index=True, default='planned', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='audit.assessedrisk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedures', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_procedures', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_procedures', to='authentication.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_procedures',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', 'status'], name='audit_proce_engagem_b35346_idx'), models.Index(fields=['assessed_risk'], name='audit_proce_assesse_5e3343_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditprocedure',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_audit_procedure_reference_per_org'),
        ),
    ]
