# Generated by Django 4.2.30 on 2026-07-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0034_auditprocedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevidencerequest',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requests', to='audit.auditprocedure'),
        ),
    ]
