# Generated by Django 4.2.30 on 2026-07-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0035_auditevidencerequest_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcontroldeficiency',
            name='assessed_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_deficiencies', to='audit.assessedrisk'),
        ),
        migrations.AddField(
            model_name='generalledgerriskfinding',
            name='assessed_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_findings', to='audit.assessedrisk'),
        ),
    ]
