# Generated by Django 4.2.30 on 2026-07-28 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_mfa_secret'),
        ('audit', '0036_auditcontroldeficiency_assessed_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(db_index=True, max_length=40)),
                ('artifact_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('preparer', 'Preparer'), ('reviewer', 'Reviewer'), ('partner', 'Engagement partner'), ('eqr', 'EQR partner')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_signoffs', to='authentication.organization')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_engagement_signoffs',
                'ordering': ('-signed_at',),
                'indexes': [models.Index(fields=['engagement', 'artifact_type', 'artifact_id'], name='audit_engag_engagem_6f4ca4_idx'), models.Index(fields=['organization', 'role'], name='audit_engag_organiz_7df9e1_idx')],
            },
        ),
    ]
