# Generated by Django 4.2.30 on 2026-07-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_alter_user_role'),
        ('audit', '0037_engagementsignoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('management_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_remediation', 'In remediation'), ('remediated', 'Remediated'), ('accepted_risk', 'Accepted risk'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='audit.assessedrisk')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_issues', to='audit.auditengagement')),
                ('gl_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='audit.generalledgerriskfinding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_issues', to='authentication.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_issues', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_issues',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', 'status'], name='audit_issue_engagem_210776_idx'), models.Index(fields=['organization', 'severity'], name='audit_issue_organiz_935f81_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditissue',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_audit_issue_reference_per_org'),
        ),
    ]
