# Generated by Django 4.2.30 on 2026-07-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_alter_user_role'),
        ('audit', '0038_auditissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('final', 'Final'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('not_an_opinion', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_reports', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_reports', to='authentication.organization')),
            ],
            options={
                'db_table': 'audit_engagement_reports',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['engagement', '-version'], name='audit_engag_engagem_625e47_idx'), models.Index(fields=['organization', 'status'], name='audit_engag_organiz_471ead_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='engagementreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('organization', 'reference'), name='uniq_engagement_report_reference_per_org'),
        ),
    ]
