# Generated by Django 4.2.30 on 2026-07-29 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_alter_user_role'),
        ('audit', '0039_engagementreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('partner', 'Engagement partner'), ('manager', 'Manager'), ('eqr', 'EQR partner'), ('reviewer', 'Reviewer'), ('preparer', 'Preparer'), ('member', 'Team member')], default='member', max_length=12)),
                ('responsibilities', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='audit.auditengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_members', to='authentication.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_engagement_members',
                'ordering': ('role', 'assigned_at'),
                'indexes': [models.Index(fields=['engagement', 'is_active'], name='audit_engag_engagem_2a5ea1_idx'), models.Index(fields=['user', 'is_active'], name='audit_engag_user_id_0c9584_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='engagementmember',
            constraint=models.UniqueConstraint(fields=('engagement', 'user', 'role'), name='uniq_engagement_member_role'),
        ),
    ]
