# Generated by Django 4.2.30 on 2026-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0040_engagementmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditissue',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditissue',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
