# Generated by Django 4.2.30 on 2026-08-02 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0041_auditissue_source_id_auditissue_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='verdict',
            field=models.CharField(choices=[('unreviewed', 'Not yet judged'), ('true_positive', 'Correct — a real issue'), ('false_positive', 'Wrong — the rule misfired'), ('uncertain', 'Cannot tell')], db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='verdict_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='verdict_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_audit_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='verdict_note',
            field=models.TextField(blank=True, help_text='Why. A false-positive verdict without a reason tells whoever fixes the rule nothing about what to change.'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['organization', 'rule_code', 'verdict'], name='finding_rule_verdict_idx'),
        ),
    ]
