# Generated by Django 4.2.30 on 2026-08-04 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0042_finding_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPassage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard', models.CharField(db_index=True, help_text='ZATCA-ER, IAS-7, ISA-315, SOCPA-… — the short code used in citations.', max_length=32)),
                ('reference', models.CharField(blank=True, help_text='المادة 53 · §15 · para 12 — the unit a reader can look up.', max_length=64)),
                ('text', models.TextField()),
                ('source_uri', models.URLField(blank=True, help_text='Where this text was taken from, so a citation can be verified.')),
                ('language', models.CharField(default='ar', max_length=8)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_standard_passages',
                'ordering': ['standard', 'reference'],
                'indexes': [models.Index(fields=['standard', 'reference'], name='audit_stand_standar_e51d8e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='standardpassage',
            constraint=models.UniqueConstraint(fields=('standard', 'reference'), name='unique_passage_per_standard_reference'),
        ),
    ]
