# Generated by Django 4.2.30 on 2026-08-04 17:23

"""Freeze the chain partition, then make a forked chain impossible.

See authentication/0011 for the full reasoning. The backfill must run between
the AddFields and the AddConstraint: until it does, every row has
chain_partition="" while each organisation's chain independently starts at
position 1, so the constraint would compare ("", 1) across tenants and fail on
the first multi-tenant database it met.
"""

from django.db import migrations, models


def freeze_partitions(apps, schema_editor):
    WorkingPaper = apps.get_model("audit", "WorkingPaper")

    for organization_id in (
        WorkingPaper.objects.order_by().values_list("organization_id", flat=True).distinct()
    ):
        WorkingPaper.objects.filter(organization_id=organization_id).update(
            chain_partition=str(organization_id or "")
        )

    # Draft papers are legitimately unchained — WorkingPaper defers chaining
    # until sign-off. They all carry position 0 today, which under the new
    # constraint would be N copies of (partition, 0). NULL is the value a
    # unique index ignores, and the honest one for "not yet chained".
    WorkingPaper.objects.filter(event_hash="").update(chain_position=None)


def unfreeze_partitions(apps, schema_editor):
    WorkingPaper = apps.get_model("audit", "WorkingPaper")
    WorkingPaper.objects.filter(chain_position__isnull=True).update(chain_position=0)
    WorkingPaper.objects.update(chain_partition="")

class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0043_standard_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingpaper',
            name='chain_partition',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Frozen partition key (organization id) this row's chain belongs to", max_length=64),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='chain_position',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=None, help_text='1-based position within this chain; NULL until chained', null=True),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + partition)', max_length=64),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='event_hash of the previous row in this chain', max_length=64),
        ),
        # Must run before AddConstraint — see the module docstring.
        migrations.RunPython(freeze_partitions, unfreeze_partitions),
        migrations.AddIndex(
            model_name='workingpaper',
            index=models.Index(fields=['chain_partition', 'chain_position'], name='workingpaper_chain_idx'),
        ),
        migrations.AddConstraint(
            model_name='workingpaper',
            constraint=models.UniqueConstraint(fields=('chain_partition', 'chain_position'), name='uniq_chain_position_workingpaper'),
        ),
    ]
