# Generated by Django 4.2.30 on 2026-08-04 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0044_chain_partition_and_fork_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainCheckpoint',
            fields=[
                ('previous_hash', models.CharField(blank=True, default='', help_text='event_hash of the previous row in this chain', max_length=64)),
                ('event_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + partition)', max_length=64)),
                ('chain_position', models.PositiveBigIntegerField(blank=True, db_index=True, default=None, help_text='1-based position within this chain; NULL until chained', null=True)),
                ('chain_partition', models.CharField(blank=True, db_index=True, default='', help_text="Frozen partition key (organization id) this row's chain belongs to", max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_model', models.CharField(db_index=True, help_text="Model whose prefix was retired, e.g. 'AuditLog'", max_length=64)),
                ('target_partition', models.CharField(blank=True, db_index=True, help_text='chain_partition of the retired prefix', max_length=64)),
                ('up_to_position', models.PositiveBigIntegerField(help_text='Last chain_position covered by this checkpoint')),
                ('head_hash', models.CharField(help_text='event_hash of the last retired row', max_length=64)),
                ('rows_removed', models.PositiveBigIntegerField(default=0)),
                ('reason', models.CharField(choices=[('retention', 'Retention window expired'), ('migration', 'Chain rebuilt by migration')], default='retention', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_chain_checkpoints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_partition', 'up_to_position'], name='chaincheckpoint_target_idx'), models.Index(fields=['chain_partition', 'chain_position'], name='chaincheckpoint_chain_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chaincheckpoint',
            constraint=models.UniqueConstraint(fields=('chain_partition', 'chain_position'), name='uniq_chain_position_chaincheckpoint'),
        ),
    ]
