# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NLQueryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                ("interpretation", models.TextField(blank=True)),
                ("filters", models.JSONField(default=dict)),
                ("excludes", models.JSONField(default=dict)),
                ("order_by", models.JSONField(default=list)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_nl_query_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
