# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlqueryhistory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nl_query_history",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="nlqueryhistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nl_query_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
