# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=50)),
                ("language", models.CharField(default="en", max_length=5)),
                ("period_from", models.CharField(blank=True, max_length=10)),
                ("period_to", models.CharField(blank=True, max_length=10)),
                ("data", models.JSONField(default=dict)),
                ("narrative", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
