# Generated by Django 4.2.30 on 2026-05-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamProcessingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('stream', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'streaming_processing_log',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_type', 'processed_at'], name='streaming_p_event_t_38fda3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detector', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=12)),
                ('invoice_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('vendor_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_hits', to='authentication.organization')),
            ],
            options={
                'db_table': 'streaming_anomaly_hits',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'severity', 'occurred_at'], name='streaming_a_organiz_d47ce9_idx'), models.Index(fields=['organization', 'detector'], name='streaming_a_organiz_bb7414_idx')],
            },
        ),
    ]
