# Generated by Django 5.2.17 on 2026-08-19 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_safety", "0001_initial"),
        ("authentication", "0011_chain_partition_and_fork_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=32)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("auth_401", "Authentication / 401"),
                            ("rate_limit", "Rate limit"),
                            ("timeout", "Timeout"),
                            ("payload", "Payload"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("document_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to="authentication.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIUsagePayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "usage_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payload",
                        to="ai_safety.aiusagerecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["organization", "created_at"],
                name="ai_safety_a_organiz_2ccdfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["organization", "operation", "created_at"],
                name="ai_safety_a_organiz_759aa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="ai_safety_a_organiz_12bf0b_idx",
            ),
        ),
    ]
