# Generated by Django 4.2.29 on 2026-03-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditjob',
            new_name='audit_engin_organiz_2af5ea_idx',
            old_name='audit_engin_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='auditjob',
            new_name='audit_engin_audit_f_7d3e05_idx',
            old_name='audit_engin_audit_f_idx',
        ),
    ]
