# Generated by Django 4.2.30 on 2026-05-03 21:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0011_working_papers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=48)),
                ('iban', models.CharField(blank=True, db_index=True, max_length=34)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('balance_cached', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('balance_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('counterparty', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(choices=[('al_rajhi', 'Al Rajhi Bank'), ('snb', 'Saudi National Bank'), ('riyad', 'Riyad Bank'), ('sab', 'Saudi Awwal Bank'), ('bsf', 'Banque Saudi Fransi'), ('other', 'Other (statement upload only)')], max_length=16)),
                ('display_name', models.CharField(blank=True, help_text='Human label shown in the UI when an org has multiple connections to the same bank.', max_length=100)),
                ('environment', models.CharField(choices=[('mock', 'Mock (offline, deterministic)'), ('sandbox', 'Sandbox'), ('production', 'Production')], default='mock', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending credentials'), ('active', 'Active'), ('error', 'Error during last sync'), ('disabled', 'Disabled by admin')], db_index=True, default='pending', max_length=12)),
                ('credentials_encrypted', models.BinaryField(blank=True, help_text='Fernet ciphertext of a JSON dict {api_key, secret, ...}.', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='authentication.organization')),
            ],
            options={
                'db_table': 'bank_connections',
                'ordering': ['bank_code', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.bankconnection'),
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0–100 fuzzy-match score from the engine.')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Per-signal explanations driving the score.')),
                ('status', models.CharField(choices=[('suggested', 'Suggested by engine'), ('confirmed', 'Confirmed by auditor'), ('rejected', 'Rejected — not a match'), ('manual', 'Manually paired')], db_index=True, default='suggested', max_length=12)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='authentication.organization')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banking.banktransaction')),
            ],
            options={
                'db_table': 'bank_reconciliations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'score'], name='bank_reconc_organiz_f93587_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('transaction', 'invoice'), name='bank_recon_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['account', 'posted_at'], name='bank_transa_account_fa2606_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterparty', 'posted_at'], name='bank_transa_counter_f1ab26_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='bank_tx_unique_per_account'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['organization', 'status'], name='bank_connec_organiz_3b5ffd_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'bank_code', 'environment', 'display_name'), name='bank_conn_unique_per_org_env'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'account_number'), name='bank_acct_unique_per_conn'),
        ),
    ]
