# Generated by Django 4.2.29 on 2026-03-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("SA", "Saudi Arabia"),
                            ("AE", "United Arab Emirates"),
                            ("BH", "Bahrain"),
                            ("KW", "Kuwait"),
                            ("OM", "Oman"),
                            ("QA", "Qatar"),
                        ],
                        default="SA",
                        max_length=2,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("BHD", "Bahraini Dinar"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("OMR", "Omani Rial"),
                            ("QAR", "Qatari Riyal"),
                        ],
                        default="SAR",
                        max_length=3,
                    ),
                ),
                ("vat_number", models.CharField(blank=True, max_length=50)),
                (
                    "cr_number",
                    models.CharField(
                        blank=True,
                        help_text="Commercial Registration Number",
                        max_length=50,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "fiscal_year_start",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Month (1-12)"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial", models.JSONField(default=dict)),
                ("notifications", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finai_settings",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_settings",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "System Administrator"),
                            ("cao", "Chief Audit Officer"),
                            ("senior_auditor", "Senior Auditor"),
                            ("junior_auditor", "Junior Auditor"),
                            ("compliance_officer", "Compliance Officer"),
                            ("finance_manager", "Finance Manager"),
                            ("external_auditor", "External Auditor"),
                        ],
                        default="junior_auditor",
                        max_length=30,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_secret", models.CharField(blank=True, max_length=64)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="authentication.organization",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_users",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("login_failed", "Failed Login"),
                            ("document_upload", "Document Upload"),
                            ("document_process", "Document Processed"),
                            ("transaction_create", "Transaction Created"),
                            ("transaction_update", "Transaction Updated"),
                            ("anomaly_detected", "Anomaly Detected"),
                            ("case_created", "Audit Case Created"),
                            ("report_generated", "Report Generated"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("config_changed", "Configuration Changed"),
                            ("data_export", "Data Exported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="authentication.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="audit_logs_organiz_9c8c67_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="auth_users_email_9c7e62_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="auth_users_role_8a5295_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization"], name="auth_users_organiz_2c1f52_idx"
            ),
        ),
    ]
