# Generated by Django 4.2.29 on 2026-03-13 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def mark_existing_users_as_verified(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    User.objects.filter(email_verified_at__isnull=True).update(email_verified_at=timezone.now())


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_org_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EmailOTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts_count", models.PositiveSmallIntegerField(default=0)),
                ("resend_count", models.PositiveSmallIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otp_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_email_otp_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="auth_email__user_id_c89f1a_idx",
                    ),
                    models.Index(
                        fields=["user", "is_used"],
                        name="auth_email__user_id_ca75ca_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_email__expires_87417c_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(mark_existing_users_as_verified, noop_reverse),
    ]
