# Generated by Django 4.2.30 on 2026-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auditlog_retain_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='chain_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
