# Generated by Django 4.2.30 on 2026-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog_chain_hash_auditlog_previous_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_totp_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
