# Generated by Django 4.2.30 on 2026-05-11 10:40

import core.utils.encrypted_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_last_totp_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=core.utils.encrypted_field.EncryptedCharField(blank=True, max_length=320),
        ),
    ]
