# Generated by Django 4.2.30 on 2026-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('cao', 'Chief Audit Officer'), ('senior_auditor', 'Senior Auditor'), ('junior_auditor', 'Junior Auditor'), ('compliance_officer', 'Compliance Officer'), ('finance_manager', 'Finance Manager'), ('external_auditor', 'External Auditor'), ('client', 'Client User')], default='junior_auditor', max_length=30),
        ),
    ]
