# Generated by Django 4.2.30 on 2026-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='chain_position',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text="1-based position within this org's chain"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(previous_hash + payload + ts + org)', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text="event_hash of the previous row in this org's chain", max_length=64),
        ),
    ]
