# Generated by Django 5.2.17 on 2026-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_chain_partition_and_fork_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="branding",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="report_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
