# Generated by Django 4.2.29 on 2026-03-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_email_verified_at_emailotpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='auditing/documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('selected_doc_type', models.CharField(blank=True, help_text='User-provided hint', max_length=50)),
                ('detected_doc_type', models.CharField(blank=True, help_text='AI-detected type', max_length=50)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('ai_result', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('overall_risk_level', models.CharField(default='low', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_documents', to='authentication.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Document',
                'verbose_name_plural': 'Audit Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('anomaly', 'Anomaly'), ('validation', 'Validation'), ('compliance', 'Compliance'), ('recommendation', 'Recommendation')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='auditing.auditdocument')),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'ordering': ['-created_at', 'severity'],
            },
        ),
    ]
