# Generated by Django 4.2.29 on 2026-03-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='auditfinding',
            options={'ordering': ['-severity', 'finding_type']},
        ),
        migrations.RemoveField(
            model_name='auditdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='auditdocument',
            name='organization',
        ),
        migrations.AddField(
            model_name='auditdocument',
            name='executive_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='source',
            field=models.CharField(default='ai', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='ai_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='detected_doc_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Report'), ('expense_report', 'Expense Report'), ('tax_declaration', 'Tax Declaration'), ('fixed_asset', 'Fixed Asset Record'), ('sales_receipt', 'Sales Receipt'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='file',
            field=models.FileField(upload_to='auditing/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='language',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='overall_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='overall_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='selected_doc_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Report'), ('expense_report', 'Expense Report'), ('tax_declaration', 'Tax Declaration'), ('fixed_asset', 'Fixed Asset Record'), ('sales_receipt', 'Sales Receipt'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='finding_type',
            field=models.CharField(choices=[('anomaly', 'Anomaly'), ('validation', 'Validation'), ('compliance', 'Compliance'), ('risk', 'Risk')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
