# Generated by Django 4.2.29 on 2026-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_alter_auditdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdocument',
            name='overall_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
    ]
