# Generated by Django 4.2.29 on 2026-03-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0003_add_critical_risk_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditfinding',
            options={'ordering': [models.Case(models.When(severity='critical', then=models.Value(0)), models.When(severity='high', then=models.Value(1)), models.When(severity='medium', then=models.Value(2)), models.When(severity='low', then=models.Value(3)), default=models.Value(4), output_field=models.IntegerField()), 'finding_type']},
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
    ]
