# Generated by Django 4.2.29 on 2026-03-25 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_audit_session_invoicebatch_audit_session'),
        ('authentication', '0004_auditlog_retain_until'),
        ('reports', '0001_initial'),
        ('auditing', '0004_add_critical_severity_fix_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRuleEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard', models.CharField(choices=[('gaap', 'GAAP'), ('ifrs', 'IFRS')], max_length=10)),
                ('rule_code', models.CharField(db_index=True, max_length=50)),
                ('rule_title', models.CharField(max_length=255)),
                ('rule_category', models.CharField(choices=[('recognition', 'Recognition'), ('classification', 'Classification'), ('completeness', 'Completeness'), ('consistency', 'Consistency'), ('cutoff', 'Cutoff'), ('documentation', 'Documentation'), ('anomaly', 'Anomaly'), ('disclosure', 'Disclosure')], max_length=30)),
                ('rule_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('insufficient_data', 'Insufficient Data')], max_length=20)),
                ('rule_severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('observation', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('score_impact', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=1.0)),
                ('related_fields', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_rule_evaluations', to='auditing.auditdocument')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_rule_evaluations', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_rule_evaluations', to='authentication.organization')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_rule_evaluations', to='reports.report')),
            ],
            options={
                'db_table': 'accounting_rule_evaluations',
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['organization', 'standard'], name='accounting__organiz_65c631_idx'), models.Index(fields=['organization', 'rule_code'], name='accounting__organiz_298720_idx'), models.Index(fields=['organization', 'report'], name='accounting__organiz_861a96_idx'), models.Index(fields=['organization', 'invoice'], name='accounting__organiz_586f76_idx'), models.Index(fields=['rule_status'], name='accounting__rule_st_60802d_idx')],
            },
        ),
    ]
