# Generated by Django 4.2.30 on 2026-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0005_accountingruleevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdocument',
            name='detected_doc_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Report'), ('expense_report', 'Expense Report'), ('tax_declaration', 'Tax Declaration'), ('fixed_asset', 'Fixed Asset Record'), ('sales_receipt', 'Sales Receipt'), ('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_order', 'Sales Order'), ('quotation', 'Quotation'), ('proforma_invoice', 'Proforma Invoice'), ('goods_receipt_note', 'Goods Receipt Note'), ('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('cash_voucher', 'Cash Voucher'), ('journal_entry', 'Journal Entry'), ('general_ledger', 'General Ledger'), ('ledger', 'Ledger'), ('contract', 'Contract'), ('supplier_statement', 'Supplier Statement'), ('customer_statement', 'Customer Statement'), ('vat_return', 'VAT Return'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='selected_doc_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('payroll', 'Payroll Report'), ('expense_report', 'Expense Report'), ('tax_declaration', 'Tax Declaration'), ('fixed_asset', 'Fixed Asset Record'), ('sales_receipt', 'Sales Receipt'), ('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_order', 'Sales Order'), ('quotation', 'Quotation'), ('proforma_invoice', 'Proforma Invoice'), ('goods_receipt_note', 'Goods Receipt Note'), ('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('cash_voucher', 'Cash Voucher'), ('journal_entry', 'Journal Entry'), ('general_ledger', 'General Ledger'), ('ledger', 'Ledger'), ('contract', 'Contract'), ('supplier_statement', 'Supplier Statement'), ('customer_statement', 'Customer Statement'), ('vat_return', 'VAT Return'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
