# Generated by Django 4.2.30 on 2026-05-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditing', '0006_alter_auditdocument_detected_doc_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIValidationDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='ar', help_text="ISO 639-1 — 'ar', 'en', 'mixed'", max_length=8)),
                ('document_type', models.CharField(blank=True, help_text="e.g. 'invoice', 'purchase_order'", max_length=64)),
                ('source_uri', models.URLField(blank=True, help_text='S3/local path to the labeled CSV/JSONL file.')),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('labeling_method', models.CharField(blank=True, help_text='manual / semi-auto / vendor', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = platform-wide dataset shared across tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_validation_datasets', to='authentication.organization')),
            ],
            options={
                'db_table': 'ai_validation_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('ocr', 'Invoice OCR / extraction'), ('handwriting', 'Handwritten receipt recognition'), ('duplicate', 'Duplicate invoice detection'), ('fraud', 'Fraud / anomaly detection'), ('vat_check', 'VAT recalculation'), ('cash_forecast', 'Cash-flow forecasting'), ('vendor_risk', 'Vendor risk scoring'), ('benford', "Benford's law"), ('other', 'Other')], db_index=True, max_length=32)),
                ('model_version', models.CharField(help_text="e.g. 'gpt-4o-2026-05', 'pyocr-tesseract-5.3'", max_length=64)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('false_positive_rate', models.FloatField(blank=True, null=True)),
                ('false_negative_rate', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('bias', models.FloatField(blank=True, null=True)),
                ('field_accuracy', models.FloatField(blank=True, null=True)),
                ('document_accuracy', models.FloatField(blank=True, null=True)),
                ('character_error_rate', models.FloatField(blank=True, null=True)),
                ('word_error_rate', models.FloatField(blank=True, null=True)),
                ('average_processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('true_positives', models.PositiveIntegerField(blank=True, null=True)),
                ('false_positives', models.PositiveIntegerField(blank=True, null=True)),
                ('true_negatives', models.PositiveIntegerField(blank=True, null=True)),
                ('false_negatives', models.PositiveIntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('with_limits', 'Approved with limitations'), ('not_approved', 'Not approved'), ('pending', 'Pending review')], default='pending', max_length=16)),
                ('approver_notes', models.TextField(blank=True)),
                ('raw_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='auditing.aivalidationdataset')),
            ],
            options={
                'db_table': 'ai_validation_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['component', '-created_at'], name='ai_validati_compone_18af07_idx'), models.Index(fields=['dataset', '-created_at'], name='ai_validati_dataset_cea632_idx'), models.Index(fields=['decision'], name='ai_validati_decisio_8625a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aivalidationdataset',
            index=models.Index(fields=['organization'], name='ai_validati_organiz_7c7b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='aivalidationdataset',
            index=models.Index(fields=['document_type'], name='ai_validati_documen_00417c_idx'),
        ),
    ]
